- CONTRIBUTING.md
Add issue label links, note that 'beginner seems to actually be 'good first issue'.
Fix external link to sonarcloud.io though maybe that should link a page specific for this project.
Links in documentation should go somewhere.
People will be able to find issues to work on from the CONTRIBUTING doc more easily.
More people will have to look at this pull request description template.
Markdown preview, click on links.
> Fix inline links in CONTRIBUTING.md

- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialStartup.java
* An NPE can sometimes occur when running unit tests which can trigger the `TutorialStartup` class to be called
* This fix also aligns this class with how other `WindowManager.getDefault().findTopComponent` calls are handled such as `KTrussAction.java`
> Fix an NPE

- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/constellation_client.py
Add the `dtype=False` parameter to calls to pandas.read_json() in get_dataframe() and get_graph_attributes().
This stops pandas from inferring types based on the column values.
Add `dtype=False` to the `pandas.read_json()` calls in `constellation_client.py`.
This is done according to the pandas documentation at https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html?highlight=read_json#pandas.read_json: if dtype is False, then don’t infer dtypes at all.
The client dataframe will contain correctly typed columns.
There should be no negative impacts.
Rerun the example in the issue description to see that the column types are correct and the values have not been modified.
Issue #133.
> :bug: Fix issue #133 - do not infer column types.

- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/blaze/BlazePluginUtilities.java
Issue #133 caused vertex ids to be strings in a dataframe. (Previously they were inferred as integers.) Using the vertex ids as-is to call the addcustomblaze plugin causes the plugin to fail because it wsa incorrectly expecting integer ids rather than strings.
This fix allows the addblaze and addcustomblaze plugins to accept string ids (and integer ids for backwards compatibility).
Re-ran the steps to reproduce in issue #139.
#139
> :bug: Allow vertex ids to be strings.

- CoreWebServer/src/au/gov/asd/tac/constellation/filetransport/FileListener.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/GraphServlet.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/PluginServlet.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/RecordStoreServlet.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/swagger/constellation.json
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/constellation_client.py
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/impl/GraphImpl.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/impl/PluginImpl.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/impl/RecordStoreImpl.java
This PR adds graph_id as a parameter to several REST APIs to allow operations on graphs other than the currently active graph.
This PR makes it much easier to work with multiple graphs at once.
None. The REST API with no graph_id specified still works on the currently active graph.
The notebooks_and_constellation notebook still works. The new graph-ids notebook demonstrates the new API.
Issue #142.
> :sparkles: Graphids

- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/CorePluginRegistry.java
- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/zoom/RotateCameraPlugin.java
- CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/camera/CameraUtilities.java
Adds a plugin to rotate the camera programmatically.
This is basic functionality.
The camera can be manipulated from a REST client.
None.
The plugin was run from a Python client to verify the functionality.
N/A
> :sparkles: Add RotateCamera plugin.

- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/CorePluginRegistry.java
- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/zoom/SetCameraVisibilityRange.java
This plugin enables access to the camera's visibilityLow and
visibilityHigh variables.
None.
The plugin provides access to the renderer's camera, which is in core.
The ability to use existing but unexposed functionality.
None.
Tested from a Jupyter notebook.
None.
> Add SetCameraVisibilityRange plugin.

- CoreImportExport/src/au/gov/asd/tac/constellation/importexport/delimited/ImportAttributeDefinition.java
- CoreImportExport/src/au/gov/asd/tac/constellation/importexport/delimited/ImportDelimitedPlugin.java
Use rowIndex as attribute value if attributes selected column = -1.
Update all calls to ImportAttributeDefinition.setValue() to use rowIndex.
- Update ImportAttributeDefinition.setValue() to accept a rowIndex parameter. This parameter will be used in cases where an import uses the **Row** column, as this column has index -1 and is not currently handled by logic. We need to pass this index in as the supplied parameters do not provide enough information to determne it.
- The 4 existing calls to ImportAttributeDefinition.setValue() are all made from loops iterating over rows and creating attributes, as such, modify the calls to also send the row index.
Considered passing in value as extra columns of the row parameter, but this required a little extra refactoring and would be less efficient …
> Added rowIndex as 4th parameter to ImportAttributeDefinition.setValue().

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java
The change handles the case where a user opens constellation, and launches the Data Access View (DAV). The Execute button (GO) is disabled. The change allows the user to select a plugin to run, and a default graph be launched upon selection. this allows the user to still utilise Constellation to its full effect, as well as add significant UX improvement. This is more effective than showing the user an error message and them have to manually correct the issue.
The code checks if there is a graph currently open, if a plugin is selected and if that plugin's parameters are valid. Once a graph is not present, but all other conditions are met, a new default graph is launched, allowing the user to proceed to click the go button and run the plugin.
Add checking to the update method within …
> DAV graph creation issue#158

- CoreImportExport/src/au/gov/asd/tac/constellation/importexport/delimited/ImportDelimitedPlugin.java
Check import definitions and if positional values are found (ie: x, y, z) then prevent auto arrangers kicking in. If no positional information exists, then allow auto arrangers to operate.
THIS PULL REQUEST ADDS UPDATE TO DESTINATION MISSED IN #173
Considered where check for position should be made - however found this to be the only real option.
Requested bug fix
Allow positional values imported be used to render node positions
If a user imports nodes with positional data but then imports transactions with no positional information, the auto arranger kicks in. This has been agreed with @arcturus2  as acceptable.
Imported nodes with no positions - confirmed auto arranger kicked in.
Imported nodes with just X set - confirmed a horizontal line of nodes displayed.
Imported nodes with just Y …
> Use VisualConcept.VertexAttribute(X,Y,Z) rather than magic strings.

- CoreDependencies/src/ivysettings.xml
- build.xml
this was previously causing a error 501 from the Maven servers
Dependencies were previously done through http which Maven servers no longer except. They now recommend using the new https servers.
None were considered unless we really needed to pull dependencies over http for some reason.
We can now build Constellation
Nothing of significance.
I rebuilt and can confirm Netbeans now uses the https server.
None
> changed http to https for Maven central

- .travis/sonar.sh
PR adds skipping of running `sonar-scanner` for forks since the secret key is not injected in forks [for security](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions).
> skip sonar-scanner for forks

- .travis.yml
- CHANGELOG.md
- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt
Disables shallow clone for SonarCloud, as recommended by [the docs](https://docs.travis-ci.com/user/sonarcloud/#accessing-full-scm-history)
> Disable shallow clone for SonarCloud

- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/DateAttributeDescription.java
- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/LocalDateTimeAttributeDescription.java
- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/ZonedDateTimeAttributeDescription.java
- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/DateAttributeDescriptionV0.java
- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/TimeAttributeDescriptionV0.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedFileImporterStage.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportController.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/RunPane.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/geospatial/ExportToShapefilePlugin.java
- CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/MarkerUtilities.java
Expand the error message to include the required data format for data input that don't match various elements in the code 
Modifying for everything including floats/integers was considered but I think most people know this already?
As a user, would be helpful to know what internal format will be used
As a user, would be helpful to know what internal format will be used
Will need to be maintained if the internal format does end up changing
- How did you verify that all new functionality works as expected?
Ran and tested this manually (for example, ingesting a new .csv with an incorrect datetime format)
- How did you verify that all changed functionality works as expected?
This is only modifying the existing error message
- How did you verify that the change has not introduced any …
> Updating error messages with expected default formats

- CHANGELOG.md
- CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewPane.java
This addresses issue 'Table View Column Selection - Search Columns #375'
As outlined in issue 375 the column selection can become unwieldy when many attributes are used.  A blank analytic graph has more then a page of attributes. 
I've added in a simple search that allows the user to filter the attributes by name within the column selection allowing easier selection of attributes.
_Simple search form at the top of the attributes._
_An example of the filtering of attributes._
This feature makes the column selection easier for the user.
1. Open a graph
2. Open the Table View 
3. Click the column selection button
4. Enter search term in the search box
> Add feature to search / filter in Table View Column Selection

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/framework/VisualInteraction.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GLRenderer.java
:bug: reverting canvas scaling - unfortunately, while we can scale the canvas during a reshape in `GLRenderer`, and we can scale the canvas for interactions in `InteractiveGLVisualProcessor`, we cannot scale the canvas for event listeners as that would only be possible by changing private methods within `GLCanvas` itself.
> javahelp-update

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/framework/VisualInteraction.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
On MacOS the render target for GLCanvas is being scaled correctly (possibly because of custom code in JOGL but I haven't confirmed this, however the mouse positions from Java AWT are coming through as not scaled (ie. MouseEvent.java ->event.getPosition()). This change adds code to get the correct scale from the GLCanvas' transform matrix and apply it to the mouse points.
> Bug #387 Fix graph/mouse offset issue on MacOS

- CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/scatter/Scatter3dArranger.java
Allow logs for negative numbers.  Log(-veNumber) 
As it was, I had set everything to be 0
Already is.
Able to see more visual based information for negative numbers.
Nil
Was checked via different datasets being thrown at it.
Nil.
> Scatter3d - allow negative numbers to have logarithmic expansion as well

- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GraphRenderable.java
- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/SharedDrawable.java
There is an issue on MacOS where JOGL code to change the GL context using release()/makeCurrent() can cause a thread lock. It looks like this issue was occurring when trying to update the glyph textures (nodeLabel and connectionLabel text). As the Blaze render calls happen after the labels it also caused the Blazes to disappear.  An explanation of the issue was found in Chapter 2 of 'Pro Java 6 3D Game Development':
This coding approach means that the context is current for the
entire duration of the thread's execution. This causes no problems
on most platforms (e.g. it's fine on Windows), but unfortunately
there's an issue when using X11. On X11 platforms, a AWT lock is
created between the GLContext.makeCurrent() and GLContext.release()
calls, stopping mouse and keyboard input from being …
> Fix labels not rendering on MacOS (#486)

- CHANGELOG.md
- CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccess.java
Fixed a bug preventing v1 graphs from being open. The exception was:
```
SEVERE [global]
java.lang.ArrayIndexOutOfBoundsException: Index -1107 out of bounds for length 64
at au.gov.asd.tac.constellation.graph.StoreGraph.getFloatValue(StoreGraph.java:1882)
at au.gov.asd.tac.constellation.graph.visual.framework.GraphVisualAccess.getConnectionVisibility(GraphVisualAccess.java:1134)
at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.LineBatcher.bufferColorInfo(LineBatcher.java:258)
at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.LineBatcher.lambda$createBatch$1(LineBatcher.java:165)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.LineBatcher.createBatch(LineBatcher.java:161)
at …
```
> Fixed a bug preventing v1 graphs from being open.

- CHANGELOG.md
- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/OverviewPanel.java
- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelineTopComponent.java
Added a fix for the bug in the timeline view where the box in the summary window would shrink when panning the timeline past the bounds of the of the summary window.
Fix for a bug in a feature of Core
1. Open a new graph and create a sphere graph
2. Open timeline view ensuring that summary window is visible
3. Pan timeline across and observe box in summary view doesn't change its size when going past summary window bounds
4.  Verify that the expected ways to change the size of the box (e.g. zooming) still behave as expected
#498
> Timeline panning bug fix

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/HitTester.java
- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GLRenderer.java
- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GLVisualProcessor.java
- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/GLTools.java
* JOGL version 2.3.2 on Windows doesn't correctly support DPI scaling.
setSurfaceScale() is not overridden in WindowsJAWTWindow so it is not
possible to scale the canvas and mouse events at this level.  It
should be noted that it is overridden in MacOSXJAWTWindow.  Where manual
scaling is required the caller scales each GL viewport and
ensures hit tests take that size into account.
* Changes annoted with Windows-DPI-Scaling comment.
This code is restricted only to Windows OSes, but has only been tested on Windows 10.  It is possible this may cause incorrect rendering and selection offsets on other versions of Windows.
> Windows-DPI-Scaling-Fix

- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/LabelDropper.java
Added a catch for ClassCastException to account for the issue where you would get the exception when you drag a label into the graph.
Looked at options around handling the case when casting ByteBufferInputStream to ByteBuffer (the case that was causing the exception) but ByteBufferInputStream is contained in a private which we can't edit.
Also looked at other options around what to do in the catch block for ClassCastException but ultimately doing nothing felt right.
- opened a new graph and the attribute editor
- left-clicked and dragged an attribute label from the attribute editor to the graph space
- right-clicked and dragged an attribute label from the attribute editor to the graph space
#448
> Drag from Attribute Editor the graph exception resolution

- CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java
Fixed a null pointer that would sometimes appear in Analytic view.
The cause of the bug was a race condition between 2 threads that were both editing the value of a field. One had locks applied to prevent a race condition but the other thread was missing these same locks meaning the race condition was still possible (and a null pointer would occur the relevant code from these threads were executed in a particular order). Applying these same locks to the other thread (which was possible) prevents this.
This needs to be run in debug in order to best see the results (as this was the best way to get the NPE to occur more frequently
#456
> Analytic View Pane null pointer fix

- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/Bundle.properties
- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java
- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/HierarchicalStateIoProvider.java
- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/NestedHierarchicalDisplayPanel.java
- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/Bundle.properties
- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/KTrussControllerTopComponent.java
Fix a bug with hierarchical clustering #543
Fix a bug with auto-save/save of attribute not working with state.step = -1
Fix a null pointer issue when adding vertices to graph, and toggling interactive. 
Add text to button to allow visible confirmation that the view interactive mode is enabled or disabled. #190 
The clustering menus are now consistent, and when loaded on a graph without state will have the interactive button disabled, and cluster enabled. When cluster is ran, the interactive button will be enabled for use. For graphs with states, this consistency is kept at close and open of the view and or graph.
N/A
Fixes bugs, improves ux
Now less error prone and easier for a user to utilize.
Fix a bug with auto-save/save of attribute not working with state.step = -1
This fix is …
> :art: Clustering interactions ux + bug fix

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/SaveAsAction.java
When closing an unsaved graph, closing the 'Close' dialog no longer opens the 'Save Graph' dialog. 
When cancelling or closing the 'Save Graph' dialog, the unsaved graph is no longer discarded.
N/A
Better UX as this is preventing users from loosing unsaved graphs.
Better UX as this is preventing users from loosing unsaved graphs.
N/A
Case A
Open new graph
Make a change
X on graph tab to close
X on close prompt
-> No Save Graph Dialog opening and close operation is cancelled (unsaved graph still exists).
Case B
Open new graph
Make a change
X on graph tab to close
Save
Close Save File Dialog || Press Cancel
->Close operation is cancelled (unsaved graph still exists)
#508
> Closing the close graph prompt exits graph without save

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/SourcePane.java
The Delimited File Import is not intended to work across file types. When files of multiple types are added and clicking between them errors can be thrown as it's trying to parse in the selected `Import File Parser` type.
So we can restrict the file type in the file selection pop up to only contain the selected Import File Parser type, and once a file is added, that drop down will be locked, to avoid adding other types later.
Change the file type automatically in the `Import File Parser`, when clicking between the files.
Better UX
Better UX
N/A
- In the Delimited File Importer, select a CSV in `Import File Parser` type. -> You should not be able to select Excel or any other file type at the same time or later.
-  The `Import File Parser` selection should be disabled when any file is …
> Delimited File Import: Issues in the preview with multiple file types

- CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/arrangements-idx.xml
- CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/arrangements-map.xml
- CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/arrangements-toc.xml
- CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/ArrangeInHierarchyAction.java
- CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/ArrangeInBubbleTreeAction.java
Help pages over time have linked to the wrong module paths
This Pr fixes those so the help files link back up.
*bubble tree action - Does not have a proper documentation page, just a page with the title `bubble tree action`
*hierarchy action
Added a constant to hold the help location so it is easily seen within the classes in the need for future changes
> fix help page links

- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/FontInfo.java
- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/GlyphsFrame.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/SwaggerServlet.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/restapi/RestServiceUtilities.java
The parameters of `body` type in the REST API are broken. The request doesn't add any content for any user input.
E.g.:
plugins parameter in run_plugins endpoint
args parameter in run_plugin endpoint
data parameter in add_recordstore endpoint
N/A
Fixes the bug
The endpoints are now usable with json type parameters. This can be improved to contain `Example Value` which will be fixed in another case.
N/A
1. Open Swagger (Run constellation and `Tools`->`Start Rest Server` then `Display Rest Server Documentation)`
2. Try any of the above endpoints in the REST API with a valid json input
3. Verify it worked with a successful response message and the request should contain the JSON you entered.
https://github.com/constellation-app/constellation/issues/654
> Fix the Body type parameters in the Rest API

- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/parser/CSVImportFileParser.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/parser/InputSource.java
* :racehorse: Dramatically improve preview performance of CSV files
The issue was that the preview was still loading all of the data. It now properly streams.
Try downloading https://www.kaggle.com/gidutz/autotel-shared-car-locations/data and run a preview. The import still fails with out of memory and is still something that needs fixing.
Try loading a large csv file. I've referenced a Kaggle dataset as an example.
#611
> Dramatically improve preview performance of CSV files

- CHANGELOG.md
- CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV4UpdateProvider.java
Adding certain nodes to a v1 graph opened in v2 will introduce duplicate types. This is because the Type have changed (which is the validation and detection regex).
We can use the Schema upgrade framework to detect old graphs and then upgrade them. Once this change goes through, the Analytic Schema version will be 4.
Supporting backwords compatibilty is something we always want to do in Constellation to make it seamless for users to continue working with their graphs and not worry about version upgrades breaking their graphs.
1. I created a graph in v1.3.1 using [this script](https://gist.github.com/arcturus2/5d211d9f993f240564011ee42353fcdb) run in the Scripting View. There are 27 nodes.
2. Opened the graph in v2 and ran the script again. This showed 13 new nodes. These needed to be …
> Upgrade Schema Vertex Types - Fixes #730

- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/StartRestServerAction.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/WebServer.java
The pop up message when starting the Rest Server saying `Web server started` is displayed for each time the `Tools` > `Start Rest Server` menu item is clicked. This gives a false impression of starting multiple servers.
Disable menu item when the server is already running?
Less confusion for user
Better UX
N/A
1. Click `Tools` > `Start Rest Server` menu item. The pop up message should say `Web server started`
1. Click `Tools` > `Start Rest Server` menu item again. The pop up message should say `Web server already started`
https://github.com/constellation-app/constellation/issues/711
> Reword the pop up  notification when the REST server is already started

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPlugin.java
In `Split Nodes Plugin` in Data Access View,  if `Correlation` exists in the `Transaction Type` drop down list, it was applying "Correlation" instead of the user selected value. 
In `Extract words from text plugin`  if the `Content` is there in the `Words to Extract` drop down, it was applying "Content" instead of the user selected value. 
N/A
Bug Fix
Bug Fix
N/A
1. Open a graph. Open DAV and Attribute Editor
2. Rename one of the nodes to `abc;def;ghi` (identifier` in Attribute Editor)
3. In the DAV, in the `Split Nodes Plugin`, set the split character as ';' and leave the transaction type empty.
4. Ensure the renamed node is selected and run the plugin
5.  If "Correlation" exists in the  drop down list, the transaction(s) formed from the plugin should be of the type Correlation.
6. …
> Split Nodes and Extract words from text plugins to default values in drop downs only if they are null

- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt
- CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationPreferenceKeys.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlEvent.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/QualityControlRule.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButton.java
- CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/event/QualityControlEventNGTest.java
- CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/QualityControlRuleNGTest.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/json/JsonUtilities.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/json/JsonUtilitiesNGTest.java
This PR adds Quality categories to replace the visual representation of quality scores. 
It does not completely rid the code of "scores", as completely getting rid of the abstract
`getQuality()` method would cause other rules to break.
The QualityControlView table and the Data access view will now show categories of quality, as opposed to scores.
The categories map to int values which are representative of the old values. for example, the quality score previously used will map to a category. 
* MissingTypeRule RISK = 90 , maps to SEVERE.
DEFAULT = 1 - 29
INFO = 30 - 59
WARNING = 60 - 89
SEVERE = 90 - 94
FATAL = 95 +
An alert box now is implemented to map rules to each priority level. Allowing for manual overriding of specific rules or rules which are important to the user.
Highest …
> :art: Implement quality categories

- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/similarity/LevenshteinDistancePlugin.java
- CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/ParameterValue.java
- CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/SingleChoiceParameterType.java
This change allows the get and set of object value within `SingleChoiceParameterType` to be used to update the `PluginParameter`. Previously, on updating of the plugin parameters through a graph update would cause only the current selection to be updated. Now, it will update all possible choices and the current selection.
This change also includes a null check which was found through testing.
Add an `updateParameters()` method within all `ParameterTypes` which is called on updateParameters calls. This would allow any current usages of `getObjectValue()` to remain unchanged.
bugfix
Fixes the issue where plugin values are not updated on graph changes
Possible usage of `getObjectValue()` elsewhere
Tested opening and closing graphs, selecting and running plugin.
#768
> single choice parameter type not updating fix

- CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/Bundle.properties
- CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/Hashmod.java
- CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/HashmodAction.java
- CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/HashmodPanel.form
- CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/HashmodPanel.java
Modifies HashMod to be able to specify that a certain field in a vertix should be matched to another field in a vertex (and hence draw a transaction between them) if the values match.  Essentially a foreign key type arrangement (ManagerId -> EmployeeId for example)
To do things manually 
Hashmod is already in the core and this is extending it to allow transactions to be put into the mix as well as vertices.
Users will be able to specify that a field in a vertex should match another field's value and then a transaction will be created.
None foreseen (as the user controls what gets linked in)
Have implemented it twice actually and have checked it against a few different data sets that I can think of (floor plans and a made up manager-employee structure)
Nil known.
> Add transactions into existing hashmod plugin

- CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/axis/LogarithmicAxis.java
Add an if statement which will change the default minimum value from 0
to 1 if the logarithmic axis is called for an empty graph.
Stops an out of memory exception from occuring when a logarithmic axis is selected for a plot with no nodes.
Unknown
https://github.com/constellation-app/constellation/issues/815
> :bug: Alternate minimal value for empty graph in logarithmic axis.

- CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java
Stops analytic view breaking bug.
Side effects yet to be discovered by fairly minimal testing.
https://github.com/constellation-app/constellation/issues/891
> :bug: updateSelectablePluginsParameters() now updates aggregator param.

- .gitignore
- CoreVulkanDisplay/src/au/gov/asd/tac/constellation/visual/vulkan/renderables/CVKFPSRenderable.java
- CoreVulkanDisplay/src/au/gov/asd/tac/constellation/visual/vulkan/renderables/CVKIconsRenderable.java
- CoreVulkanDisplay/src/au/gov/asd/tac/constellation/visual/vulkan/renderables/CVKLoopsRenderable.java
- CoreVulkanDisplay/src/au/gov/asd/tac/constellation/visual/vulkan/resourcetypes/CVKIconAtlasSerializable.java
- CoreVulkanDisplay/src/au/gov/asd/tac/constellation/visual/vulkan/resourcetypes/CVKIconTextureAtlas.java
- CoreVulkanDisplay/src/au/gov/asd/tac/constellation/visual/vulkan/resourcetypes/CVKImage.java
- CoreVulkanDisplay/src/au/gov/asd/tac/constellation/visual/vulkan/utils/CVKUtils.java
- renderer.conf
[Load times] Icon atlas caching
* Added new flag to renderer.conf to allow caching icon atlas to and from disk.
* Fixed CVKImage only ever writing and mapping the first layer.
* Made renderer.conf variable parsing exception tolerant.
* Some TODOs in this MR that need to be addressed before this feature could be called robust.
> [Load times] Icon atlas caching

- CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/ValueInputPane.java
Fixed a bug for Remember-dropdownlist-options feature. The value input pane needs to pickup first element
from the recent values list.
To display the previous value of the text correctly.
To display the previous value of the text correctly.
1.Open DA view and run a plugin which uses a text input.
2.Close DA view
3.Open DA view and verify the previous value of the text displayed.
> bugfix remember-dropdownlist-options for Valueinputpane

- CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersPane.java
Fixed the issue where plugins in the data access view would be enabled upon expanding the parameters (if recent values had been applied).
The cause of the issue was a parameter listener that was being added before the parameter pane was created (which would be triggered if recent parameter values were applied to the parameter). Since the listener isn't actually needed before the pane is created, this listener has now been added after the pane is created.
Fixes a bug in core
Plugins aren't unexpectedly enabled
Nil
#25
> Data Access Plugins bug fix

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java
The split nodes plugin when run would change the icons and colours of nodes due to the complete with schema plugin being run by default. A checkbox has been added to the split nodes plugin to allow for the user to decide whether they wish for complete with schema to be run on the selected nodes. The selected nodes which the split nodes plugin runs on are placed into a subgraph so that if the user chooses to use the complete with schema plugin it only affects the nodes in that subgraph instead of altering the entire graph. 
None realised
Allows for the user to make more decisions about how the graph is affected when the split nodes plugin is run. 
Allows for users to choose whether they want to keep the changes they have made to nodes (colours and icons) when running the plugin.
None …
> Split Nodes Reset Attributes

- CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java
- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/resources/Style-AttributeEditor-Dark.css
- CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/resources/data-access-view.css
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportPane.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportTopComponent.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/resources/delimited-import.css
- CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReporterPane.java
Modified menu display settings for several views to give a consistant feel as well as shading any menu options to make the menu identifyable.
nil
Requested ticket highlighted that in some cases this top menu wasnt easily identifed as cselectable.
Ensure menu is selectable - and identifiable by the user. Note - the issue in this case is that the top bar is a menubar, which normally doesn't have shading for each menu option, this however is having other buttons overlaid so it requires a slightly different look and feel.
None identified
Go through all views and ensure any with menus have the same look and feel - in particualr any menu (ie Options menu for Data
Access View) is shaded differently to identify it as a button.
#866
> Modified menu display to ensure it is visible.

- CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramClearFilterPlugin.java
- CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramFilterOnSelectionPlugin.java
Modified Historgram filter setup to include EDGE and LINK as potential element types in line with GUI.
This is done to ensure code is able to successfully filter by element type  rather than retuning null and triggering exceptions.
Nil - this is a bug fix due to missing element types
Bug fix
Can now filter by Edge/Link Grapg Elements rather than seeing an exception
none known
Repeated steps shown in issue description. 
Performed filtered-by and clear opeorations for all graph element types.
#952
> Added EDGE and LINK element types to saupport filterinf by them.

- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelinePanel.java
- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelineTopComponent.java
Dragging the timeline view to resize the view no longer has the content of the view disappear when making the view smaller. By removing the minimum size of the content of the view, it stops the content from scrolling above the currently visible part of the view. 
Also added back a UI change so that the overview panel is able to be seen at the bottom of the pane when the timeline view is opened, instead of having to open the bottom part of the split pane to view it.
None realised
Stops the content of the view from scrolling off of the page. 
Resized the timeline view from the size of the window to as small as possible. The content no longer scrolls off of the view.
#910
> Timeline view is not always visible on resizing

- CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/GlyphRectangleBuffer.java
Hopefully this will stop a bug causing labels to be rendered incorrectly.
May not actually fix the issue as I can-not reliably test it as it is an infrequent multi-threading issue for an individual that common enough that a group using constellation frequently will notice it.
#962
> :bug: Potential fix to bug causing glyphs to replace others.

- CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java
Incorrect initial display of analytic aggregators was due to the 
categoryListPane.expanded value being initially set to true when it 
actually starts hidden, with the questionListPane expanded. Added a line
after initialisation to set categoryListPane.expanded to false.
Analytic views aggregators panel now initialises with the correct choices.
NA
#926
> :bug: Fix incorrect initial population of analytic aggregators.

- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelinePanel.java
- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelineTopComponent.java
Update to the timeline view to stop the summary pane of the view from resetting to the default size when a selection is made on the graph. The summary pane currently resets to 20% of the view size every time a selection is made on the graph or a change is made to the view. The change stops the summary pane from changing every time.
None realised 
Stops the size of the pane from resetting with every change made to the graph, improvement in usability. 
#910
> Timeline View summary pane resizing 

- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/clustering/TreeElement.java
- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/clustering/TreeLeaf.java
- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/clustering/TreeNode.java
> :racecar: Converted displayPos's to int

- CoreFindView/src/au/gov/asd/tac/constellation/views/find/gui/FindCriteriaPanel.java
Previously an error could occur when switching between graphs because
a FindRules attribute and type would be modified without its attributes
being updated to reflect the new type.
The line added causes the attributes value to be corrected prior to
accessing the attributes in the method that the error occurs in.
Stops the occurrence  of an error when switching graphs with the find view open.
I was unable to reproduce the slowness described in the ticket so this may actually address a different issue. However this error occurs when performing the steps described in the reproducer and I have seen errors remain hidden and cause application slowdown before.
#852
> :bug: Stop error triggered when switching graphs with find open

- CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/io/GraphJsonReader.java
- CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/save/AutosaveUtilities.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpener.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
Added an additional level of redundacy to star file loads, such that backup files (.bak) are created on save, prior to saving of new file verison. These backup files capture the star file before updates, (because these files were able to be loaded). Additionally, no longer delete backup file when loading an autosave file .
Upon load, andattmept is made to open the selected star file, if this fails, a check is made to see if an associated backup is found and if sao, attempts are made to load this. 
I considered options to try and capture all ways a file could be corrupted, but there are too many to consider, hence is is considered easier to be more robust in loading.
Bug fix.
Add an extra level of redundancy to file loading.
There is one case still not covered, if an autosave file exists …
> Issue#19 corrup star file handling

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
Saving and opening a .star file returns an exception. A semicolon is incorrectly used as a separator.  
This is a core functionality.
Removes the exception
1. Create a graph
2. Save the graph. This will return an exception (Notice the graph actually saved)  
3. Open the graph. This will return an exception
PR #981
> bugfix-Invalid separator in the file path

- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/ConstellationIcon.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/IconData.java
* The Constellation icon (and others) were not being cached properly so File -> Open on a folder containing star graphs would waste CPU time building the icon again for each filename.
* Fixed a memory leak where built icons was cached but never retrieved.
* In the cache, the `IconData` is no longer stored which has greatly reduced the memory footprint.
Opening a folder containing 10,000 star files :smile:
The following profiles Constellation from launch so it includes calls to create icons throughout the application. This includes the 4 icons in the bottom right corner (nodes, transactions, edges, links) etc. You will notice that `IconData.createData()` was called 35k times and is now just 15 times!
Performance of `master` taking around 5.5 seconds:
Performance of this branch taking under …
> Improve the performance of File -> Open

- CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
- CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramTopComponent.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Added a total bin count to the top of the Histogram view. 
Also set the minimum width of the Histogram view so that all elements are always able to be viewed.
Allows for the user to easily tell how many bins are currently in the Histogram.
#996
> Added bin count to Histogram

- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/QualityControlRule.java
The null pointer was caused by the hashcode for rules not being unique enough. Since the hashcode was only unique to the result set, any rule that flagged the same set of results would have the same hashcode. This has now been updated by adding the hashcode of the class itself rather than that of the results.
There are possibly better options for the hashcode but coming up with something more unique for each rule was difficult in this case
Bug fix in core
less bugs
possibly discover more bugs previously hidden
#1047
> fixed npe by updating qc rule hashcode to be more unique

- CoreGraphNode/test/unit/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginInteractionNGTest.java
A unit test was breaking locally that appears to be caused by an annotation. I think the annotation was added to allow it to pass in CI so we'll see how it behaves. 
In the end, removing a nice-to-have check from the failing unit tests (which was needing another thread to finish doing its thing before the assert was made) was enough to ensure the tests pass both locally and in CI
Allows unit test to pass
> fixed unit test breaking locally

- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java
Fixed a bug where the quality control view sometimes wouldn't update when you loaded a graph.
The issue ended up pointing to a change made to not update the quality control state when the camera was modified (e.g. camera zoom). What it resulted in though was that when you loaded or switched to a graph where the camera was different to what was currently set, the quality control state wouldn't update (even if there were other changes besides the camera).
Since the global mod counter resets to -1 every time you load or switch graphs, extending the camera mod check to include a check for the global mod count being -1 resolves the issue.
Quality control view now updates as expected when you load a graph or switch graphs.
Nil
#1054
> QC View Graph load bug fix

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
Fixed a bug where the quality category button in the DAV didn't have the correct priorities before QCV was open.
Correct categories displayed in DAV quality category button from the beginning
Takes a bit longer to open the DAV since it is now also updating the priorities but I think it is necessary in order to ensure the quality category is correct from the get go
#1049
> Quality Category button bug fix

- CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationViewTopComponent.java
Fixed the issue where Conversation View sometimes locks up when you open it. The source of the problem was an unnecessary call of `Platform.runLater` in the constructor.
Fixes bug in Core
Conversation view should hopefully not lock up anymore
Nil
Ran the reproducer as described in #978, also did some general playing around in the Conversation view to ensure nothing else broke in the process.
#978
> Conversation view lock up fix

- CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java
- CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/shortcut/LayersViewShortcuts.java
A few noted null pointers to finish off #1002 
Returning a boolean as false instead of null made sense.
Tested by having no graph open.
Use the hotkeys ctrl + alt + L
ctrl + alt +1
The error should occur at that point.
With the fix, there is no null pointer and no drawbacks because nothing should  be occurring without a graph or the Layers View opened.
> 🐛 Layers view null pointer fix

- CHANGELOG.md
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlEvent.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/QualityControlRule.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButton.java
- CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPaneNGTest.java
- CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/event/QualityControlEventNGTest.java
- CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/QualityControlRuleNGTest.java
- CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButtonNGTest.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Updated the names of most of the Quality Control Categories and some of the colours to be more visible and less confusing. 
The category names have been changed from Default, Info, Warning, Severe and Fatal, which could be confusing, to Minor, Medium, Major, Severe and Critical. A category called OK has been added for when no Quality Control rules have been flagged. 
None realised.
Updates the Quality Control categories to be less confusing for users by providing more meaningful category names. The colours are now also more meaningful by being colours that are more representative of the category names (e.g. OK is Green, Minor is Blue, Medium is Yellow, Major is Orange, Severe is Red and Critical is Dark Red).
Makes the Quality Control view less confusing for users. 
None realised.
Tested …
> Update Quality Control Category Names and Colours

- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/GlobalParametersPaneNGTest.java
These tests will only run when a display is present. If the build is headless, a skipping exception will be thrown which will cause the class to be skipped.
Improves test coverage.
Opens a super annoying frame when the tests run.
> `GlobalParametersPane` Tests

- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/LeadNodeSelectionDialogNGTest.java
Added unit tests for `LeadNodeSelectionDialog`. Due to JavaFx in the superclass I have avoided the minimal functionality in the constructor and focused on the two methods in this concrete class.
Creating an actual instance of this class means the calling of the superclass constructor which initialises all this JavaFX code causing headaches. Shooting for the testing of the unit level logic in the code. Not the functional UI so avoided.
Unit tests are awesome and should be everywhere.
Improves code coverage.
The constructor code is currently not tested.
> `LeadNodeSelectionDialog` Tests

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/PluginFinder.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/PluginFinderNGTest.java
Refactored the `PluginFinderClass` so that the event listeners were in actual inner classes and not lambdas so that they are accessible from the tests.
`PluginFinder` has a global property called `result` that it is being set by the event listeners. This is then used when the `find` method is called. It's very hard to set this all up and validate each case has set the `result` property correctly. I have added some TODO comments to hopefully figure this out in a future ticket.
Improve code coverage.
> `PluginFinder` Tests

- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesPluginNGTest.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/TestMergeType.java
Unit tests for `MergeNodesPlugin` class. Added a test concrete implementation of `MergeNodeType`.  This gets picked up in the scan by the NB `Lookup`. As it is only in the test packages it will not be included in the final distribution and so is only available in the tests.
Tried mocking the static call to `Lookup` but it proved difficult when the test was run with the other test classes. Something else must call the `MergeNodesPlugin` class before I set up the mocks and pre-populate the `static final` global variables essentially preventing the mocking from working.
Improves code coverage.
> `MergeNodesPlugin` Unit Tests

- .github/workflows/build-and-scan.yml
- .githubutilities/run-tests.sh
- CoreDependencies/nbproject/project.xml
- CoreDependencies/src/ivy.xml
- CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/ShowInTableViewContextMenuProviderNGTest.java
- CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilitiesNGTest.java
- docker/netbeans-runner/Dockerfile
Added TestFX and Monocle to the deps. This should hopefully allow for a headless build to run over JavaFX code.  Added required system props to the run test script so that the build runs in headless mode.
The PR contains one example of how to write the tests as a proof of concept.
This will mean that all the tests we have written that involve JavaFX code can now be run on the CI and included in coverage stats.
All tests run as a part of the CI build.
The Monocle dep is based on the JDK version. This could cause some issues when we look at upgrading to the next LTS. No one seems to have touched the GitHub repo for a while but I am not sure what is involved in making a new release. It is part of the TestFX package so hopefully it will be kept up to date as needed.
> Headless Build

- CoreTesting/src/au/gov/asd/tac/constellation/testing/CoreTestingPluginRegistry.java
- CoreTesting/src/au/gov/asd/tac/constellation/testing/FiveSecondWriteLockAction.java
The Five second write lock action was calling the five second read lock plugin instead of its namesake. Have fixed this.
Fix bug in core
Fix bug in core
> Five sec write lock action fix

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedSourcePane.java
There was an already existing scroll bar but it was present at the bottom of the enlarged file name list. I added a change that shrunk the original size of the file name list and made the scroll bar present as soon as a file name was large enough to show it.
Increases usability, allowing users to see the full file path
Increases usability, allowing users to see the full file path
I ensured clicking on a valid file path would still have the same effect on the rest of the view.
#1145
> Added horizontal scroll bar to imported files

- CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewController.java
- CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/clustering/ClusteringManager.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
I would like this and the related changes to go into v2.4.0
:bug: Fixed a bug with a concurrent mod issue
:art: Removed the experimental tag for Notes View
:art: Changed the UpdateDimOrHidePlugin to a "LOW LEVEL" tag
:art: Fixed a syntax error in what's new
Every graph action triggers a plugin report which causes the notes view to read and write from the state. This is not efficient and needs to be reworked so that it can be as efficient as the plugin reporter or as close to as possible.
This resolves a concurrent modification issue
My concern was around more memory use but I have been able to confirm that this does not increase the memory use. The spike in memory has to do with the notes being rendered which are JavaFX objects.
I did a lot of subsequent actions like continuously hopping …
> Resolve Concurrent Mod Error #1342 and Notes View fixes

- CHANGELOG.md
- CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTileRenderer.java
- CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationPointMarker.java
- CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/providers/DefaultMapProvider.java
- CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/ScriptingViewPane.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/file/ConstellationInstalledFileLocator.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/FileIconData.java
The `ConstellationInstalledFileLocator` class in `CoreUtilities` includes a `locate()` method intended to find files in NetBeans modules. One of the method parameters is `boolean localized`, which was intended to narrow the search to a localized and branded lookup. But the method never uses this parameter, it's hard coded to `false`.
None.
Minor update.
Increased clarity by removing unused code.
None.
- Used NetBeans to check for usages of the `locate()` method in the entire Core, and addressed those usages.
- Used NetBeans to check that `ConstellationInstalledFileLocator` has no occurrences of polymorphism (eg inheritance) and method overrides.
- Ran the unit test suite as problems with changing method signatures manifest as compile time errors.
- Ran Constellation, clicked around the …
> :fire: Remove unused "localized" parameter from locate method signature

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RunPane.java
- Changed the order that the 3 columns appear on the file importer
As per the issue for it #1308 , it improves readability by showing a more appropriate order of how elements actually appear in the graph.
It looks nicer.
long term users might get confused initially. 
- I ensured that the + button associated with transactions was still associated with it.
- I did not change any functional code, only the order in which they appear.
#1308
> Move transactions to middle

- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/file/ConstellationInstalledFileLocatorNGTest.java
Add unit tests for the ConstellationInstalledFileLocator class.
Ran the tests.
#413
> :white_check_mark: Add tests for ConstellationInstalledFileLocator

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/InteractiveGraphPluginRegistry.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/docs/add-and-selection-modes.html
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/framework/VisualAnnotator.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/FreeformSelectionPlugin.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/EventState.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformModel.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformRenderable.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Add in a way for a user to be able to run a freeform selection in the main graph view (similar to the box select)
The alternate design was modelled on graphics tools
It's adding to the functionality of the program and not having to do multiple little box selects at one time
The user will be able to do freeform selections to selectively pick out bits and pieces of the graph 
Potential for some duplicated code requiring a refactor.  No speed or memory increase was noticed in the testing 
Ran through multiple selections and box selections over multiple graphs with no loss of speed or noticeable slowdown after some time doing this.  No exceptions noted or odd behaviour encountered.
#1268
> Add in the ability to do freeform selection via ALT+left mouse drawing

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RunPane.java
- Added a scroll bar to the content within the run tabs. 
- Changed attribute scroll bar to be as needed instead of always.
- Changed height of sample view to be smaller to remove large blank space
This change was needed for users with small screens/monitors that would experience the attribute collapsible pane disappearing once collapsed. The new change adds a scroll bar that stops the collapsible pane from completely disappearing after being collapsed. The user will be able to see the bar after being collapsed by scrolling to the bottom of the Import From File screen.
Allows users with small monitors to use the import file feature with more ease.
Small monitor uses can also now properly see the attributes when the tab is expanded.
UX benefits.
The sample height section is slightly …
> Attribute bar disappearing on collapse

- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Matrix33d.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Matrix33dNGTest.java
Add unit tests for the Matrix33d class.
Ran the tests.
#413
> :white_check_mark: Add tests for Matrix33d

- CHANGELOG.md
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Matrix44d.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Matrix44dNGTest.java
`setRotationMatrix` is intended to set the top-left nine values of the 4x4 matrix to the values of the input 3x3 matrix. Incorrect values were used in the `System.arraycopy` calls to retrieve values from the source 3x3 matrix. This is especially obvious with the 3rd copy, which attempts to copy 4 values from a 9-element array, starting at the 8th element.
While I was here I also improved unit test coverage of the class.
None - simple bugfix.
Reliance on this incorrect method could result in strange bugs when users move their viewpoint around Constellation views.
Improved correctness in a core utility method.
Any plugins relying on this behaviour will no longer work as expected. Updated the change log to account for this.
Created unit tests and ensured they run correctly.
> :bug: Fix setRotationMatrix to set the right values for a 3x3 matrix, and increase test coverage

- .github/workflows/build-and-scan.yml
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/io/ParameterIOUtilities.java
- CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilities.java
- CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilitiesNGTest.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIODialog.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIODialogNGTest.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIONGTest.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/genericjsonio/resources/my-preferences.json
- docker/netbeans-runner/Dockerfile
Created unit tests for the JSON IO package in the utilities module. Refactored the code to make use of `Optional` where conditional parameters were being returned and provided. Improved comments and simplified some of the code where possible.
Overloaded the load preferences method to allow callers to provide an expected class. This will cause the code to map the loaded JSON into that object rather than returning a JSON Tree. The old methods are still there and this is backwards compatible. I have marked the JSON Tree methods as deprecated. I have also modified the save preferences to take a `Object` rather than a JSON Tree. Now either a JSON Tree or a preference object can be passed and it will be serialized.
The aim of this is a pre-cursor to try and clean up the IO classes that then use …
> JSON IO Unit Testing

- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorDialog.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/AttributeNode.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/DefaultAttributeValueDialog.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/NewAttributeDialog.java
- CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/NamedSelectionManager.java
- CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/NamedSelectionTopComponent.java
- CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/PluginInteraction.java
- CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersSwingDialog.java
Changed all the 'Ok' buttons to uppercase so that we have consistent naming across the application
I would've preferred to switch the upper case 'OK's to camel case but since this what is used by the javafx button (which I can't fix in this application), I had to go with the other option
Consistency across teh application is a good thing
Consistency
OK is now always shouting at you
#1348
> Switched 'Ok' buttons to 'OK' for consistency across application

- CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java
Updated the conversation search to change the found text to the empty string when there is no search text. 
Showing a search count doesn't make much sense if no search has been made
Better UX
My solution assumes users aren't searching for a string of whitespace characters. Maybe someone will be mad but I'm assuming 99% of users won't be
Conducted various permutations of opening a graph before and after Conversation view was open with and without search text already present. Then conducted some searches on a graph that had content to verify the found text appeared in its various forms when I start typing and disappeared once I cleared the search.
#1168
> Removed Found Count Text When No Search Is Made

- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/datastructure/ImmutableObjectCache.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/datastructure/ImmutableObjectCacheNGTest.java
`ImmutableObjectCache` has two paths of logic. One of these paths inspects objects added to the cache and keeps statistics on how the cache reacts to each object, which can be retrieved using the `toString` method. This is called `verbose` mode. The other path doesn't keep statistics and is consequently much faster.
`verbose` mode is not enabled by default.
Previously the only way to enable `verbose` mode was to make a code change to `ImmutableObjectCache` - if a developer changed the `VERBOSE` variable to `true` the cache would run in `verbose` mode. This made `verbose` mode hard to test. The improvement made was to add a setter allowing programmatic setting of the `verbose` flag. This retains the functionality of the original code as the developer can change the default of `verbose` …
> :art: Allow programmatic setting of verbose mode for ImmutableObjectCache

- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/Bundle.properties
- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/KTrussControllerTopComponent.form
- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/KTrussControllerTopComponent.java
I have done a few small things that should hopefully help.
- Moved updating the buttons into functions so changing button properties can be easily added or modified later on.
- Made the cluster button and the interactive button have bold text. This should hopefully direct the user a bit more to press then 1st then 2nd respectively.
- Changed the text of the interactive button to state "Toggle Interactive: Enabled" or "Toggle Interactive: Disabled" 
- this just read a bit cleaner to me. It states what the button does and states the current mode its in.
- This was changed from "Interactive - disabled" and "Interactive - enabled"
I was unable to automate the process of pressing cluster automatically enabling the interactive mode due to the inflexible design of the view. This should hopefully …
> Improve user flow for K-truss view

- CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/Hashmod.java
- CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/HashmodAction.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Allow transaction to inherit attributes from a node.  Also significantly speeds up ingest of data from a CSV file
Nil considered
Already in core
Ingesting csv files is a lot quicker with the hashmod ingester now as it doesn't have to traverse the entire key chain each time.
Allows transactions to have an attribute from a vertex added to it.
Nil known.
Integration testing was done for new and larger csv files (one with 48K rows - when this same one took minutes previously, it took seconds to ingest with the changes)
#1363
> Hashmod - Allow transactions to have attributes from the CSV

- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/https/HttpsConnectionNGTest.java
Add unit tests for the HttpsConnection class.
Ran the tests.
#413
> :white_check_mark: Add tests for HttpsConnection

- CHANGELOG.md
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/https/HttpsConnection.java
`HttpsConnection` had two areas of unused code. The first was the `enableSSL` member variable. The second was the `keepAlive` method which was intended to enable `HTTP keep-alive`. As shown in the [Mics HTTP URL stream protocol handler VM properties](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/doc-files/net-properties.html#MiscHTTP) `keep-alive` is controlled by the `http.keepalive` VM property with defaults to `true`.
None.
It is a class used by many things, and already in the Core.
Reducing complexity by removing unnecessary code.
None.
Confirmed that the `keepAlive` method in `HttpsConnection` does nothing by creating a test harness that executes the method then inspects the set of `requestProperties`. The method …
> :fire: Remove unused HttpsConnection code

- CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/save/AutosaveUtilities.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpener.java
Changed log messages provided during loading of files to give a more detailed picture of what is happening when user opts to use an autosave file. This is aimed at demostrating via logs how original file (and any .bak files) are replace by autosave restore process.
nil
Reduce user confusion if viewing logs. Actual load process doesnt change.
Reduce user confusion if viewing logs. Actual load process doesnt change.
None known.
Replicate steps documnted in https://github.com/constellation-app/constellation/issues/1091 - Steps to reproduce and view generate dlog messages.
> updated logging surrounding loading of autosave files

- CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/results/AnalyticResult.java
After the recent Analytic View refactor the default sort was disabled and the results were displayed in random order. This fix brings back the default descending order of the results. 
Core functionality
The descending order is more intuitive to analyze the data. The random ordering was misleading   
Possible performance issues tested, but there is no change in performance.  
1. Open the Analytic View and open a graph.
2. Select any Analytic Question e.g. 'Connects The Network Best' -> 'Betweenness Centrality Alalytic' and Run the plugin.
3. Notice the results are sorted in descending order.
> Fix to Analytic View sort

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ResetViewContextMenu.java
- CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ResetViewContextMenuNGTest.java
- CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/SelectionContextMenu.java
- CoreVisualGraph/test/unit/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/SelectionContextMenuNGTest.java
Adds in the Selection menu (with icons) on right clicking the Graph menu and adds in the Reset menu (with icons) as well
Nil.  The ordering of the selection and reset view sub menus are the same as the default menu options
Already there
Enhances UX for the user
Nil
Ran across multiple graphs with no issues or bugs noticed.
#1261 I see this as addressing the actual problem that that issue was looking at.
> Add icons to right click popup context menu

- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/NestedKTrussDisplayPanel.java
Pane was resizing by diving by zero because of the `totalNeededHeight` variable. Adding a check to avoid dividing by zero seemed to prevent the exception. I have spend the last few hours trying to correct the actual problem of it being zero and checking if the current solution causes any detrimental behaviour but have not found anything.
I actually could not seem to create a graph that had nested k-trusses for testing. The pane will resize just as it did in previous versions on standard working graphs so I suspect this PR is fine.
Tried to find alternate solution which involved avoiding the  case of zero being the variable value but came up short.
Avoids …
> Prevent exception of divide by zero in k-truss

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/geospatial/AbstractGeoExportPlugin.java
- CoreMapView/nbproject/project.xml
- CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTopComponent.java
This change adds validation to the dialogs involved with exporting and zooming.
A graph has to exist before the export menu dialog will pop up. If the export menu button is pressed without a graph, a dialog is presented to notify the user that a graph must be present to export from.
similarly with the zoom to ... menu, there must be a graph present to zoom to a location, so there is relevant error handling around that.
The main issue was to do with there not being a graph present or the inputs being blank.
I tried to disable the export menu when a graph was not present. this did not work as the jdropdownbox did not disable for some reason, and it didnt …
> Map view various fixes

- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/SwaggerServlet.java
Following endpoints which were not showing the response message because of missing Response body has been fixed. They now display the message in html format in the response body.
Get_graph_image
Get_icon
The best option is to display the message in JSON format, similar to other end points.
Better UX
User can now see details of what went wrong rather than just an error code.
Open swagger and run the above endpoints with incorrect constellation secret, and correct constellation secret with incorrect icon name.
The response body should appear with a clear error message.
https://github.com/constellation-app/constellation/issues/656
> RESTApi Swagger showing the response message when the requests with image MIME type fail

- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/compare/CompareGraphAction.java
This feature adds a notification to the user when only one graph is present and an attempt is made to compare graphs.
This below image shows the notification that pops up when the compare graph is clicked and one graph exists only. This will not happen if two graphs are present. This will also not be possible to open two graphs, then compare graph, and close one graph. The compare graph is modal and therefore this shouldn't happen.
I looked to add custom logic to the context handler, but this is not accessible within our code it seems. 
This seemed like a good way to go about it because the user should have no need to compare with one graph open. This …
> Compare graph warning when only one graph is opened

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesPlugin.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeTransactionsPlugin.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/TestMergeType.java
A couple of plugins had a default value added to one of the parameters. The problem was that changing the value in these parameter was meant to trigger a controller but since the default value was set before the controller was defined, the expected actions didn't happen (e.g. other parameters in the plugin being enabled or disabled). This small change just moves the setting of those default parameter values to after the controller definition so that the controller code gets triggered.
Ensures plugins in Core follow expected behaviour
parameters don't have to be re-selected to trigger intended behaviour
Nil
> fixed issue with some default parameter values not triggering controllers

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/docs/import-from-file.md
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Users can specify the input time zone used in the Datetime fields in imported data files. 
Right-click on the `Datetime` transaction attribute and navigate to `Formatter` -> `Datetime` then select the `Time Zone`. 
It'll be empty by default which will display the formatted columns as if they are in GMT, similar to the previous behavior.
When a value is selected:
n/a
Better ux
This is specially useful when Excel files are imported where the Excel datetime number doesn't contain time zone information.
1. Open Constellation and the File Importer
2. Load a file in to the importer containing date time columns of different formats
3. Right-click on the …
> Add option to specify input timezone for Datetime formatters in Importers

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/docs/import-from-file.md
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
In the File or Database Importer the date times can now be converted to a specified time zone before importing, to avoid that step being performed in the Attribute editor. `Display Time Zone` is available in the pop up window when right-clicking the DateTime attribute, and navigating to Formatter -> Datetime.
(Added the changes here on top of the branch in https://github.com/constellation-app/constellation/pull/1705 because they were required. Only the last commit relates here.)
1. Open Constellation and the File Importer
2. Load a file in to the importer containing date time columns of different formats
3. Right-click on the Datetime transaction …
> Add option to specify display time zone for Datetime formatters in Importers

- CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/RecentFiles.java
a concurrent mod was occasionally happening after a graph save. The source of the issue appears to be in `RecentFiles.getUniqueRecentFiles()` which doesn't have a lock around the static list it plays with. Have modified the code slightly to wrap the function around the history lock.
Considered creating a separate lock specifically for the function (since the concurrent mod wasn't occurring until after the history list had been used) but decided the the performance cost using the existing wouldn't be so bad that the existing one couldn't be used.
If performance truly does take a significant hit, this alternate approach could be implemented.
bug fix
bug …
> added lock around getUniqueRecentFiles to avoid concurrent mod

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ResetViewPlugin.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/RotateCameraPlugin.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomToSelectionPlugin.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomToVerticesPlugin.java
Modified the plugins which alter the camera position (zoom level) to check if the related graph is active before doing an animated camera zoom.
If the related graph is not the active one, the new camera position will be set directly in the related graph, skipping the animation process.
If you are working on multiple graphs and run a plugin on one of those graphs, and then switch to a different graph while waiting for the plugin to complete.
The current graph being viewed will not suddenly have it's zoom level changed when the first graph's plugin has completed.
> Only reset view/camera position on related graph.

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/screenshot/RecentGraphScreenshotUtilities.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/filechooser/FileChooser.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/filechooser/FileChooserNGTest.java
Added a null check so that the recent graph screenshot class does not try to take a screenshot if the graph has already been closed.
Fixed bug where graph did not close after clicking on the X on the graph title tab to close the graph and then saving the graph.
N/A
Bug fixes. 
Actually closes the graph after clicking on the X on the graph title tab and saving the graph, as it would expect to. 
None realised.
1. Open a graph and add a vertex.
2. Close the graph using the X on the graph title tab.
3. Choose Save, and save the graph somewhere.
4. Observe that the graph closes and no null pointers are thrown.
5. Reopen the graph to confirm that it was saved …
> Closing Graph on Save Bug & Screenshot Null Pointer 

- CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/RecentFiles.java
Updated the Recent Files preferences list so that temp files are not stored in this list. This list has a maximum of 10 file paths and temp files were being added to this list, meaning that less files would show up in the Open Recent Files menu option and in the Welcome Tab Recent files, as the temp files could not be found.
N/A
The recent files lists now accurately show the last 10 graphs that were worked on.
Allows users to view the last 10 graphs that were edited easily.
None realised.
1. Edit and save at least 10 graphs
2. Reopen Constellation and observe that 10 graphs show in Open Recent Files and the Welcome Tab recent files tiles
To create temp …
> Update Recent Files List

- CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/DeselectAllAction.java
- CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/SelectAllAction.java
The shortcuts for the Select All and Deselect All plugins will now only work when the graph tab has focus.
N/A
Prevent inadvertent selecting of all nodes when editing a text field in a different component.
Users can use Ctrl-A to select all text in a component without affecting the current selections on the graph.
Can no longer select all nodes when other panels/components have focus.
* Open a new graph and add some Nodes
* Press Ctrl-A to confirm all nodes are still being selected when appropriate
* Select a single node
* Open the Data Access View
* Type some text in a text area field such as the one in: Extract Words from Text -> Words to Extract
* …
> Fix Select All issue with graphs when different elements have focus.

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Updated a number of the default datetime formatters to be single digit d and H as this allows both single digit and double digits days and hours to parse (e.g. 1, 01, 12). Not all could be updated to accommodate this though so I only updated the ones I could. Also added a couple of new default formatters which don't contain seconds in them
Enhances work already done in Core
Greater flexibility in the default datetime formatters.
Nil
1) Created some csv files containing data with both single and double digit days and hours that matched the default formats
2) Tried applying the formatter to the datetime attribute and applying it to the relevant column in …
> updated datetime formatters in importers

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
Values that came through as scientfic notation couldn't have the datetime attribute applied as the code immediately tried to parse the number as a long (which causes an issue for decimals). By getting the double value and then extracting the long value, the parser can handle epoch times in both standard and scientific notation
Could've created a BigDecimal and got the long value out of that. It would be a more accurate long but for most use cases I think it may possibly incur more overhead than needed (as that solution works best if the number can't be represented as a long immediately).
Improves parsing functionality of importer
Can parse epoch …
> updated epoch parser to allow scientific notation to parse

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/ImportJDBCPlugin.java
Updated the import bubbles from the file and database imports so that the bubbles appear in time order rather than alphabetical order.
The underlying issue appears to be that netbeans sorts the bubbles alphabetical by header and then where the headers are the same, it goes in time order after that. That part I couldn't figure out how to change (I think it may be a netbeans thing) but I could get around it by making the import headers the same, that way the bubbles will show up in time order (as it can't order by header).
Worth noting as part of this that I made the header from file imports "File Import" and from database imports "Database Import" so this …
> updated file and database import bubbles to ensure time order

- CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationPreferenceKeys.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlStateUpdater.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/QualityControlRule.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButton.java
- CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPaneNGTest.java
- CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlStateUpdaterNGTest.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Updated the quality control view category priority dialog to include an option to enable or disable a rule. Similar to the category priority change, this will be persistent between sessions. By default, all rules are enabled.
While I was at it, I also fixed an issue with the QC widget in Data access view where any changes to rules were only applied once the quality control view was opened (e.g. if DAV was opened and QCV was not, if you previously changed the Unknown rule category from minor to major, and that was the only rule flagged by a particular node, the widget would read as minor until you opened QCV and which point it would change to major). …
> Enable/Disable QC Rules

- CoreFindView/src/au/gov/asd/tac/constellation/views/find2/state/FindViewStateIoProvider.java
This run time error was caused by the new find view attempting to pre-fill the selected attributes drop down with all the attributes that were previously used in a search even if those attributes no longer exist on the graph. 
The error is reproducible by opening the attached graph below or by doing the following on release version 2.9:
1. Creating a new graph and adding a new custom node attribute.
2. Use the new find view to search with this custom attribute selected in selected attributes.
3. Close the new find view and delete the custom attribute
4. Close and reopen the graph (this should throw the index out of bounds) …
> Find View Run Time Error 

- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/IconEditorFactory.java
- CoreAttributeEditorView/test/unit/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/IconEditorFactoryNGTest.java
Allow .GIF and .JPG files to be imported as icons. This mean code in the attribute editor that allows icons to be imported is modified to not just lock down to PNGs. 
Existing cvode allows these files to be stored as custom icons in star files and places copies of impoorted files into icon folder.
nil
Increase the types of images that can be icons
As above
None known
Repeat steps documented in this tickets problem description, but confirm that GIF of JPG files can nw be added, either individually, or by directory.
#1768
> Allow GIF and JPG images to be added  as icons

- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorTopComponent.java
- CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReportTimeUpdater.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/restapi/RestServiceUtilities.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/NewGraph.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/OpenGraph.java
- [ X] Reviewed the [checklist](CHECKLIST.md)
The thread.sleep() in the attribute editor has been removed since a similar effect can be reached without it. The RestServiceUtilities class has had a thread.sleep replaced with a CompletableFuture.
After some investigation:
Data access view - the thread.sleep() here seems to be an intentional thing where the user can choose to sleep the thread for a certain period of time.
Graph Node - It is unclear how to make this any better. The sleep is in the DefaultPluginInteraction class
Core Interactive Graph - The sleep is in the Animation class. The sleep is used pause the thread after each frame of the animation …
> Removed some thread.sleeps from WebServer and Attribute Editor package

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpener.java
- [ X] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
Added code to handle case where there is a valid graph backup, but also a corrupt grpah and autosave file. Previously in this case, if the user elected to open autosave, the graph is copied over top of the backup - even if its corrupt (which isn't known until opening it) - so if the autosave is also corrupt, then the only file that wasnt (the backup) was deleted and the two corrupt files remained.
Now in this case, if a user is opening an autosave, and there is a backup, that backup is temporarily backed up and only used if the autosave and main file are corrupt.
Could have …
> Update VisualGraphOpener.java to support additional recovery options

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GMLImportProcessor.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GraphMLImportProcessor.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/PajekImportProcessor.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectTopNPlugin.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GMLImportProcessorNGTest.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GraphMLImportProcessorNGTest.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/PajekImportProcessorNGTest.java
- CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportEntry.java
- CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportSessionData.java
- CoreErrorReportView/test/unit/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportFullSuiteNGTest.java
- CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/ConstellationErrorManager.java
- CoreFunctionality/test/unit/src/au/gov/asd/tac/constellation/functionality/ConstellationErrorManagerNGTest.java
- CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironment.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/TemplateUtilities.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportController.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedIO.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/ScriptAttributeTranslator.java
- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/AutosaveStartup.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/NotifyDisplayer.java
Addresses issues raised in #1641 
When a plugin shows a notification to the user, it should no longer show an exception popup as well.
This is achieved by setting a block-popups flag on the Error Report that is generated when the exception is logged.
Note that this Pull Request only covers plugins that are part of the core "constellation" repo.
There will be a separate Pull Request for the plugins that are defined in the "constellation-adaptors" repo.
None
It should be a consistent standard across the product to have notification popups without an accompanying exception dialog.
Improved user experience.
No need to show an exception dialog as well as a …
> Prevent exception popup windows from being displayed when a notification was already shown.

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GMLImportProcessor.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GraphMLImportProcessor.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/PajekImportProcessor.java
- CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportDialog.java
- CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportSessionData.java
Updated the "File not Found" notification when running a plugin from the Data Access View without specifying a filename. It should only pop up a single message informing the user that they haven't specified which file to use.
Also tightened the matching criteria used in the Error Report view, as there were similar exceptions from the data access plugins being grouped together, when they shouldn't be.
N/A
Improved user experience
Improved user experience
N/A
In the Data Access View, select (click the checkbox for) Import from Graph file.
Click the Go button
Confirm that you see a single popup window saying "File not specified" and no other popup windows. …
> Improved notification for File Not Found error when no file specified.

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessViewTopComponent.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataSourceTitledPane.java
Opening and closing graphs should not auto-select plugins in the Data Access View.
N/A
To have the application perform in an expected manner.
To prevent unexpected plugins being selected without any user interaction.
None
Expand all Data Access View plugins.
Ensure they are all unselected.
Open a new graph.
Confirm that none of the plugins have been auto-selected.
#1829
> Prevent auto-selecting plugins on the Data Access View.

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPlugin.java
- CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironment.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/threadpool/ConstellationGlobalThreadPool.java
- CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/threadpool/ConstellationGlobalThreadPoolNGTest.java
Reverted back to having `WorkflowQueryPlugin` create its own thread pool of size `maxConcurrentPlugins`.
While I was at it, I realised that with the default plugin environment thread pool, we had 2 cached thread pools which isn't really necessary in this case as neither pool was being shutdown or terminated and a cached thread pool can have up to `Integer.MAX_VALUE` threads (which we're unlikely to ever hit unless something has gone very wrong). So I've removed the pool specifically for the `DefaultPluginEnvironment` and moved that to using the other cached thread pool.
I considered simply removing the shutdown call in the `WorkflowQueryPlugin` but the …
> Workflow plugins thread pool

- CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/Generator.java
There is an issue on Linux where trying to access help pages throws an IndexOutOfBound Exception.
This is caused by a hard coded path separator being used when getting the resource path.
It should be using the system dependent File.separator
N/A
Core functionality
Core functionality
N/A
Install on Linux and access the help pages.
Click on any question mark icon in constellation to retrieve the related help page.
> Use the system dependent File separator in the resource path.

- CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
- CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
**_Fix for issue #1848 found during testing of release candidate v2.10.0-rc1_**
Notes that are being edit do not get reset when an autosave occurs. If a note is in edit mode and the user switches graphs, that note will remain in edit mode with any changes made when the user returns.
Makes editing notes safe as the users can the sure there changes won't randomly be lost if a background plugin finishes running.
Increases usability of the notes view.
Auto notes are not updated in real time.
Made changes to note in edit mode switched graphs and came back to see note still in edit mode with the changes I have made.
#1848
> Notes view autosave no longer removes changes on notes being edited

- CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/RecentFiles.java
- CoreGraphFile/test/unit/src/au/gov/asd/tac/constellation/graph/file/open/RecentFilesNGTest.java
Screenshots for recent graphs (if available) should now be consistently displayed on the welcome page.
N/A
Improved user experience.
Reliable quick access to recently used graphs.
N/A
Confirm that recently used graphs are consistently showing up in the welcome page on startup.
In the event that a timing issue does occur, a warning message is logged, and the affected process will wait up to 5 minutes for the data to be initialised, afterwhich the processing resumes as normal.
If the data is still not initialised after 5 minutes, another warning is logged with an exception, which will be captured by the Error Report view, and the process will proceed with …
> Fixed issue with missing screenshots on the welcome page.

- CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
Fix the Notes View tags filter to update notes consistently upon user selection/deselection of tags
Due to the `Platform.runLater()` in the `updateSelectedTagsCombo` , the selected tag filters were not updating before the UI is updated in the `updateNotesUI()` . It ( Platform.runLater() ) doesn't seem to be required because no GUI is updated in that function, hence removing it fixed the issue.
Moving the entire updateNotesUI()  inside a Platform.runLater() but it'd degrade the performance
Open a graph and Notes View. Perform some activities on the graph such as select a node, delete it
Select Auto notes filter and see notes appear for those activities …
> Fix the Notes View tags filter

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessViewTopComponent.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java
- CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButton.java
Added code to QualityControlAutoVetter.java to remove graph change listner if no listeners remain to QualityControlAutoVetter.
Updated DataAccessViewTopComponent.java and DefaultQualityControlAutoButton.java to modify when listeners to QualityControlAutoVetter are added/removed to ensure closing the view removes all listeners.
QualityControlView already correctly removes listeners when closed.
nil
Improve performance by removing redundant calls to QualityControlView.graphChanged.
As above
Nil known
To test:
* in debugger, add following breakpoints to QualityControlAutoVetter.java:
1) line 147 in first line of graphChanged
2) line 270 in addListener where …
> Handle close of listeners to QC Auto Vetter to trigger removal of graph listneer if no listeners to auto vetter

- CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/utilities/BlazeUtilities.java
- CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/utilities/BlazeUtilitiesNGTest.java
When there is already 10 preset blaze colours and the user wants to add in a new preset, a dialog window will popup asking the user which preset they would like to replace with their new one.
Currently the last blaze colour preset would be replaced with the new one with no warning which isn't ideal since if that last preset colour is important it'll be lost without giving the user a choice.
Gives user more control over which preset they would like to replace.
Dialog windows are annoying to work with in JavaFX and making changes in the code can have unexpected effects.
Saved 10 blaze colours as presets. Then set 10 new presets by replacing the existing …
> Blaze colour replacement dialog.

- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/schema/type/SchemaTransactionTypeUtilities.java
- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/schema/type/SchemaVertexTypeUtilities.java
If a Vertex Type or Transaction Type is manually entered, and a Schema update is performed ("Complete with Schema"), it will now be checked if it extends from and existing Type in the Schema.
ie. For Analytic Graphs there is a Type called "Document", and if you create a new Vertex and set the Type to "Document.Letter" it will be identified as an extension of the Document Type and use that as its base when performing a Schema update, instead of the default behaviour where it will be based on the "Unknown" Type.
The image icon and background colour will be set according to the new base Type identified.
The full text that was entered as the Type will be …
> User defined Types will now be checked if they extend from an existing Schema Type.

- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorTopComponent.java
- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributePreferenceKey.java
- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeReader.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
Added checks of attributes being displayed in populateContentContainer and if "Show All" is NOT enabled and values are null then dont call createAttributeTitlePane and add title pane for the attributes.
Updated AttributeEditorTopComponent to have a hook for preference changes to allow update as Show All is toggled.
nil
Fixing bug in "Show All" plus user requested ability to hide large amounts of null content
Open a graph and Attribute Editor. Hide/Unhide some attributes and ensure they are hidden/shown on Attribute editor. Now enable "Show All" and repeat.
confirm that if no node selected all node attributes show as null and dont display if "Show All" …
> Added checks for null attributes and only add if "Show All" selected

- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/BooleanEditorFactory.java
- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/DecoratorsEditorFactory.java
- CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/DrawFlagsEditorFactory.java
Handle null values in selected Editors
Look at atribute types in the attribute editor and for each one, test the ability to edit "multiple entries", which passes null to the Editor.
For those that cannot handle null, explictly catch the case and deal with it.
Nil - bug fix
bug fix
avoid errors which prevent editing multiple entires of the given types
none known
1. Create a new graph.
2. Add multiple custom attributes covering each data type.
3. Add two nodes.
4. Select one of the nodes and for each custom attribute, modifiy the value in the Attribute Editor.
5. now select both nodes and confirm that the atrtribute editor shows "Multiple Values" for each …
> Handle null values in selected Editors

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/experimental/TestParametersPlugin.java
Remve hard coded default date in test parameters panel in DAV so that the current date is used instead
nil
make dates more accurate
make dates more accurate
consistent with developer settings in experimental
nil
1. Open a new graph
2. Select Experimental->Developer->Test Parameter Building and confirm date shown is current, close dialog
3. Open the Data Access View
4. Expand Developer->Test Parameters (Batched) and Developer->Test Parameters
5. Confirm that date shown in both expanded sections is current
nil
> Removed hard coded default date value and use current date

- CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java
- CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/state/AnalyticDeactivateStateChangesPlugin.java
Ensures that any changes made by the analytic view are always reset when the view is closed or a new analytic is run.
Bugfix
Open multiple graphs
Run an analytic on each and select some of the graph visualisations (color, hide and size)
Close the analytic view
Check that the changes made by those graph visualisations have been reverted on all graphs.
> Analytic View Reset Bug

- CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/similarity/LevenshteinDistancePlugin.java
- CoreAlgorithmPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/similarity/LevenshteinDistancePluginNGTest.java
As outlined in #1894, when doing a levenshtein match on attributes in the analytic view identical matches are removed, this was originally a design decision to find similar attributes, not identical attributes.  This use case has since changed and the maxDistance can be zero.  The proposed change simply removes the checks to remove exact matches from the results.
None considered.
This is a modification to current core code and gives a consistent experience for the user.
Consistence experience when using the levenshtein analytic, when using the maximum distance results are returned as expected.
None considered.
1. Open a new graph in Constellation
2. Add …
> Levenshtein allow identical matches

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/api/DataAccessUserPreferences.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/io/DataAccessParametersIoProvider.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/io/DataAccessParametersIoProviderNGTest.java
We can now Save Templates in the Data Access View even when there are no values supplied yet in the Global Parameters.
This would previously either throw a null pointer exception, or not provide any feedback to the user that the save will not be performed.
N/A
Improved user experience, Improved functionality.
Properly handle null/empty Global Parameters when Saving Templates.
Don't throw unnecessary null pointer exceptions.
Open the Data Access View.
Clear the Query Name parameter in the Global Parameters section (we are testing the case for when Query Name is empty).
Click the Workflow Options button and select Save Templates
Confirm that it prompts for …
> Allow Saving Templates in the Data Access View when there are null Global Parameters.

- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/resources/constellation_client.py
- CoreWebServer/test/unit/src/au/gov/asd/tac/constellation/webserver/test_rest.py
- [X ] Reviewed the [checklist](CHECKLIST.md)
- [] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
The constellation_client wasn't decoding the output from the server from bytes to a string to then be used by Panda's read_json as outlined in #1816.  In the past this was allowed by Pandas even though it wasn't documented.  This was changed without depreciation notice sometime last year.  
Since Constellation opens the default Jupyter instance there can be many different versions of python and pandas accessing the web server using the constellation client.
The change simply checks the data returned from the Constellation web …
> Fixed pandas data type error #1816

- CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV6UpdateProvider.java
- CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV1UpdateProviderNGTest.java
- CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV2UpdateProviderNGTest.java
- CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV3UpdateProviderNGTest.java
- CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV4UpdateProviderNGTest.java
- CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV5UpdateProviderNGTest.java
- CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV6UpdateProviderNGTest.java
At the time the Visual Schema v6 updater was created, there were no issues with how it was constructed. Since then though, the v7 changes have been introduced which was related to modifying the same attributes. for transaction_labels though, this represented reverting its name back to what it was prior to v6. What this meant now was that graphs now opened with visual schema v5 or earlier were now having that attribute removed from their graph (as the new and old version of that attribute were the same). These changes account for that by removing the updates made to transaction_labels in the v6 updater.
Doing this won't cause any issues as any graphs that …
> modified schema updater to account for changes since it was created

- CHANGELOG.md
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GraphMLImportProcessor.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GraphMLImportProcessorNGTest.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/resources/processing.graphml
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/resources/processingEdges.graphml
As outlined in #1935, a NullPointerException would occur when importing a graphML file that didn't have an edge id field.  GraphML doesn't require an id for edges ([graphML Schema](http://graphml.graphdrawing.org/specification/xsd.html)) however this is a required field for constellation.
The proposed change attempts to fix this discrepancy and adds error reporting for nodes and edges that were invalid.  
1) As many graphML files wont include an id field for an edge as this is not a required field, I'm proposing a UUID be assigned as the edge Identifier in the absence of an edge id.
2) Warning messages have been added to notify the user of failed imports …
> Feature graphML processing error msgs

- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/svg/ExportToSVGPlugin.java
- CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/svg/SVGGraphBuilder.java
- CoreImportExportPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/importexport/svg/SVGGraphBuilderNGTest.java
The SVG Export plugin utilizes `GraphVisualAccess` which holds a lock on the graph during the plugin execution. This PR adds a check for the `SVGGraphBuilder` to allow it to release the lock from the `GraphVisualAccess` when the plugin is interrupted.
Alternate 1 - Refactor the `GraphVisualAccess` to accept a `GraphReadMethods` as in a constructor. This would relinquish responsibility from the `GraphVisualAccess` to release the graph but would extend the class beyond its intended use.
Alternate 2 - Refactor the Export to SVG plugin to use `VisualGraphUtilities` instead of `GraphVisualAccess`. These utilities accept `GraphReadMethods` as parameters …
> SVG Export Plugin locking graph when interrupted

- CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersSwingDialog.java
This PR enables the Graph Title input field on the ExportToSVGPlugin PluiginParametersSwingDialog to express recent values correctly.
N/A
It is a core feature.
Export a graph to SVG | File -> Export -> to SVG.
(Note the graph title value is blank as a graph title has not yet been set.)
Export a different graph to SVG | File -> Export -> to SVG.
(Note the previously exported graph title is in the recent values dropdown.)
#1930
> Add recent values to SVGExport  ValueInputFields

- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/resources/constellation_client.py
Similar to #1933 the constellation_client wasn't decoding the output from the server from bytes to a string to then be used by Panda's read_json as outlined in https://github.com/constellation-app/constellation/issues/1816.  This error occured when calling get_graph_attributes from the client.
Since Constellation opens the default Jupyter instance there can be many different versions of python and pandas accessing the web server using the constellation client.
The change simply checks the data returned from the Constellation web server, if it is a byte type it'll decode it to utf8, as suggested in …
> fixed client get_graph_attributes data issue

- CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/AnalyticSchemaFactory.java
It appears there was a logic issue in the way the analytic schema resolved the foreground icon for a vertex type. The current logic first checked if there was an icon that matched the type name and if so, set the icon to that type if it wasn't already set. After that, it then checked the foreground icon defined by the schema type and set it if it wasn't already set.
This logic appears backwards as it means the foreground icon defined for a type in schema is simply ignored if there happens to exist an icon with the same name as the type and this shouldn't be the case. This PR flips those cases around so that the foreground icon defined by schema is …
> foreground icon resolve fix

- CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/RecentFiles.java
In a very niche case, selecting a recent file of which the source file has been unzipped manually from a star file results in constellation displaying the folder and file contents of the uncompressed text that represents the graph being imported. see below screenshot:
This PR fixes this issue by preventing recent files that are directories from being included in the recent files list. 
The result of opening the file in this way (seeing the saved files json text) may be a useful feature but should be implemented intentionally instead of being a side effect.
The welcome view does not dynamically update during runtime so if a user were to alter the file as …
> Importing recent files that have been unzipped

- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/UndoGraphEditState.java
A change made to `UndoGraphEditState` here #2031 had resulted in some significant performance issues with loading graphs. This change reverts the changes made to that class and fixes the performance issue
Improved performance
Performance no longer as degraded
Sonar smells are restored by it seems they will need to be addressed another way (another time)
1. Open new graph
2. Run Sphere Graph builder with 50k nodes, 50k transactions
3. Difference running on master vs this branch should be significant (will vary depending on system but on my system it was around 10 secs vs 5.5 mins)
> undone change to undo graph edit state causing performance issues

- CHANGELOG.md
- CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewTopComponent.java
- CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
- CoreViewFramework/src/au/gov/asd/tac/constellation/views/NoGraphPane.java
- CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudController.java
- CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudPane.java
- CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudParametersPane.java
- CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudTopComponent.java
- CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/utilities/WordCloudUtilities.java
Word Cloud threw an exception if the Generate button was clicked when there was no graph open. Rather than simply alerting the user that a graph needs to be open when the button is clicked, I've instead opted for something similar to Layers View in which with no graph open, the view instead simply displays a message saying that a graph needs to be open in order to use the view.
To do this, I've abstracted the `NoGraphPane` from the Layers View into the View Framework which enables us to add the same thing for the Word Cloud View. It also enables other views to take advantage, should we decide to include it for other views down the line.
I could've simply …
> Word cloud view fix for no graph

- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessViewTopComponent.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataSourceTitledPane.java
- CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/SchemaViewPane.java
- CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/TableViewTopComponent.java
- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/visual/VisualManager.java
Addressing the issue found in #2157 
Changed some key areas of code that were using the global fixed threadpool to instead have their own dedicated fixed threadpool.
This avoids situations where functionality was being unnecessarily blocked when the global fixed threadpool was exhausted.
Considered using the cached threadpool, but for long running processes, it is recommended to use a fixed threadpool.
Prevent unnecessary locks/blocking in the system.
Improve system performance and usability.
Create multiple new graphs and confirm you can keep creating new graphs beyond the number of logical processors in your system. And each new graph is fully …
> Revised some of the fixed Threadpool usage.

- CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBubble.java
- CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationDatetimeProvider.java
Testing on Linux, it was found that the tail of the Conversation Bubble was not connected to the main body of the bubble due to the length of the date/time string shown beneath the bubble. 
The size of the date/time text has been reduced to keep it within the bounds of the bubble body.
This allows the tail to be positioned correctly.
Also corrected an issue where the colours were not matching at the bottom of the conversation body and the top of the tail.
Could reorganise the layout of the bubble and the timestamp info if preferred.
To address a visual issue with the Conversation Bubbles seen on a Linux machine.
Confirm that the Conversation Bubbles are …
> Fix Conversation bubble issue with detached tail

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java
- CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPluginNGTest.java
Addressed a Box Selection issue (where you click and drag the mouse over the graph to create a selection area) ...
Currently, when Layers are active, and the graph window is displaying a subset of graph elements appropriate to the active layers ... all elements with x,y coordinates within the selection box are being selected, regardless of their visibility.
The Box Selection functionality should filter out graph elements that are not visible for the active layers.
The code will now check if a graph element has appropriate visibility before being included in the set of elements being selected during a BoxSelection action.
Note: this fix only addresses one …
> Layers View: Box selection should not include invisible elements

- CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/filechooser/FileChooser.java
Set the main window to be the parent of the FileChooser approver so that the confirmation dialog will pop up on the same screen/monitor.
This will enable the FileChooser confirmation dialog to appear on the same screen as the app.
This will enable the FileChooser confirmation dialog to appear on the same screen as the app.
The first 2 set of steps (File Save and File Open) are to verify that the first 2 issues raised in ticket #2082 have already been fixed.
1 - File Save
a) Open a graph
b) Export the graph to an SVG
c) export the graph to a KML
d) Save the KML in the same location as the exported SVG
e) Note no warning dialog
2 - File Open
a) Open the …
> Update FileChooser.java to popup confirmation dialog on same screen

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java
A recent change to the Box Selection function causes an exception when used on graphs that were created prior to June 2020 (this is when the layers view was introduced).
Older graphs don't have the layer_visibility attribute, so the Box Selection function will fail.
The code has been changed to now check if the attribute exists before using it as a selection restriction.
N/A
Compatibility with older graphs.
Compatibility with older graphs.
N/A
Open a graph that was created prior to June 2020
Try to do a Box Selection on some graph elements 
(Box Selection = mouse click and drag to create a rectangular selection area) 
Confirm the graph elements are …
> Box Selection fix for older graphs

- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/NewGraph.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/OpenGraph.java
The New Graph and Open Graph rest functions have a 10 second timeout applied to them and so if that timeout is reached, you get a http 500 error thrown. For a new graph, this can happen the first time a graph is opened in a Constellation session as sorting out things with the GPU the first time around can sometimes result in this time being exceeded.
This change removes the timeouts which allows the functions to run along as needed.
I also considered extending the timeout limit (e.g. to 30 secs) but in the end decided that the timeout period wasn't necessary. While nice in theory as it avoid having notebooks run for a considerably long time, there are 2 …
> removed timeout from rest functions

- CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
- CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponentNGTest.java
Fix exception being thrown when closing and saving graphs too quickly. This was because a second temp file would be made before the first was cleaned up, causing an error.
Could possibly use a slightly more complex solution that keeps track of files being saved in a queue system. That way there would never be duplicates. However, the simpler approach of checking if the temp file already exists is better, I think, as edge cases would be unlikely.
N/A
Exception no longer thrown, and graphs can be saved even when rapidly closing tabs and saving.
I can see an edge case where an old temp file wasn't removed previously, and it just so happens to have the same …
> Fix exception being thrown when closing and saving graphs too quickly

- CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/resources/time-filter-dark.css
- CoreViewFramework/src/au/gov/asd/tac/constellation/views/ListeningTopComponent.java
- CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
- nbproject/project.properties
Some minor fixes for some issues found in v3.1-rc1
- Warning found in the logs for an incorrectly formatted css styling
- Fixed typo in what's new text 
- Potential fix for inconsistent null pointer thrown in top components when a graph is null when `graphChanged` is called
Fixes for issues in Core
> Minor fixes for v3.1-rc1

- CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationColorProvider.java
The issue was caused due to the (sender < colorPositions.length) check in the `DefaultConversationColorProvider`, where the sender is a vertex  id and the colorPositions.length is graph Vertex count. The vertex ids are not in order for graphs created by file importer as it adds 2 vertices for each transaction and then merge unique vertices accordingly. This results in certain vertex Ids > graph Vertex count, failing the above check for certain valid Vertices.
The same scenario can also occur on a graph manually created: On nodes last added after deleting some previously added nodes. (As explained below)
This is the intentional behavior of the code in in …
> Conversation View Color Exception fix

- CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/AnalyticSchemaFactory.java
- CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GraphMLImportProcessor.java
- CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeTransactionsPluginNGTest.java
- CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/GraphRecordStoreUtilities.java
Transactions and Vertices that have custom types were being incorrectly processed when the Complete With Schema function is run.
They should now be treated the same way as having a default type.
Issue was found in #2307 when importing GraphML files,
but the problem was not limited to that scenario.
Also addressed the issue #2308 for GraphML imports to correctly process the "all" setting.
Have standard functionality perform in an expected way.
Functionality performs in the way that a user would expect.
Setting attributes on a custom type will not have them overridden when a Complete With Schema function is performed.
None known
1. Create a new graph. Add …
> Fix incorrect Complete With Schema processing on custom Types

- CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/AnalyticSchemaFactory.java
Analytic graphs now set the key attributes other than the Identifier, before creating the new element, to avoid duplicate key exceptions thrown. For Vertices it's Type and for transactions Type and Datetime. 
When creating a new element, the code uses the key attributes to determine whether it already exists, before incrementing the unique id in the identifier. Prior to these changes, any new element added was always identified as non existing, hence didn't impact new graphs unless edited in between.
N/A, but perhaps we should change the code in the VisualSchemaFactory which uses the DuplicateKeyException thrown by StoreGraph.validateKey, to identify …
> Fix the DuplicateKeyException in Analytic graphs when creating a new element with existing key attributes

- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/SwaggerServlet.java
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/swagger-ui/index.html
- CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/swagger/constellation.json
Improve authorization using security scheme
Improve authorization using security scheme.
Authentication to be handled in with securitySchemes instead of adding secret as parameter in each end point.
Constellation secret is now added only once to authorize with all api endpoints.
1. Open Swagger (Run constellation and Tools->Start Rest Server then Display Rest Server Documentation).
2. Grab constellation secret from  $HOME/.ipython/rest.json  to Authorize api endpoints
3. Check the Endpoints. It should not ask to enter constellation secret as a parameter.
All api endpoints should be able to use provided constellation secret for authorization.
#1458
> #1458 - Improve authorization using security scheme

- CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/NamedSelectionTopComponent.form
- CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/NamedSelectionTopComponent.java
When the fontsize of Constellation is increased, it causes the text in the Named Selections View to be cut off and hard to read.
Fixes an issue in Core 
Makes the text easier to read
Devs:
1. If running from netbeans, in Constellation project.properties, add --fontsize 20 after the line "-J--add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED" (don't forget to add a backslash after this line)
2. Restart netbeans
3. Run Constellation. Text should be fontsize 20.
4. Open Named Selections View and create a few Named Selections 
5. The Named Selections should be easy to read and not cut off 
With executable:
1. Navigate to where executable is and open …
> Fixed Named Selections spacing
