build.xml

Change the copy of unfolding maps to be downloaded from the third-party-dependencies repo

Move unfolding maps dependency

---

CoreArrangements/src/au/gov/asd/tac/constellation/arrangements/circle/ArrangeInCirclesPlugin.java

fixed the array out of bound when configuring the circle arrangements

#91 Updated to fix the NPE when selecting Circle arrangements

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/support/DefaultSupportAction.java

Update the GitHub URL to the new repository.

Update the constellation url

---

CHANGELOG.md
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataSourceTitledPane.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPlugin.java
CorePluginFramework/src/au/gov/asd/tac/constellation/pluginframework/parameters/PluginParameters.java
CoreScripting/src/au/gov/asd/tac/constellation/views/scripting/utilities/ScriptingUtilities.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/impl/PluginImpl.java

Added PluginParameters.hasParameter() to the Core Plugin Framework module as a convenient way to check if a parameter exists.
The code is a convenient method so that instead of doing:
```java
if (parameters.getParameters().containsKey(parameter.getKey())) {
// do something
}
```
you can do:
```java
if (parameters.hasParameter(parameter.getKey())) {
// do something
}
```

Added PluginParameters.hasParameter()

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/GraphRendererDropTarget.java

added a null check in GraphRendererDropTarget.java to avoid null pointer exception on drag and drop action on a graph.

fix for exception thrown at GraphRendererDropTarget.java

---

build.xml

* Remove existing dependencies before doing an `update-dependencies-clean-build`
* Use a variable for the destination distribution files

Minor update to buid.xml

---

CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/sna/metrics/MultiplexityPlugin.java

A null pointer fix for when there is no type defined for a node.

Minor null pointer fix

---

branding/core/core.jar/org/netbeans/core/startup/Bundle.properties
branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties
nbproject/project.properties

* The application name can just have a capital C
* Set the license to be Apache 2

Change some project settings

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeTransactionsPlugin.java

* Make a public constant that can be used to set the `LEAD_PARAMETER_ID` when calling this plugin
* Remove an unused private static string

Minor update to merge transactions plugin

---

build.xml

Fix to LF in the Linux build zip

:penguin: Fix to LF in config file

---

CoreGraph/src/au/gov/asd/tac/constellation/graph/attribute/AbstractObjectAttributeDescription.java

The AbstractObjectAttributeDescription.getString() method returns
`String.valueOf((T) data[id])` even if `data[id]` is null. This returns
the String "null" when a float_or_null value is null, which in turn
causes Float.parseFloat() at line 90 in RestUtilities.addData() to
throw a java.lang.NumberFormatException: For input string: "null".
This commit checks for a null value and returns either a non-null
value or null.

:bug: Fix issue #135 - return correct null value.

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/shaders/Graph.fs
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/shaders.txt

Changed two more files to use from texture2D to texture as there are trace errors when running with the new proposed change suggested on PR#120. Tested in Mac OS Mojave

Changed two more files to use from texture2D to texture as there are trace errors in Mac

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/docs/introduction.html

* Update the wording to the correct view name being the attribute editor.
* I'd actually like to replace this html file something more comprehensive like the quick start guide PDF file but for now, the reference to the "Properties window" needs to be corrected at least.
* We also have the "Welcome tab" to do so maybe that will make this redundant?

Minor wording improvement to the introduction help page

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java

When the score quality is between 60 and 90 the text colour is changed to white. White text colour doesn’t clash with the blue background making the text easy to read.
Instead of changing the text colour to white, the background colour could be changed to a different shade of blue or a different colour entirely. This design was chosen because it was the smallest and simplest way to solve this issue without changing much of the appearance of the Quality Control View. 
It enhances the readability of the Quality Control View. 
This change will improve the readability of the Quality Control View’s UI. 
N/A
I tested it’s functionality by manually setting the quality score to 60, then 80 to see if the white colour made the text easier to read.  
N/A

Add fix for Quality Control View issue #132

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java

It was creating a new instance every time getInstance() was called which violates the singleton pattern and created an infinite loop of new threads. 
Adding 1 second into countDownLatch.await(). This didn't solve the overall issue. 
The bug made it difficult to use the Data access view and the quality control view. 
Fixes a complete freeze of constellation. 
The steps to reproduce the bug were followed and constellation no longer froze.

Fix for Dav freeze issue #170

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/state/DataAccessPreferenceKeys.java

Added a check selection in the options menu of the DAV to deselect plugins after pressing Go.
Allows users to decide if they want the plugins in the data access view to be deselected when the Go button is clicked
See above
The option was used multiple times to ensure it's functionality is an appropriate solution for this enhancement.

Deselect plugins after pressing go #225

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java

The issue was that the JavaFX thread and the Event queue thread were accessing the currentQuestion in an unsafe way. I've added reentrant locks to the lines of code that cause the exceptions. 
Using a synchronised block to perform the same function. This alternative wasn't used because this type of lock didn't seem to resolve the issue. 
Resolves exceptions when using the analytic view. 
Resolves exceptions when using the analytic view. 
The steps to reproduce the errors were continuously repeated without issue. 
This only resolves the Illegal argument exception and the first concurrent modification issue that was documented in the ticket. The other concurrent modification exception is still unresolved. 
I only added locks on the lines of code that modified the currentQuestion and caused …

Analytic view Exceptions on creation / switching of graphs #196 

---

CHANGELOG.md
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/support/SupportPackage.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/support/SupportPackageAction.java

Fix a spelling error with the SupportPackageAction and minor code refactor.
* Fix a typo with the spelling to `SupportPackageAction`
* Exposed the log directory so that it can be used in other modules

Fix to the Support Package class name

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt

Added missing what's new entries. What's new entries can inform users of things that have changed in Constellation and there has been some great work done recently but none of them are visible to the user.
These entries double up as a good release notes so I do want to mandate that going forward any change should either have a `whatsnew.txt` entry if its something that is user facing or add a change to `CHANGELOG.md` if it's a change to the back end that developers should know about like when classes are renamed/refactored.
**NOTE:** If the wording can be improved or if I've missed something let me know or feel free to edit the what's new entry in this branch directly.
Show users what has changed.

Whats new updates

---

README.md

PR adds a table of contents to the readme

add TOC to readme

---

CHANGELOG.md
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt

Add missing doco for issue #179 or PR #258 .

Updated CHANGELOG.md and What's New

---

docker/netbeans-runner/Dockerfile.netbeans-11
docker/netbeans-runner/Dockerfile.netbeans-8.2

format Dockerfiles

---

docker/netbeans-runner/Dockerfile.netbeans-11
docker/netbeans-runner/Dockerfile.netbeans-8.2

Adds the `-q` flag to the Dockerfiles + updates the 11 jdk to `zulu11.37.17-ca-fx-jdk11.0.6-linux_x64`

silence unzip + update java jdk

---

.gitignore

PR adds MacOS's `.DS_Store` files to `gitignore`

add .DS_Store to gitignore file

---

.travis/run-tests.sh

PR updates + adds comments to the CI script

add comments about tests

---

.travis.yml

Based on the recent [breaking changes](https://community.sonarsource.com/t/error-not-authorized-please-check-the-properties-sonar-login-and-sonar-password/21076/7) with Travis' sonar addon

update sonar addon token definition

---

README.md

Minor update to formatting and moved some of the pre-requisites to the build Constellation section because we bundle the JRE with Constellation so users don't have to have Java installed.

Update to README formatting

---

CHANGELOG.md
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/GraphRendererDropTarget.java

Fix a logic bug preventing any graph drop targets from being called because the null check will never be met.

Fix a bug in Graph Drop Target

---

README.md
build.xml

* Changed the reference to the `jhall` and `org-netbeans-module-help` jar files to use our 3rd party folder instead
* Updated the doco to point to the latest version of Java11 and NB11.3
* Updated formatting to stay in sync with https://github.com/constellation-app/constellation/pull/275

Update to README (NB11)

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find/advanced/FindComparisons.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/DateAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/LocalDateTimeAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/TimeAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/TimeZoneAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/ZonedDateTimeAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/DateAttributeDescriptionV0.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/DateTimeAttributeDescriptionV0.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/TimeAttributeDescriptionV0.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GraphDisplayer.java

- Handled single quotes in printf format-style strings
- fixed a bug that popped up in find
All identified in Sonar

Single quote escaped

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/chinesewhispers/ChineseWhispers.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/paths/FindSubgraphs.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/circle/SphereArranger.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hde/HighDimensionEmbeddingArranger.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/proximity/FR2DArranger.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/proximity/FR3DArranger.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/random/RandomArranger.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/ArrangeInSingleTreeAction.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/experimental/TestParametersPlugin.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/DateAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/LocalDateTimeAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/TimeAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/TimeZoneAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/ZonedDateTimeAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/DateAttributeDescriptionV0.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/DateTimeAttributeDescriptionV0.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/TimeAttributeDescriptionV0.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/layers/ThiessenPolygonsLayer.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GraphDisplayer.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/AttributeFillBuilder.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/CompleteGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/PreferentialAttachmentGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SmallWorldGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SphereGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/StructuredGraphBuilderPlugin.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/components/TimelineChart.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/json/JsonUtilities.java

- converted uses of Random to be using Single instances
- changed some type casts to occur on operand rather than operation
- added NoSuchElementException to some instances of Iterator.next()
- corrected mistake from previous PR: single quotes now properly escaped
All these brought up by Sonar

Random reusable

---

.travis.yml

Get Travis build notifications in Gitter

Get Travis notifications in Gitter

---

CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/plugins/AttributeCalculatorPlugin.java
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/script/DefaultScriptLoader.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationSenderProvider.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/SelectableLabel.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/widgets/DateTimeRangePanel.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ActionPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportTableColumn.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/parser/SQLiteImportFileParser.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/AutosaveGraphPlugin.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/AutosaveStartup.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTileRenderer.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/update/UpdateController.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/state/TableStateIOProvider.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/dragdrop/ImageIconDropper.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/PluginServlet.java
nbproject/platform.properties
nbproject/project.properties

Replaced instances of Throwable.printStackTrace(...) with logger.log(...) as suggested by sonar

replaced stack trace prints with log entries

---

CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributePreferenceKey.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/advanced/FindTypeOperators.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/access/DoubleValueUpdater2.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/access/FloatValueUpdater2.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/access/IdValueUpdater2.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/access/IntValueUpdater2.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/access/LongValueUpdater2.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/access/ObjectValueUpdater2.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/access/ObjectValueUpdater4.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/access/ObjectValueUpdater5.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/widgets/NamedColorPanel.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GLInfo.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/SingleChoiceInputPane.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/RecentParameterValuesKey.java
CorePreferences/src/au/gov/asd/tac/constellation/preferences/GraphPreferenceKeys.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/components/Transaction.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/color/ConstellationColor.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/nifi/FlowFileV3Utilities.java

Made some changes suggested by Sonar:
- made NAMED_COLOR_LIST an immutable list
- made some public static fields final (if no other changes were being made to value)
- changes the visibility of some public static mutable variables

public static handling

---

CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/resources/editor-dark.css
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/resources/conversation.css
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/resources/tutorial.css
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/resources/quality-control-view.css

I've commented out the references to the obsolete JavaFX skins which will prevent the NoClassFound errors. There is more work to be done which is documented in #308.
Requires more investigation but we could use the ControlsFX skins. Not sure how they can be used so I felt this could be an investigative task in #308.

NB11 Quality Control View Fix 

---

CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/RestServiceServlet.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/SwaggerServlet.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/resources/constellation_client.py
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/restapi/RestServiceRegistry.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/restapi/RestServiceUtilities.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/AddRecordStore.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetAttributes.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetIcon.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetPluginDescription.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetRecordStore.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetServiceDescription.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetTypeDescription.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/ListIcons.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/ListPlugins.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/NewGraph.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/RunPlugin.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/SetGraph.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/SetGraphValues.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/transport/FileListener.java

Updates to previous PR due to SonarCloud.
N/A
Fixes for a previous PR in Core.
Stop SonarCloud from complaining as much.
Possible new bugs.
Tested changes.
SonarCloud complaints.

Fix a bunch of SonarCloud issues.

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/flow/FlowNetwork.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/flow/Network.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/infomap/InfomapBase.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/infomap/InfomapGreedy.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/util/Lcg.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/GraphTaxonomyArranger.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArranger.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialTopComponent.java
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/WhatsNewProvider.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/TimeZoneAttributeDescription.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/gui/SimpleGraphOpener.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironment.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/translator/DateAttributeTranslator.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/translator/DatetimeAttributeTranslator.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/translator/FindAndReplaceAttributeTranslator.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpener.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/AutosaveStartup.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/providers/EsriMapProvider.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GLInfo.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/IconBatcher.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/GLTools.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/TextIoProgress.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/dragdrop/DragAction.java

Fixed format strings as recommended by Sonar.
Changes include:
- change \n to %n
- changed from format string to string if no format specifiers
- used/removed unused parameters

fixed format specifiers

---

CHANGELOG.md

Added formatting to code snippets. Thank you @antares1470 for the Python script!

CHANGELOG.md formatting

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/logging/ConstellationLoggerHelper.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/WebServer.java

:bug: fixed an incorrect string constant

nb11-crypt-fix

---

CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SphereGraphBuilderAction.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SphereGraphBuilderPlugin.java

Increase the default sphere size and add some random blazes.
N/A
N/A
N/A
N/A
N/A
N/A

Increase the default sphere size and add some random blazes.

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/circle/ArrangeInCirclesPlugin.java
CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/DefaultOpenFileImpl.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/ThreadConstraints.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/RunPane.java

Made changes to conform to the rule

RULE (Java) Assignments should not be made from within sub-expressions

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/tree/TreeData.java
CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/DefaultOpenFileImpl.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationPointMarker.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/MarkerUtilities.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/UriIconData.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/image/GaussianBlur.java

Made changes to conform to this rule.

Rule (java) asserts should not be used to check the parameters of a public method

---

CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/axis/ZonedDateTimeAxis.java

Small update to ZoneDateTimeAxis to comply with this Rule

RULE - Java Return values from functions without side effects should not be ignored

---

.github/workflows/stale.yml

Add a stale detection action workflow that will run once a day. With the growing number of issue and PRs we need to keep on top of them and make sure we don't let them hang around forever or be forgotten about.
This is a very lenient numbers and hopefully we don't see this too often!
Add a stale detection action workflow that will run once a day. With the growing number of issue and PRs we need to keep on top of them and make sure we don't let them hang around forever or be forgotten about.
This is a very lenient numbers and hopefully we don't see this too often!

Stale detection action workflow

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPlugin.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractFromContentPluginNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPluginNGTest.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/CoreTestingPluginRegistry.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SleepEditPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SleepReadPlugin.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/WebServer.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/ConstellationApiServlet.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/resources/constellation_client.py
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/AddRecordStore.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetAttributes.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetGraphValues.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/GetRecordStore.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/RunPlugin.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/RunPlugins.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/SetGraph.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/SetGraphValues.java

New run_plugins service. Also updated ExtractWordsFromTextPlugin.
N/A
That's where it is.
Multiple plugins can be run at once.
Check with that ExtractWordsFromTextPlugin still works as expected.
The run_plugins service was tested using a Jupyter notebook and ExtractWordsFromTextPlugin.
ExtractWordsFromTextPlugin unit tests were run, and more were added.
N/A

Master nb11 rest service

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/infomap/InfomapBase.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironment.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/widgets/IconChooser.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpener.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/GLTools.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/logging/DefaultConstellationLogger.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/templates/SimpleEditPlugin.java
CoreSecurity/src/au/gov/asd/tac/constellation/security/proxy/ProxyUtilities.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/state/TableState.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/debug/MemoryAction.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/jdbc/ExportToJdbcPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/jdbc/ImportFromJdbcPlugin.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/camera/BoundingBox.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/DefaultCustomIconProvider.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/UriIconData.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/nifi/rest/NifiClient.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/rest/Response.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/WebServer.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/RunPlugins.java

Fixed up some of format string sonar smells that were missed the previous time a PR was done for this

Missed rules

---

CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/panes/AttributeCalculatorPane.java
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/panes/CalculatorTemplateDescription.java
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/script/ScriptIO.java
CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/save/AutosaveUtilities.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/io/GraphByteWriter.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/templates/ManageTemplatesPlugin.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/templates/SaveTemplatePlugin.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/TableViewTopComponent.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/GraphicsCardUtilities.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/WebServer.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/transport/FileListener.java

- return values containing operation status codes are no longer ignored
- mutable enum fields are no longer public

Return values

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/DateAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/LocalDateTimeAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/ZonedDateTimeAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/DateAttributeDescriptionV0.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/compatibility/TimeAttributeDescriptionV0.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedFileImporterStage.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/RunPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/geospatial/ExportToShapefilePlugin.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/MarkerUtilities.java

Csv importer fixes

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/docs/analyticview.html
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/docs/calculator.html
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/tutorial/resources/Contents.html
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/tutorial/resources/ForPythonUsers.html
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/docs/mapview-layers-day-night.html
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/docs/mapview-layers-heatmap.html
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/docs/mapview-layers-paths.html
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/docs/mapview-layers-thiessen-polygons.html
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/docs/mapview-overlays-info.html
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/docs/mapview-overlays-overview.html
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/docs/mapview-overlays-tools.html
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/docs/mapview.html
CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/docs/pluginreporter.html
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/docs/qualitycontrolview.html
CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/docs/scatterplot.html
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/docs/tableview2.html
nbproject/project.properties

- made a public field private
- removed need for majority of deprecated html tags

Deprecated html

---

CHANGELOG.md
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewTopComponent.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/SharedDrawable.java
CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/axis/ZonedDateTimeAxis.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/DefaultCustomIconProvider.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/image/GaussianBlur.java

- removed problem of parameters overwritten before initial value is used
- removed chance calling function on null object

More sonar fixes

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MaxScoreAggregator.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MeanScoreAggregator.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MinScoreAggregator.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/SumScoreAggregator.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/results/ScoreResult.java
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/resources/obliterator.py
CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/io/GraphJsonReader.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/UndoGraphEditOperation.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/formats/ScriptFormatter.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/translator/DateAttributeTranslator.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/translator/ScriptAttributeTranslator.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/query/QueryEvaluator.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/resources/constellation_client.py

- no longer call get() on optional variable without checking whether value exists
- cast the value of parameter of calls to Double.longBitsToDouble as a double
- handled duplicate string literals in both python and java (ones that were missed previously)
- added comments to empty python methods

Optional values and some python changes

---

CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewPane.java

Update UI with Gridpane
Switch to using a GridPane to keep alignment of headings correct
N/A
Looks much better
Keeps columns aligned
Test in multiple different view formats
#223

:art: Switch Layers to GridPane

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/docs/data-access-options.html
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt

Updates to the help text to reflect the changes for #235 and added whatsnew comments.

Remove data access prefreences

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/flow/FlowNetwork.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/infomap/InfomapGreedy.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/paths/SP2Traverse.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/metrics/ConnectivityDegreePlugin.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/MdsArranger.java
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/plugins/AttributeCalculatorPlugin.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPlugin.java
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/compare/CompareGraphPlugin.java
CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/io/GraphJsonReader.java
CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/io/GraphJsonWriter.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramTopComponent.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/geospatial/AbstractGeoExportPlugin.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/ValueInputPane.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/CompleteGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/PreferentialAttachmentGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SmallWorldGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SphereGraphBuilderPlugin.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/geospatial/Shape.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccess.java

As suggested by sonar, (sensibly) reduced the cognitive complexity of some functions

Cognitive complexity

---

CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/utilities/LayersContextMenu.java

Resolved the null pointer exception when right clicking on a graph

Null Pointer when right-clicking on graph

---

CHANGELOG.md
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPlugin.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/HitTester.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/NewLineRenderable.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/PlanesRenderable.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionBoxRenderable.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/AxesRenderable.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/FPSRenderable.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GLRenderable.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/query/QueryEvaluator.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/visual/VisualManager.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/visual/VisualOperation.java

- moved some interface constants to enums
- added default cases to switch statements
- ensured conditionally executed code was reachable

More Java sonar fixes

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/BooleanObjectAttributeDescription.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/query/QueryEvaluator.java

Changed methods of return type boolean to only return boolean expressions, as some cases were present where a null could be returned.
N/A
Resolves code smell identified by SonarQube.
Reduces code complexity.
N/A
Executed Constellation and attempted to open, draw to, create new and save graphs to observe if any functionality was lost or new bugs were introduced. Application still functioned as normal.
#280

RULE (Java) Null should not be returned from a "Boolean" method

---

CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/SharedDrawable.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/ExportGlyphTexturesAction.java

I looked at this bit of code during my review of #446 and couldn't help but fix the following:
* Fixed some exceptions seen running Experimental -> Glyph Textures
* Removed some comments no longer used
* Added some finals

Fix some bugs running Export Glyph Textures

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/BooleanObjectAttributeDescription.java

Added comment to affirm returned non-boolean value is intentional.
N/A
N/A
Code clarification.
N/A
N/A
#280

Rule (java) null should not be returned from a boolean method (COMMENT)

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/support/SupportPackageAction.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/StringUtilities.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/support/SupportPackageNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/text/StringUtilitiesNGTest.java

* Perform basic sanitisation of system properties
* Added `StringUtilities.removeSpecialCharacters`
* Fix the location of the `StringUtilities` unit test

Sanitise the user.name property prior to use

---

CoreAttributeEditorView/nbproject/project.xml
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/DateEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/DateTimeEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/LocalDateTimeEditorFactory.java

Fix for date attributes not accepting typed values
Added a fix to allow date attributes to accept typed dates

Editing a date attribute by typing in a value does not update that attribute. #475

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/LayerByTimePlugin.java

Resolved the array out of bounds exception by creating the missing custom attribute. 
The missing attribute was NLAYERS which according to a comment it means number of layers. When creating this missing attribute I've set the default number of layers to 1.

Update to Layer by time to resolve missing attribute

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/arrangements-idx.xml
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/arrangements-toc.xml
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/docs/visualgraph-map.xml

Fix some minor typos picked up during testing the new help system following https://github.com/algol60/reconst

Minor fixes to help files

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java

Fixed the bug where box selection doesn't work properly when not at the x,y,z coordinates (moving towards x2,y2,z2 coordinates). This was caused by a mismatch in mix ratio ranges where the code was expecting a different range to what it was actually receiving.
Users can box select properly regardless of the number of times PgUp and PgDn are pressed
1) Opened a new graph and created a few nodes in different places
2) Verified I could box select each node both individually and all together
3) Pressed PgUp a few times and ran the same verification process as in step 2. Did this a few times for different number of PgUps and PgDns
4) Added some transactions and did the same thing
#389

Box selection when moving to x2,y2,z2 coordinates

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/SaveGraphPlugin.java

Added an enhancement that allows the user to hardcode in a filepath to save a graph to within the saveGraphPlugin.

Save graph plugin to include a file path parameter #53

---

CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/DefaultExternalDropHandler.java

Altered code to a working state from v1.3 of Constellation to regain functionality.
N/A
It is basic user functionality.
Regain drag and drop functionality.
N/A
Dragged and dropped graph to check if the graph opened as expected.
#450

Drag and Drop fix

---

CHANGELOG.md
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt

* Added some recent changes that was missing from the change log file.

Update to release notes

---

README.md

Added a minor comment to mention MacOSX and remove the warning now that we do have basic support for MacOSX.
#21

Updated README.md with MacOSX Support

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreQueryPlugin.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java

The issue was that the remove unused attributes plugin classified vertex and transaction attributes as unused because some values were null? although they had a default value. These were getting deleted and then checked by Test Parameters. Test Parameters then updated a variable that triggered a layer refresh.
This Pr will check if an attribute exists before using it. Specifically for the layers view attributes.
An alternate design may exist, but this is the only fix that came to mind.
bug fix
no error
N/A
Tested via running remove unused attributes and test parameters at the same time. 
Tested for any drawbacks in the layers view usage
#460

:bug: DAV Freeze fix

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/geospatial/Shape.java

* Cache the output from CRC.decode() as it was taking on average 4 seconds to compute the default "EPSG:4326" value and resulted in lags opening the Schema View. The Schema View was affected because the Plugins tab populates all of the attributes with default values and CRC.decode() was being called twice which made the view hang. All other tabs look like they are doing the right thing.
This observation was found during performance testing #406. The NodeProviders look to be doing the right thing but I will investigate a bit more of anything else we can do to improve performance.
It is interesting to note that the SchemaView is susceptible to performance issues not due to its code but due to other parts of code. Not much we can do about it.
Less delay loading the Schema view and in theory …

Minor Performance Improvement to Schema View (#406)

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.form
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java

icon location contained a typo causing the whole view to not load
N/A
allows the window to be opened
Allows the window to be opened
N/A
tested window opening
#539

:bug: Fix heirarchical clustering icon location

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocation.java

Fix to Merge nodes by location (alternative solution to #538) which will exit at the start of the plugin and won't create attributes that are not required.
I've run the plugin after creating some nodes which don't have the lat/long attributes.
#533

merge nodes by location (alternative solution)

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersPane.java

Allow the labels of plugin parameters to scale to a wider width and enable the whole pane to grow.
N/A
Allows readable menu items for the analytic view
Allows viewing of analytic view plugin parameter labels
N/A
Testing scaling of application through different menu toggles.
#455

:art: Allow analytic view pane to scale for labels

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/SelectableLabel.java

* This stopped working when we went to Java 11 because the class was trying to do reflection on a method that no longer existed. Removing the use of reflection seemed to fix the issue.
To reproduce the problem you will need a graph which has a date time on the transaction and the Content.Content attribute defined with some text. Next, open the Conversation View and click on a node linked to the transaction that has content. You will get an exception.
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private javafx.scene.control.ScrollPane javafx.scene.control.skin.TextAreaSkin.scrollPane accessible: module javafx.controls does not "opens javafx.scene.control.skin" to unnamed module @5777a418
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown …
```

Fix to SelectableLabel

---

CorePluginReporterView/nbproject/project.xml
CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/PluginReporterTopComponent.java
CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReporterPane.java

This PR converts the old listening framework to the generic topcomponent framework used by most of the application.
N/A
Code standardization
Code standardization
None realized
Plugin execution and filter / graph switching tests
#332 partially

Convert PluginReporter to TopComponent framework

---

CoreAttributeEditorView/nbproject/project.xml
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.form
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorTopComponent.java

Add final modifiers
convert swing panel to pane
switch over to top component framework for graph listeners
N/A
Code consistency
Code consistency
None realized
Open/close - state testing between graphs.
#332

Convert Attribute editor to JavaFx pane and use TopComponent framework

---

CoreConversationView/nbproject/project.xml
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationViewTopComponent.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/resources/conversation.css

Switch view over to TopComponent framework.
remove a transparent color in css to allow the background Top Component color to be in effect.
N/A
Code consistency
Code consistency
None realized
Opened the view. I could not replicate a way to test full functionality of the view with a conversation. _Testers may need to pay attention to the way this operates._ 
#332

Conversation view convert to TopComponent framework

---

CoreNamedSelectionView/nbproject/project.xml
CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/NamedSelectionTopComponent.java

Switch to TopComponent framework to use consistent listeners
N/A
Code consistency
Code consistency
None realised
Opening and closing views, Switching graphs
#332

Convert NamedSelection to TopComponent framework

---

CoreFunctionality/nbproject/project.xml
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialTopComponent.java
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialViewPane.java

Extract pane out into it's own class and move view to listening framework of JavaFx
N/A
Code consistency
Code consistency
None realised
Opening view
#332

Convert Tutorial View to Top Component framework

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectTopNPlugin.java

Add a null check to select top N plugin. 
N/A
Bug fix
Bug fix
N/A
N/A
#566

Select top n null pointer check

---

CoreSchemaView/nbproject/project.xml
CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/SchemaViewTopComponent.java
CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/providers/TransactionTypeNodeProvider.java
CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/providers/VertexTypeNodeProvider.java
CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/resources/schema-view.css

Add Search filters to Transaction Types and Node Types tabs in Schema View
N/A
Better UX
Better UX
N/A
Try the  Search filters in 'Transaction Types' and 'Node Types' tabs in Schema View of a graph.
#373

Add Search filters to Transaction Types and Node Types tabs in Schema View

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/temporal/TemporalFormattingNGTest.java

Unit test cases for TemporalFormattingNGTest failed due to incorrect offset time value.
Run the test cases.

Fix-broken-unit-tests for TemporalFormattingNGTest

---

CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTileRenderer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/InfoOverlay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/MapOverlay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/OverviewOverlay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/ToolsOverlay.java

:art: removed reference to `ToolOverlay` from `MapViewTileRenderer` in order to keep it loosely coupled

map-view-fix

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPluginNGTest.java

:bug: Fix a bug with split nodes plugin
* The split nodes plugin was only working splitting for one node. It now works as expected for all nodes selected on the graph.
Did some test driven development; wrote the unit test and then fixed the code until it passed.
Also did some manual testing too.

Fix a bug with split nodes plugin

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/RowFilter.java

The Filter in the preview table of Delimited File Importer is broken. It doesn't load any data in the graph for any input in the filter.
Rows that match the filter criteria should be imported into the graph.
N/A
Better UX
Better UX
N/A
1. Create a file containing the following, and call it tst.csv
a,b,c,d
1,2,3,4
5,6,7,8
2. Select File->Import->From Delimited File...
3. Open the above csv file using "+" button
4. Add the Identifier Source Node Attribute on to the column a
5. Select Destination New Analytic Graph
6. Enter Row !=1 in the Filter -> Row 1 (5,6,7,8) should be Greyed out
Now press the Import button -> There should be a node 1 in the graph.
7. Enter Row !=0 in the Filter -> Row 0 (1,2,3,4) should be Greyed out.
Now press the Import button ->There should be a node 5 in the graph. …

Fix the Filter in the preview table of Delimited File Importer

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersPane.java

Fixed the layout issue of the manage templates window. The buttons couldn't be clicked and were pushed off the edge of the screen and had unusual colons overlapping with the label text.
The buildParameterLabel method in the PluginParametersPane class had to be modified. The only pane that I am aware of that uses this is the analytic view pane and that seemed to be visually unaffected so I'm unsure of how other panes have been impacted.

Fix for for manage templates layout

---

CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironment.java

This change adds a null check to the graph parameter and in the case of run later, stops execution and logs the null graph error.
The change also includes a null check to runNow methods to log when the graph which is passed in is null.
Catch failing silently - Unsure where this was meant to be occurring. 
Additional logging
Additional logging

Null check and logging for plugin execution

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java

This bug was reproducible when running merge modes or any other DAV plugin which caused the QCV to run it's rules again.
When you close the graph, it would return a null future and cause a null pointer on `Future<?>.get()`
This fix simply adds a null check and only gets the future when one is returned.
N/A
Bug fix
Bug Fix
None realized
Running rules and testing of close graphs
N/A

QCV and DAV null pointer

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/CoreGlobalParameters.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/docs/dataaccess-idx.xml
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/docs/dataaccess-map.xml
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java

I've made a small fix so that the help icon for "Range" in the data access view is functional. 
I can't seem to figure out how to prevent it's help icon from overlapping on top of the months buttons so I haven't resolved the entire issue yet. The problem I ran into is that the icon is added using a separate template within the PluginParametersPane so I couldn't figure out how to control how its added to the pane. Does anyone have any suggestions?

Dav help fix

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/InfoMapPlugin.java

Handle running on empty graph and display a meaningful message to the user.
N/A
bug fix
N/A
N/A
Testing with and without elements
#588

#588 infomap run on empty graph

---

CoreLayersView/test/unit/src/au/gov/asd/tac/constellation/views/layers/utilities/LayersDualGraphSyncNGTest.java

This is a suggestion to #602 for @aldebaran30701.
>I'd like to help out to see if I can give some guidance to get the graph switching part to work
@arcturus2 I think I'll take you up on that offer - Above is the branch I've been testing with.
So I noticed you've used a `StoreGraph` but what I think your after is testing a `DualGraph` and test the bug with syncing graphs. To do it yourself with a `StoreGraph` and mimic the sync will effectively be implementing the `DualGraph` in a unit test so I've just used a `DualGraph`.
As a result the unit test has been modified to deal with read and write locks but the code is pretty much as you had it.
So @aldebaran30701 your unit test was passing before my changes and they are still passing after my changes. I think your introduction of the queries …

Convert PR #602 to use a DualGraph

---

CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/SharedDrawable.java

Removal of potentially superfluous filetype extension was previously
handled manually. The previous method results in the file being saved
to the wrong location if the file path has a full stop but there is no
extension given. Method now uses a built in method to remove any
extension, fixing the problem.

:bug: Fixed exportGlyphTextures method.

---

CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironment.java

* Returning null caused problems with context menu plugins not running
* Going to log this as FINE in case we want to know what's happening

Fix to the plugin environment

---

CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/GlyphManagerBI.java

When a view is opened in a COnstellation instance with multiple graphs
multiple threads are trying to use the method at the same time. As the
drawing variable used comes from the static implementation of a class
they are using the same drawing causing issues.

:bug: Synchronized renderTextAsLigatures method.

---

CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/SchemaViewTopComponent.java

Fix to a logic bug. The Schema View `showingComponent()` does not need the view to rebuild.
#631

Fix a performance and logic bug with the Schema View  (#631)

---

CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/AnalyticSchemaFactory.java

Removed a boolean condition causing issues in `completeTransaction()`
Previously, null and empty types were handled differently and so there did not appear to be any problems. In v2 though, null and empty types are handled the same and this exposed this problematic boolean condition that needed to be removed to avoid unexpected behaviour
Fixes a problem with `completeTransaction()`

Hotfix: Removed a boolean condition causing issues

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/RemoveUnusedAttributesPlugin.java

Added a check to stop the plugin from running if no nodes are on the active graph 
https://github.com/constellation-app/constellation/issues/642

Resolved the error that the remove Unused Attributes Plugin caused

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/grid/ArrangeInGridAction.java

I have changed the ArrangeInGridAction to call the GRID_COMPOSITE
plugin instead of the generic grid plugin. This changes the behaviour
so that the ArrangeInGrid action exhibitis the same behaviour as in
constellation V1. That is each subgraph gets its own grid.

:bug: Changed Arrange by Grid to use V1 logic.

---

CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/docs/attributecalculator-idx.xml
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/docs/attributecalculator-map.xml
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/panes/AttributeCalculatorPane.java
CoreAttributeCalculatorView/src/au/gov/asd/tac/constellation/views/attributecalculator/plugins/AttributeCalculatorPlugin.java

The NPE was being thrown because the attribute calculator plugin couldn't find the obliterator.py file. I replaced the URL of the file with the full location and this resolved it. 
I also made some slight changes to calculator pane so that the save and load buttons are readable and I fixed the help icon. 
https://github.com/constellation-app/constellation/issues/640

Fix for NPE in attribute calculator

---

PULL_REQUEST_TEMPLATE.md

Make sure your branch name is prefixed by `feature`, `bugfix`, `hotfix` or `release`
Keeps branches grouped together so there is less  clutter :clap:

Improve branch naming conventions

---

CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/panes/NamedSelectionListElement.java

Path was old and pointed nowhere so it caused a null pointer when the resource was not found
fix includes the correct path and now loads without issue.
N/A
Bugfix
Protect selection now works
None realised
Testing Named Selections and protecting checked/unchecked.
#643

fix path for imageicon in Named Selection View

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java

Switches default value from null to empty string. Calling .contains(null) was resulting in a NPE.
using StringUtils.EMPTY instead of ""
Unsure what is preferred in this scenario.
Bugfix
#668

:bug: switch default value to empty string

---

CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/NamedSelectionManager.java

A Consistency and UX fix for Named selections. This case removes the selection from the graph once the selection is deleted.
N/A
Consistency
Consistency
Possibly use cases which need the old behaviour ?
Deleting one or many selections
#696

:bug: remove selection alterations after delete

---

CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewPane.java

Made a slight change so that the "Visibility" label in the layers view doesn't get cut off in the .exe.
Built and ran the .exe to ensure the change fixed the label and didn't ruin the appearance of the view.

Experimental -> Layers View: View heading text cut off 

---

CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/templates/SaveTemplatePlugin.java

The recent values drop down wasn't functioning because the store recent values method was never called.

fixed save templates recent values

---

CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/AnalyticSchemaFactory.java

Revert of #651 
as per comments in #723
This will fix the transactions drawing as directed all the time..
This revert will remain in place until an issue of the blank types occurs in normal operation.
N/a
Bugfix
Bugfix
N/A
Tested draw modes
#723 #651

revert boolean hotfix

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewPane.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java

Change to use a different filechooser as the previous one would not work as a modal window. Passing the parent scene resulted in errors, so a different framework dialog worked best.
I tried using the original file chooser save prompt but it was not compatible with the current window's type.
Stops users from opening many save dialogs
Stops users from opening many save dialogs
None realised
Save file testing, attempting to open  multiple saves
#671

switch filechooser to allow modal save dialog

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewTopComponent.java

This change tracks the last current graph loaded with the view, and checks before reloading the view if a complete view reset is necessary.
N/A
Bug fix
Keeps the results pane open when using the same graph and switching views
N/A
Test opening with a graph, test opening without a graph, test switching of graph when view is minimized, test results pane consistency with same graphs.
#718

:bug: Analytic View results refresh fix

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/SaveAsAction.java

Added a regex check to restrict file names and removed functionality for making a new folder.

 Fix for forward slash being allowed in graphs name, causes errors if used

---

CHANGELOG.md

**Update to CHANGELOG.md**
* Added more specific entries to change log which was found during a migration of some v1 modules to v2 for the Cyber modules
* Sorted entries in alphabetical order
Further improve documentation to help others moving from v1 to v2

Update to CHANGELOG.md

---

CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV4UpdateProvider.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/SaveAsAction.java

I've got 2 small fixes in 1 PR (sorry in advance) that came up during testing. I have committed them separately for clarity though.
* Allow a graph name to have spaces
* Handle null Types in the upgrade

A couple of bug fixes

---

CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/BannerAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/io/BannerIOProvider.java

A simple change that resolves the Banner IO exception. This doesn't include the convertFromString() method that @arcturus2 mentioned on the issue ticket because after a bit of testing I realised it wasn't being used and did not contribute to resolving the exception. This doesn't resolve the issue regarding the banner not rendering on screen, it is likely that the banner hasn't functioned properly for some time now and will require a separate ticket. 
https://github.com/constellation-app/constellation/issues/721

Resolves the banner IO exception

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java

The split nodes plugin would throw an NPE 100% of the time when I used it on master. When updating the split nodes plugin with the new feature, @Auriga2 would experience this issue on occasion. The NPE occurs because when getting the splitParameters.get(SPLIT_PARAMETER_ID) we only checked if the parameter was null but not the string value so the string value could still return null. There is no associated ticket for this issue.
java.lang.NullPointerException
at java.base/java.lang.String.contains(String.java:2036)
at au.gov.asd.tac.constellation.views.dataaccess.plugins.clean.SplitNodesPlugin.query(SplitNodesPlugin.java:192)
[catch] at au.gov.asd.tac.constellation.views.dataaccess.templates.RecordStoreQueryPlugin.lambda$query$0(RecordStoreQueryPlugin.java:139)
at …

Bugfix for an NPE that occured when using the split nodes plugin

---

CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/GraphNode.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java

GraphNode keeps count of how many calls to turn off the loading spinner is made and only turns it off when it reaches zero. VisualGraphTopComponent just does it when it wants without checking. I've just added a simple change to make VisualGraphTopComponent call GraphNode's makeBusy method that keeps track of the count.

Fix for running query spinner disappears when saving graph

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java

Add a lock to the access of `currentQuestion`
Initially reproduced by making a new graph on fresh constellation boot. 
using sphere graph builder
launching analytic view
NPE would then occur 100% of the time.
#628
N/A
bugfix
bugfix
none- realised
Test opening and closing of analytic view + reproducer
#628

:bug: add lock to access of question - Null pointer

---

CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationPreferenceKeys.java
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java

PR for ticket #769 which adds a message to the dialog when no rules are displayed for an identifier.
Also adds a descriptive fieldname to the JSON storage of the rule priority preferences file.
N/A
feature for usability 
increases usability of the view
None realised
Opening and closing rules, opening and closing the application and reading stored preferences.
#769

add no rules message and descriptive json fieldname

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java

This change adds a listener and implements a check so that if the state of a graph is null, it clears the quality control table.
When a graph closes, it will now clear the view when there is no new active graph.
None realised
bug fix
QCV better reflects the shown graph
N/A
Testing opening of one or multiple graphs, closing those graphs to ensure the view reflects the current graph
#772

:bug: Implement graph close on quality control view

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/utilities/AttributeUtilities.java

@aldebaran30701 realised that if you open the analytic view when there is no active graph, a null pointer exception is thrown. This adds a check to just return an empty array of attributes to prevent this scenario from occurring.

Update to attributeUtilities to resolve NPE

---

ProjectUpdater/src/build.xml

* Avoid jar file clashes in the future by introducing the type pattern. See https://ant.apache.org/ivy/history/2.1.0/concept.html#patterns for more information.
The `ProjectUpdater` belongs in Core because all module suites rely on Core so it is perfectly suited to live in Core. This saves developers from having to clone a different repository before they can start to compile Constellation!
Introducing the type into the pattern prevents some jars overriding each other. Typically the `type` value will be `jar` but it can be `pom`, `xml`.
The dependency jar file names look like `commons-collections-3.2.2-jar.jar` which looks ugly but there isn't much we can do.

Update the downloaded jar file pattern

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java

This change removes the lock objects which was a fix for multiple threads accessing the currentQuestion variable.
Now, the only threads which access the variable are via the JavaFx thread.
thought of synchronizing methods, but it was so widely used it felt wrong.
bug fix
thread safe variable access
none realized
Opening and closing analytic view really fast (With and without a graph opened)
Opening and closing graphs with the analytic view opened
Selecting plugins and questions to trigger state updates.
#767

:bug: move currentquestion access to FX Thread

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ConfigurationPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/RunPane.java

A fix for issue 580. Stops the TableView from having duplicate (reversed) values further down the table.
None considered, found the cause and implemented the solution
This is a fix to an issue affecting Core.
Makes importing data look nicer.
None found in testing.
Tested locally, replicated actions to create the issue several times and error did not recur. 
To replicate 
*Open the "Import from Delimited File" Window
--Start
*Clicked Green plus
*Found sample file and clicked Open.
*Selected File in Files panel
*Clicked Red Minus
*Clicked Green plus
*Found sample file and clicked Open.
*Repeat from START with several different files
N/A

Bug 580 fix - refresh TableView

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedFileImporterStage.java

Pin the import toolbar to the bottom of the dialog so that it is not missed by the user. 
***BEFORE***
***AFTER***
N/A
Bug fix, improves usability
Bugfix, improves usability
N/A
Tested opening/closing and usability of the view.
#617

Pin import button toolbar to import delimited dialog

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/visualisation/TableVisualisation.java

This change removes the calls to Platform.runLater which are not necessary as they always run on the FX thread. this is because the code is triggered in the event handlers.
N/A
Code readability
Code readability
None realised
Testing of analytic view for running on FX thread
#786

Analytic View - remove redundant calls to Platform.runLater

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java

Added more short descriptions that will inform the user of the current state these buttons are in.
https://github.com/constellation-app/constellation/issues/713

Tool Tips should reflect button states

---

CHANGELOG.md
CoreDependencies/nbproject/project.xml
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginInteraction.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersSwingDialog.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/PluginParameters.java

When a plugin is run interactively, checks whether a multi-line string parameter exists and unfocuses ok button of swing dialog if so.
#762 
Allows users to hit enter when typing things into a multi-line string parameter via the swing dialog box 
#757

Unfocus Plugin Swing Dialog Ok Button v2

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/PluginParameters.java

Further testing for the changes made in #798 uncovered a null pointer if a parameter doesn't have the `LINES` property. This adds a null check for this.
#757

HOTFIX: added missing null check

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java

The exception occurs because the LAYER_PREFERENCES attribute hadn't been initialised yet in the recalculateLayerVisibilities method.

Resolved saved layers exception

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/LayerByTimePlugin.java

This change adds an attribute which was mistakenly removed previously.
#816

layer by time add attribute

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/LayerByTimePlugin.java

A follow up PR from #817 to standardise how the layer attribute is defined and used.
There are a few things I would do differently with the plugin but it works and there are bigger issues to resolve so I held myself back 😄

Layer by time update

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java

The new split nodes functionality duplicated transactions attached to the split node for all newly created nodes but the identifier of these transactions wasn't the original identifier meaning that if 2 nodes merged (because they had the same identifier) the transactions attached to these nodes (identical in every way bar the identifier) wouldn't merge
#743

HOTFIX: altered duplicate transaction identifiers from split nodes

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButton.java

This change simply changes the text of the button which is used within the Data Access View. It now says Quality Category.
#833

Update score text to category

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/spectral/SpectralArrangementAction.java

Changed Spectral 3D shortcut due to clash with Layers View.
NA
Bugfix
Stops duplicated shortcut
None-realised
Tested layers view and Spectral 3D
#824

Assigned new shortcut to Spectral 3D

---

CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/resources/schema-view.css

When you go out of focus from the input text field in the filter, what you typed is invisible in the black background, until you click back in the filter text field. A temporary fix here by changing the filter background to grey and filter text to black so that it's always visible.
Same behaviour on the filters on Attributes, Node Types and Transaction Types tabs.
- Find the line of code which sets the text colour to black and set it to white or a similar colour. 
- Set a priority style other than using `!important` which didn't work
Better UX
Filter text no longer go invisible.
N/A
- Open a graph and open the Schema View. 
- Type something in the `Attributes` tab and click in the graph section. The filter text colour or the background colour should not change.
- Repeat with the filters …

Schema View filter text invisible when out of focus

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/LayerByTimePlugin.java

Visibility of Duplicate nodes was being set to 0, changed to 1
N/A
Bugfix
All nodes Visible 
None realised
#830

Bugfix for Layer By Time Visibility 

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/draw/MenuSetDrawModeAction.java

Shortcut created to quickly switch between Draw and Selection mode
Shortcut created to quickly switch between Draw and Selection mode
NA
Ability to quickly switch between Draw and Selection mode
Quickly switch between Draw and Selection mode
None realised 
#796

Draw/Selection Mode Shortcut

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/RunPane.java

Loading the delimited file importer was slow and after a quick profile it turned out the ScriptingEngine job was slowing things down. Moving that to its own thread seems to make it quicker.
Would it be better to move the threading into the `RunFilter` instead?

Performance improvement loading the Import from Delimited.

---

CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/CompositeNodeState.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/clustering/ClusteringManager.java

Doing a quick profile around the timeline view identified the slowest bit being the print to console slowing down the rendering on the actual time line view. I've removed that and then searched the entire code base and there was one more `System.out.println` that wasn't commented and I decided to remove that too.

Remove redundant prints and improve performance

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialViewPane.java

Changed the What's New font size to a set size instead of using preferred font size
Different Font Size
Bugfix
What's New text easier to read
None Realised 
#712

Update to 'Whats New' Fontsize

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialViewPane.java
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt

Create a checkbox on Tutorial Page to toggle showing on start-up
NA
Easier way to turn off showing the tutorial page on start-up 
Easier way to turn off showing the tutorial page on start-up 
None Realised
#808

Create Show On Startup Checkbox

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/ByteAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/DateAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/LongAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/ShortAttributeDescription.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/TimeAttributeDescription.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/BooleanAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/BooleanObjectAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/ByteAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/ByteObjectAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/DateAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/DoubleAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/DoubleObjectAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/FloatAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/FloatObjectAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/HyperlinkAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/IntegerAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/IntegerObjectAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/LocalDateTimeAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/LongAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/LongObjectAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/ShortAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/ShortObjectAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/StringAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/TimeAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/TimeZoneAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/TransactionAttributeNameAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/VertexAttributeNameAttributeDescriptionNGTest.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/attribute/ZonedDateTimeAttributeDescriptionNGTest.java

This is related to #778 Review default values for attribute descriptions. Unit testing has also been added for all attribute descriptions and there where a couple of cases picked up in the unit testing where the actual default values were different for some scenarios. This has also been fixed by updating the attribute descriptions.
Note that there are some methods I was not sure how to test so they have been commented. The `hashCode` methods in most attribute descriptions have also been commented because they are hard to test.
With the addition of the unit tests we should have a better code coverage on the attribute descriptions which are a fundamental component.
#778

Adding unit testing for attribute descriptions

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java

FIleOutputStream is closed after the file has been written to.
Closed the file output stream after the excel file is written to.
N/A
Bugfix
Files are no longer read-only when constellation is open.
N/A
Exported multiple files and edited them while constellation was still running.
#860

Release Excel File in Table View

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java

@Delphinus8821 this is a follow up to your PR. Thanks again for fixing that bug and I really wanted to have that go into `master` asap and didn't want to hold up that being merged. This is a _syntactic sugar_ change which was introduced in Java 8 called try with resource. The resource will be automatically closed for you.
PR #883

Convert to try with resource - PR #883 Follow up

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewPane.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java

Have fixed the issue where copying and exporting data from the table view only was applied to the current page.
Bug fix in Core
Users can copy and export the entire table instead of just the page they are currently on.
Getting the selection variants working properly meant a cost in performance for export to excel
#862

Table view export

---

CHANGELOG.md
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt

Updated the whatsnew and CHANGELOG with some missing entries.
Related to changes made in Core
Fills in holes on changes made for developers and users.
Nil

updated whats new and CHANGELOG with some missing entries

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java

This change checks the mod counters of the quality control view to refresh on any change that isn't a camera move, or element selection. any other change should trigger a recalculation while the view is open.
Try to listen to any of the attribute within each rule. Possibly not scalable.
Reduces unnecessary refreshes
More performant
None realised
Opening and closing, performing actions to verify that the view listens to things it needs. Avoids refreshing when it doesnt need to.
#897

Refresh quality control state only when necessary

---

CONTRIBUTING.md

Minor updates to the conributing guide formatting

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/GraphRecordStoreUtilities.java

When converting the record store to strings, if the data in the attribute isn't parsable to the type an exception is thrown. This is bad becuase Data Access plugins fail and won't return any result to the graph. 
Each plugin could check before setting the value but that seems wasteful work every plugin has to do as is probably overkill / slow.
Nothing is stopping you from doing that but this catch-all here will allow plugins to run to completion rather than fail and stop due to edge cases; for example we expected a float and we got a string instead.

Fix to prevent plugins halting due to bad data

---

CoreDependencies/nbproject/project.xml
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java

Changes the mouse release method in HistogramDisplay to allow for click + dragging on the histogram to select multiple objects at once. Also fixes the ctrl + click + drag to select more objects or deselect currently highlighted objects within a new selection. 
N/A
Allows for users to make selections on the histogram by click + dragging over part of the histogram. Ctrl + click + drag has also been fixed to allow for users to add to an existing selection and deselect any already highlighted bars in the current selection.
An easy way for users to make selections of data in the Histogram or update current selections.
N/A
Using a sphere graph, an attribute has been chosen to display in the histogram as data and used both click + drag and ctrl + click + drag to make selections on the graph. Was …

Highlight in Histogram View 

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/SelectableLabel.java
CoreDependencies/nbproject/project.xml

Changes the SelectableLabel class from extending TextArea to extending Label. This stops the text from the conversation bubbles from being hidden as the label scales to match the size of the text.
N/A
Displays all of the text in a conversation bubble to the screen without the need to scroll.
Allows for the user to read all of the text in a conversation bubble without having to scroll through all of the bubbles to check for additional content.
N/A
Edited the attribute content to be displayed in the conversation bubbles to varying lengths, e.g. 1 line, 5 lines, 10 lines, extra blank lines. 
#914

Conversation View Hidden Text Visible

---

CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java

Added a scroll pane to the welcome page so that the content on the page is able to be seen without any buttons overlapping. The contents of the page now fill to the height and width of the current page and if the page size gets smaller than the layout of the contents of the page, scroll bars are added. This allows for the page keeps its formatting and allow all buttons to continue to be viewed using the scroll bar.
None realised
The current welcome page does not resize correctly so some of the buttons are unable to be reached. This change ensures that all of the content on the page is able to be viewed either by default or by using the scroll bars. 
Allows for all of the buttons on the welcome page to be reachable when the page is resized.
None realised
Tested by changing the size of the …

Welcome Page Resize Issue

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/MultiChoiceInputPane.java

For Single Choice and Multi Choice parameter types, the list of choices can be Strings or they can be other parameter types. When work was done to remember Data Access plugin parameter value between sessions (#759), the work done on the single choice input pane accounted for all parameter type choices but work done on the multi choice input pane only accounted for string parameter type choices.
This change mimics in `MultiChoiceInputPane` what is done in the `SingleChoiceInputPane` for remembering parameter values
Affects Core code
Fixes potential bug in case where there is a multichoice parameter whose options aren't string parameters
#25

HOTFIX: added missing case in MultiValueInputPane

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/whatsnew/whatsnew.txt
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java

A change was made previously to fix the issue of dragging in the histogram not working. The fix to this though introduced a new bug in which histogram selection wasn't applied to the graph. This change was reverted to fix the selection issue.
Reverting this change meant the dragging bug was again an issue. After some digging, I identified the cause of this to be a boolean condition that was introduced to `mouseDragged()` which meant the most of the code in the function was never executed (as this condition was always false). This condition was modified to correctly add the intended behaviour of introducing the condition.
Fixes a bug in core
Dragging and selection in the histogram now work again as intended
Nil
#941

fixed histogram selection issue

---

CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java

Made some changes to the Welcome tab pane to remove the need for some of constants, fields, and functions that were being used
Modification of code that will be in core
easier code maintenance, less variables needed
There will no longer be a max on the number of top or side plugins that can be added but I don't think this will be a problem assuming people don't go overboard with the number of welcome tab plugins they want to add
#944

welcome tab pr update

---

CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReporterPane.java

The Plugin Reporter ignored plugins currently displays the value "LOW LEVEL" as being selected by default but when opening the drop-down list it is not ticked. The change clears the combo-box value so that nothing is selected by default.
None realised
Clearly shows what is currently selected in the Plugin Reporter ignored plugins combo-box.
On a clean build of Constellation, the plugin reporter ignored plugins show none are selected by default. 
#906

Plugin Reporter Select Ignored Checkbox Value by Default

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/reporting/GraphReport.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/reporting/GraphReportManager.java
CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReporterPane.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

The Plugin Reporter currently has 2 drop-downs lists in its menu bar, one for filtering the plugins shown and the other for selecting plugins to be ignored from the list shown. This change consolidates them into one drop-down list for filtering what is shown in the reporter. 
To create a listener for each of the existing lists to have them update when the other is changed.
The current solution of the two drop-down lists is confusing for users as the drop-down lists appear to do the opposite of each other but do not always behave this way. Consolidating it to one list is more user friendly and understandable. 
None realised
#976

Consolidate Plugin Reporter Drop-Down Lists

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/LayersConcept.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/mergers/BitwiseOrGraphAttributeMerger.java
CoreLayersView/nbproject/project.xml
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/state/LayersViewState.java
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/utilities/LayersUtilities.java

This change adds some methods for use in the Constellation-Adaptors repository.
Also included is an AttributeMergerClass for handling the Bitwise OR of bits.
All operations hardcoded in Adaptors - did not appear to be a good coding practice.
Adds functionality

Add utility methods for Layers View

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/MultiChoiceInputPane.java

Fix to ArrayIndexOutOfBoundsException with Multichoice. This can happen if the values are an empty string.

Fix to ArrayIndexOutOfBoundsException with Multichoice

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewPane.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java

Reuse strings to reduce the amount of String objects in memory
The screenshots below show the before and after with a Sphere Graph build of 30k nodes and transactions and then opening the table view
**Before**
**After**

Significant memory saving in Table View

---

CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPluginNGTest.java

Add test cases for select in box plugin as per #1023 
Tests: 
- select nothing
- select one node
- select two nodes and one transaction
All test were run with two boolean flags toggled in every state, and camera mix of 1.0 and 0.0.

✅  Box Selection Plugin Test

---

CoreSecurity/src/au/gov/asd/tac/constellation/security/proxy/ConstellationHttpProxySelector.java

Fix to a logic bug perhaps as I think checking for a specific proxy should happen first/have higher priority than checking for local host.
Fixing a logic bug or priority conflict
Any existing settings where local host should be used will be unaffected as if there is not specific host check then it will fall through to the local host logic anyway.

Re-order the proxy selection logic

---

CoreGraphNode/test/unit/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginInteractionNGTest.java

Minor update to make #1030 pass

DefaultPluginInteraction Unit tests #1030 Patch

---

CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/AutosaveGraphPluginNGTest.java
CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationPreferenceKeys.java

Added unit test for the AutosaveGraphPlugin class.
Unit testing a class in Core.
Better chance of catching errors with the Autosave function.
#1023

Autosave Graph Plugin Test

---

CHANGELOG.md
CoreDependencies/nbproject/project.xml
CoreDependencies/src/ivy.xml
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/AttributeRegistry.java
ProjectUpdater/src/au/gov/asd/tac/constellation/projectupdater/ProjectUpdater.java
ProjectUpdater/src/build.xml

Here are some changes I wanted to put in to fix some common issues that was really starting to annoy me:
* Update `ProjectUpdater` to sort jars in `project.xml` consistently between Windows and Linux.
* Remove the file type being added to dependency jars as it counts towards the limited class path length in Windows.
* Fix to the missing BogusColorSpace class error seen in unit tests
```
java.lang.NoClassDefFoundError: com/sun/media/imageioimpl/common/BogusColorSpace
```
* Reduce verbose output with the Attribute Registry so we don't have the following appearing in the unit test logs
```
[testng] May 10, 2021 12:30:03 PM au.gov.asd.tac.constellation.graph.attribute.AttributeRegistry lambda$static$0
[testng] INFO: Registered Attribute …
```

Miscellaneous corrections

---

CoreFindView/test/unit/src/au/gov/asd/tac/constellation/views/find/advanced/GraphAttributePluginNGTest.java

Added simple unit test for GraphAttributePlugin class.
Created a unit test of a class that is in core.
Better chance of catching errors in the Graph Attribute Plugin.

Graph Attribute Plugin Test

---

CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginInteraction.java
CoreGraphNode/test/unit/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginInteractionNGTest.java

Have added some unit tests for DefaultPluginInteraction. Some slight refactoring of some of the code in the class was needed in order to enable the unit testing.
Note: There are a few classes I would've liked to have tested but was unable to due to dialog boxes being created. Those classes probably won't be able to be tested until we introduce libraries to allow engaging with dialog boxes in a unit test.
Unit testing a class in Core
Pick up issues with the code earlier on
Nil
#1023

DefaultPluginInteraction Unit tests

---

CoreVisualGraph/nbproject/project.xml
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccess.java
CoreVisualGraph/test/unit/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccessNGTest.java

Started writing unit tests for `GraphVisualAccess`. There's still a lot to go but I figured some tests were better than none.
Unit tests for a core class
Pick up code issues earlier
Nil
#1023

GraphVisualAccess Unit Tests

---

.github/workflows/greetings.yml

Fix a gramatic error

---

CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/delete/DeleteSelectionPluginNGTest.java

Added unit tests for the DeleteSelectionPlugin class.
Created a unit test of a class that is in core.
Better chance of catching errors with the Delete Selection Function

Delete Selection Plugin Unit Tests

---

CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/GlyphManagerBI.java

* Turns out the Rectangle hashCode method was not unique so letters where being replaced with others randomly.

Fix to labels rendering error

---

CoreDependencies/nbproject/project.xml
CoreDependencies/src/ivy.xml
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButton.java
CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButtonNGTest.java

Added DefaultQualityControlAutoButtonNG with mocked dependencies using mockito. However I didn't mock the `QualityControlViewPane.qualityStyle(event.getCategory(), 1);` of DefaultQualityControlAutoButton.update, because it's a static method. It's recommended not to mock static methods.
Uses `mockito-inline`  instead of discontinued `mockito-all` library. Unlike `mockito-core`, `mockito-inline` supports mocking Final classes if needed. (`mockito-core` needed more steps to support that) 
As per latest documentation, it looks like mockito-inline is to provide some experimental features like mocking final classes and methods, mocking static methods etc. But is likely to be discontinued once mocking of final classes and methods gets integrated into the mockito-core. If that happens we'll have …

DefaultQualityControlAutoButtonNGTest Unit tests

---

CoreDependencies/nbproject/project.xml

Fix the dependencies XML file
* Use the correct dependency file name
It looks like the `ProjectUpdater` code needs a `clean` and `build` done to make sure it is using the latest settings for some developers. This is a fix with the correct settings.
Tested on both Windows and Linux and the sort order is working pretty good too.

Fix the dependencies XML file

---

CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SphereGraphBuilderPlugin.java

An update for https://github.com/constellation-app/constellation/pull/1070 which fixes build sphere graph too.

Visual Schema Update for pinned decorator - Suggestion

---

CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/CompleteGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/PreferentialAttachmentGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SmallWorldGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SphereGraphBuilderPlugin.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV5UpdateProvider.java

This schema update adds the pinned attribute as a decorator to old graphs so that there is visual indicator to users when a node is pinned. This overrides any existing decorator in the top right.
Also considered only applying the decorator if there already wasn't a decorator in the top right
Update to reflect a change in core
Users can see the pinned attribute as a decorator on old graphs without having to manually change the decorators from the attribute editor
If a user had customised the decorators in their graph, they will the NE decorator they had set as it will be overwritten
#57

Visual Schema Update for pinned decorator

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java

Fix a bug with Import from Delimited
* Fixed an exception being thrown when importing via import from
delimited
**NOTE:** I think this PR should go in before we release v2.3

Fix a bug with Import from Delimited

---

CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV5UpdateProvider.java

Older graphs were failing to load because the call below was returning `Graph.NOT_FOUND` because it was not registered with the graph - which makes sense because it is a new attribute. Changed it to `ensure` and its working as expected.
```
final int pinnedAttribute = VisualConcept.VertexAttribute.PINNED.get(graph);
```

Fix to schema updater regarding the pinned attribute

---

CorePreferences/src/au/gov/asd/tac/constellation/preferences/docs/application-font-preferences.html
CorePreferences/src/au/gov/asd/tac/constellation/preferences/docs/preferences-idx.xml
CorePreferences/src/au/gov/asd/tac/constellation/preferences/docs/preferences-map.xml
CorePreferences/src/au/gov/asd/tac/constellation/preferences/docs/preferences-toc.xml

Discovered that the links to the help pages of some of the preferences were broken. This ended up being due to a missing quotation mark in the map file. While I was at it, I also changed some of the text from Font to Application Font just to align with the what the preference tab is called
Bug fix
People can see help pages

fixed broken help page links

---

CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationFontOptionsPanelController.java
CoreSecurity/src/au/gov/asd/tac/constellation/security/proxy/ProxyOptionsPanelController.java

In the Constellation Options Menu there were typos that were stopping the Application Font and Proxy tabs' help documentation from being opened with the help button.
Allows users to open the related help documentation for these options tabs. 
#1065

Fixed typos in Help Documentation not opening from Options Menu

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectAllPlugin.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

Updated the Data Access View Select All Plugin to select both vertices and transactions when used. 
N/A
The description of the Select All Plugin stats that it will select everything on the current graph which would indicate it would select vertices and transactions. Updated the functionality to match the description. 
None realised
#1025

Update DAV Select All Plugin to include Transactions

---

UNIT_TEST_GUIDELINES.md

Added some unit testing guidelines. I don't by any means claim to be an expert on writing unit tests but this what I've learned to be helpful when writing unit tests for Constellation. 
It's helpful to have a standard to follow for unit tests which in turn helps improve consistency across unit tests.
It's helpful to have a standard to follow for unit tests which in turn helps improve consistency across unit tests.
If not maintained, these could get out-of-date

Unit test guidelines

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java

Removed all mentions of the options button from the Analytic View as it is not currented implemented and all features related to an options button are listed as to dos in the code which may not ever get implemented.
N/A
Stops users from being confused by an options buttons that is not functional.
None realised
#197

Remove Options Button from Analytic View

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/MissingTypeRule.java
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/UnknownTypeRule.java
CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPaneNGTest.java

Updated the Missing Type Quality Control Rule to include blank types such as "" and " ".
N/A
Allows for blank and empty types to be identified as Missing types.
None realised 
Creating graphs with types equal to "" and " ", seeing that they are correctly identified as missing types. 
#1050

Updated Missing Type QC Rule to include Blank Types

---

CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationFontOptionsPanel.form
CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationFontOptionsPanel.java
CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationFontPreferenceKeys.java

The font size is now able to be lowered to 8. Previously it was unable to go below a font size of 12.
Also fixed the font size option default from displaying as 14 when Constellation is first opened. 
N/A
Allows the users to have more control over the size of the font.
None realised
#1099

Update Minimum Application Font Size

---

CHANGELOG.md
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewTopComponent.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

User Notes now store which nodes and transactions were selected when the note was created if the user chooses to apply the note to the current graph selection. 
Also added the ability for users to change the selection for a specific note from the edit dialog. 3 radio buttons have been added to the bottom of the edit dialog window where the user is able to choose to keep the original selection, add what is currently selected on the graph to the note selection, or remove what is currently selected on the graph from the note selection. 
If the note was applied to the entire graph and the user then edits the note and adds nodes and/or transactions to the selection then the note will no longer be applied to the entire graph and only to those nodes/transactions. Or, if the user were to remove …

Create Link between Notes to Nodes and Transactions 

---

CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/TransactionGraphLabelsEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/VertexGraphLabelsEditorFactory.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/schema/SchemaFactory.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SphereGraphBuilderPlugin.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

Changed the default node and transaction label colour to white as it is easier to see on the black graph background.
None realised
Makes the nodes and transactions labels easier to read by default.
None realised
Created both nodes and transactions to check the label colour had changed to white. 
Checked that the sphere graph builder also has updated to use white labels for nodes and transactions.
#1120

Change Default Label Colour to White

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/advanced/FindRule.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/gui/FindCriteriaPanel.java

Cleaned up some possible null pointers which were identified in the Conversation View and Find View.
While cleaning up the find view ones, I discovered there were some functions not being used and didn't seem necessary so I removed those while I was at it
Bug fix
Less exceptions
Nil

Random Null Pointer Fixes

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/experimental/TestParametersPluginNGTest.java

Created a test class and some unit tests for the methods.
As this is an experimental plugin I have not tested to 100%. I've attempted to get the main functionality tested and a few tests of key parameters.
I did not execute the plugin with the pluginexecution rather tested each method similar to how `MergeTransactionsNGTest.java` does.
Applicable tickets:
#413

✅ Test TestParametersPlugin.java

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPluginNGTest.java

A first pass for the WorkflowQueryPlugin. Based on what is not covered like the exceptions section in the `execute` method.
#413

Simple test for the WorkflowQueryPlugin

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessPluginCoreType.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessPluginCoreTypeNGTest.java

Added a unit test for `DataAccessPluginCoreType`
Unit testing good

DataAccessPluginCoreType Unit Test

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPlugin.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreQueryPlugin.java

Restored some behaviour around arrangements that was removed when freeze graph was removed. Now mimics the behaviour of when a graph was frozen (rather than not)
Edits Core code
No surprise arrangements happening without the user knowing

restored some behaviour removed when freeze graph was removed

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessPluginTypeNGTest.java

Added unit tests for `DataAccessPluginType`
Unit tests for class in Core

DataAccessPluginType Unit tests

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectAllPlugin.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectAllPluginNGTest.java

I've added a way for the plugin to let the user know that the attribute does  not exist. 
This is also reflected in the unit tests.
Related ticket:
#413

select all plugin unit tests

---

CoreDependencies/nbproject/project.xml
CoreDependencies/src/ivy.xml

* Upgrade Mockito to the latest stable version
* Remove duplicate entries and minor cleanup
* Upgraded libraries to the latest stable version
There are several PRs pending and I would like everyone to merge with `master` after this is merged to make sure we don't get the duplicate `mockito-inline` entries again.

Upgrade and cleanup of ivy.xml

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java

Added unit tests for MergeNodesByLocation class.
I came up with a random number for the Threshold, such that it fulfill the if conditions. Let me know if we need to use a more realistic number.

Unit tests for MergeNodesByLocation class

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPreferencesNGTest.java

Added unit tests for `DataAccessPreferences`.
Improves code coverage.

`DataAccessPreferences` Tests

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByTypeNGTest.java

Added unit tests for MergeNodesByType.java
#413

Unit tests for MergeNodesByType.java

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessStateIoProviderNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessStateNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessUtilitiesNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/resources/dataAccessStateRead.json
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/resources/dataAccessStateWrite.json

Added Unit Tests for the data access classes.
Testing of the core
More test coverage

Data Access State Unit Tests

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/RemoveNodesPlugin.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/RemoveNodesPluginNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/RemoveUnusedAttributesPluginNGTest.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java

Wrote some unit tests for `RemoveNodesPlugin`. I encountered some typos as well a long the way so I fixed those up as well
Testing Core Class
#413

RemoveNodes Unit Tests

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractTypesFromTextPluginNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPluginNGTest.java

Added unit tests for ExtractTypesFromTextPlugin.
Also added additional tests for ExtractWordsFromTextPlugin
Unit testing Core

Unit Tests for ExtractTypes and ExtractWords Plugins

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/FilterPlugin.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/FilterPluginNGTest.java

A basic test to cover the abstract `FilterPlugin` class.
#413

Add basic testing for the abstract FilterPlugin class

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/QueryNameValidatorNGTest.java

Testing Query Name Validator
Note that the `verify` in the second test was used as a way to cover the last `return` statement so this should be 100% covered.
#413

Testing Query Name Validator

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreDropper.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreDropperNGTest.java

* Added unit testing for some parts of RecordStoreDropper using mockito
* Minor code formatting updated
#413

Added testing for RecordStoreDropper

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreQueryPlugin.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreQueryPluginNGTest.java

* Reviewed and updated unit testing for the RecordStooreQueryPlugin
* Minor updates to the class to resolve some SonarQube warnings
Testing could have been added for the `read`, `query` and `edit` methods separately but there was a lot of dependencies and the same lines of code being run multiple times I felt that putting them into 1 test was better. For instance, you can't run the `query` method without running `read` because `read` is needed to initialise some of the class.
I tried to use Mockito for the 2 `RecordStoreValidator` instances I had to make but I was not able to figure out how to create 2 different types of classes that extend `RecordStoreValidator`. This was required because the class is used to determine what validators are removed.
#413

Added testing for RecordStoreQueryPlugin

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/state/DataAccessPreferenceKeys.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/state/DataAccessPreferenceKeysNGTest.java

Adds test cases for preference keys. 
Found small improvements to make, like actually setting the previous save directory to the previous saved, rather than duplicating the same directory.
Also added a check to make sure that the saved preference was a directory and not a file before saving it to preferences.
Switched usage of "" to StringUtils.EMPTY for consistency.
NOTE: Some tests contain duplicated code as I had trouble mocking two static methods of the same class. To get around this, I mocked only the internals of each static method and this worked perfect.

✅  Test DataAccessPreferenceKeys

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeTransactionsNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeTransactionsPluginNGTest.java

Updated and added more unit tests for MergeTransactionsPlugin and MergeTransactionType.
Testing Core Classes
More unit tests in core

Updated Unit Tests for MergeTransactions

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesPlugin.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesBySuffixNGTest.java

Add unit tests for MergeNodesBySuffix class

Unit tests for MergeNodesBySuffix class

---

CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/MarkerCache.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/csv/SmartCSVWriter.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/datastructure/ObjectCache.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SeparatorConstants.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/StringUtilities.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/csv/SmartCSVWriterNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/datastructure/ObjectCacheNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/text/StringUtilitiesNGTest.java

Filled in some coverage gaps in the core utils module. Fixed some sonar smells once the tests were in place.
Improves code coverage

Core Util Tests

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/UnknownTypeRule.java
CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/IdentifierInconsistentWithTypeRuleNGTest.java
CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/rules/UnknownTypeRuleNGTest.java

Adds tests for the quality control rules with missing unit tests

✅ Test quality control rules

---

CorePluginFramework/test/unit/src/au/gov/asd/tac/constellation/plugins/parameters/types/BooleanParameterTypeNGTest.java

Added some testing of the boolean parameter type
No issues found with the current implementation.

✅ Test boolean parameter type

---

CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/shortcut/DeselectAllLayersPlugin.java
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/shortcut/EnableLayerPlugin.java
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/shortcut/NewLayerPlugin.java
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/utilities/UpdateElementBitmaskPlugin.java
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/utilities/UpdateLayerSelectionPlugin.java

I've refactored some Layers view plugins for readability

add tags for layers view

---

CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/AddModeWelcomePlugin.java
CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/DelimitedFileWelcomePlugin.java
CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/JDBCImportWelcomePlugin.java
CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/SelectionModeWelcomePlugin.java
CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/SphereGraphWelcomePlugin.java

Updated tags for the WelcomeView plugins.
Updated text for File and Database importer buttons.
#1126

Update Tags for WelcomeView Plugins

---

CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/plugins/CompleteSchemaPlugin.java

Updated tags for the plugins in CoreVisualSchema.

Update plugin tags in VisualSchema

---

CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/plugins/CreateTransactionTypePlugin.java
CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/plugins/CreateVertexTypePlugin.java

Add tags for core analytic schema

Add tags for core analytic schema

---

CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/LabelDropper.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/ShowInAttributeEditorContextMenu.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/operations/AttributeValueEditOperation.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/operations/CreateAttributeEditOperation.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/operations/ModifyAttributeEditOperation.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/operations/PrimaryKeyEditOperation.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/operations/UpdateTimeZonePlugin.java

Tags for core attribute editor

Tagging for core attribute editor

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find/BasicFindPlugin.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/ReplacePlugin.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/advanced/FindStatePlugin.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/advanced/GraphAttributePlugin.java

tagging core find view

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/admin/DevOpsNotificationPlugin.java
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/browser/OpenInBrowserPlugin.java
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/compare/CompareGraphPlugin.java
CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/email/SendToEmailClientPlugin.java

Nothing interesting to note, just adding tags. Please review the tags as I personally feel like these are utility style plugins

Add tags for core functionality

---

CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelineSelectionPlugin.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/clustering/ClusteringManager.java

Updated tags for the plugins in CoreTimelineView.

Updated tags for plugins in TimelineView

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewController.java

Updated tags for NotesView plugins.
N/A
N/A
N/A
N/A
N/A
#1126

Update tags for NotesView plugins

---

CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/OpenFilePlugin.java

Refactored plugin to use read instead of getting a graph write lock

Tagging for code graph file

---

CoreTesting/src/au/gov/asd/tac/constellation/testing/FiveSecondReadLockPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/NullPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/PluginExceptionPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/SynchronizerPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/TestNotificationsPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/TestParameterBuildingPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/CompleteGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/DnaGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/GraphConstructionDemoAction.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/IconGraphBuilderAction.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/ImageGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/PreferentialAttachmentGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SleepEditPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SleepReadPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SmallWorldGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SphereGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/StructuredGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SudokuGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/jdbc/ExportToJdbcPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/jdbc/ImportFromJdbcPlugin.java

Add tags to core testing

---

CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/state/NamedSelectionStatePlugin.java
CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/utilities/NamedSelectionEditorPlugin.java

Add tags for core named selection view

Add tags for core named selection view

---

CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTopComponent.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/plugins/CopyCustomMarkersToGraphPlugin.java

Update to plugin tags in CoreMapView.

Update plugin tags for MapView

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewController.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/ChangeSelectionPlugin.java

Updated tags for CoreNotesView plugins.
N/A
N/A
N/A
N/A
N/A
#1126

Update tags for CoreNotesView plugins

---

CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/HashmodAction.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/perspectives/PerspectiveBookmarkTopComponent.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/planes/PlaneManagerTopComponent.java

Refactor of anonymous plugins and tagging. Most of these plugins are tagged as VIEW as they change the camera or are camera related (perspective bookmarks)

Tagging core graph utilities

---

CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/templates/LoadTemplatePlugin.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/templates/ManageTemplatesPlugin.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/templates/SaveTemplatePlugin.java

Add tagging for core graph node.

add tagging for core graph node

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/ScatterChartPane.java
CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/ScatterOptionsPane.java
CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/ScatterPlotTopComponent.java
CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/state/ScatterPlotStateWriter.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/AddRecordStore.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/SetGraphValues.java

Added plugin tags to plugins in quality control view, scatter plot view, and web server.
tagging core plugins
Better filtering in notes view and plugin reporter

Quality Control View, Scatter Plot, Web Server Plugin tags

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/chinesewhispers/ChineseWhispersAction.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/chinesewhispers/ChineseWhispersPlugin.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/InfoMapAction.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/InfoMapGeneralAction.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/InfoMapPlugin.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/KTrussAction.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/KTrussControllerTopComponent.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/NestedKTrussDisplayPanel.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/paths/DirectedShortestPathsPlugin.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/paths/ShortestPaths2Plugin.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/paths/ShortestPathsPlugin.java
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/tree/SpanningTreePlugin.java

Add tags to core algorithm plugins

Add tags to core algorithm plugins

---

CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/TypeDropper.java

Add tags to Core Schema View

---

CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/ScriptingExecutePlugin.java
CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/ScriptingViewPane.java

Add tags for core scripting view

Add tags for core scripting view

---

CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/dragdrop/ImageIconDropper.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/blaze/AddCustomBlazePlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/blaze/DeSelectBlazesPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/blaze/RemoveBlazePlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/blaze/SelectBlazesPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/blaze/UpdateBlazeSizeOpacityPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/dim/DimAllPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/dim/DimSelectedPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/dim/DimUnselectedPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/dim/SelectDimmedPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/dim/SelectUndimmedPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/dim/UndimAllPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/dim/UndimSelectedPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/dim/UndimUnselectedPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/hop/HopOutPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/merge/PermanentMergePlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/ChangeSelectionPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/DeselectAllPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/DeselectTransactionsPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/DeselectVerticesPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/InvertSelectionPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/SelectAllPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/structure/SelectBackbonePlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/structure/SelectHalfHopInducedSubgraphPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/structure/SelectLoopsPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/structure/SelectOneHopInducedSubgraphPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/structure/SelectPendantsPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/structure/SelectSingletonsPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/structure/SelectSinksPlugin.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/structure/SelectSourcesPlugin.java

Add tags for Core Visual Graph

Add tags for Core Visual Graph

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilities.java
CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/TableViewPreferencesIOUtilitiesNGTest.java
CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/resources/transaction-preferences.json
CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/io/resources/vertex-preferences.json

Added unit tests for the table view IO package.
Tests are awesome
Improve code coverage.

Table View IO Tests

---

CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/HeadingPaneNGTest.java

@Auriga2 Please review this and see if you feel it would benefit from being added to your unit tests in #1217

Add test listener to test triggering of listeners

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/dragdrop/FileDropper.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/dragdrop/JsonDropper.java

Added static classes with plugin Tags to anonymous plugins in the Core Import Export Plugins module
https://github.com/constellation-app/constellation/issues/1126

Adding Tags to plugins in Core Import Export

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/HeadingPane.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/HeadingPaneNGTest.java

Unit tests for `HeadingPane` class.
TODO: Test of `validityChanged` method when the `DataSourceTitledPane` is `QueryEnabled`. This is tricky because `HeadingPane` is creating the List of new `DataSourceTitledPane`s in the constructor. This is what I tried, with no luck, if I ever have to try again.
```
//    @Test
//    public void testHierarchicalUpdate_paneIsQueryEnabled() {
//        System.out.println("testHierarchicalUpdate_paneIsQueryEnabled");
//
//        DataSourceTitledPane dataSourceTitledPane = mock(DataSourceTitledPane.class);
//        Iterator<DataSourceTitledPane> itr = mock(Iterator.class);
//        when(itr.hasNext()).thenReturn(true, false);
//        when(itr.next()).thenReturn(dataSourceTitledPane);
// …
```

HeadingPane Unit Tests

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/clipboard/CopyToClipboardAction.java

Simplified `CopyToClipboardAction` following on from comments in https://github.com/constellation-app/constellation/pull/1257#discussion_r693627322

Simplified `CopyToClipboardAction`

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewTopComponent.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/docs/notes-view.html
CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/PluginReporterTopComponent.java
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java
CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/ScatterPlotTopComponent.java
CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/SchemaViewTopComponent.java
CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/ScriptingViewTopComponent.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewTopComponent.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelineTopComponent.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

Moved Notes View to Views menu.
N/A
This is a change to a core view.
The Notes View will be more visible to users.
N/A
N/A
N/A

Move Notes View to Views menu

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/ShowInTableViewContextMenuProvider.java

Fix to the context menu name.
#1273

Fix to a typo with the context menu (#1273)

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find/advanced/SelectFindResultsPlugin.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/DragElementsPlugin.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/PointSelectionPlugin.java

Some plugins were still tagged with SELECTION whereas we've moved to using SELECT. This fixes those tags

Updated Plugin Tag from Selection to Select

---

CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

Fix a broken link to the "introduction" page on "What's New". I've renamed the link to "getting started guide" to match the page it goes to.
#1274

:bug: Correct the introduction link on whats new

---

CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/GraphConstructionDemoAction.java

The graph construction demo had its menu item link commented out an was therefore only available via search. Since nothing appears to be superseding it, this PR is putting it back on the menu
This is already a thing, now it's properly accessible
Easier to access
Maybe some people liked that it was a hidden easter egg?

restored graph construction demo to build graph menu

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/datastructure/IntHashSetNGTest.java

Add unit tests for the IntHashSet class.
Ran the tests.
#413

:white_check_mark: Add tests for IntHashSet

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/camera/BoundingBox.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/camera/BoundingBoxNGTest.java

Add unit tests for the BoundingBox class.
Ran the tests.
#413

:white_check_mark: Add tests for BoundingBox

---

CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/RecentFilesWelcomePage.java

Hopefully fixed an issue where an illegal argument exception was thrown trying to open some graphs from the welcome page. From the digging I was able to do, the issue appears to be the way that the file object is created before trying to open the graph so I've changed it what seems to be used elsewhere (including the Open Recent menu action) and hopefully that should do the trick (it seems to work on the graphs I had that I could open successfully previously but I didn't have any graphs that couldn't experienced this issue so am not sure for those ones). 
Bug fix
Less bugs
#1284

Welcome Page Open Graph bug fix

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersPane.java

A quick fix to preventing buttons in the horizontally aligned parameter dialogs from being chopped off. Below is what the fixed version looks like and it is wider than I like it to be and I can investigate this further later on but for now I would like this to be accepted to help get v2.4 over the line.

Fix to horizontally aligned parameter dialogs

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewTopComponent.java

Separate PR for issue introduced by #1316.
- Graphs notes would carry over from previous graph to new graph.
- This was an unintended result of the notes disappearing bug
- This code should fix the issue of the notes disappearing and should not have notes transfer from one graph to the next
Notes view doesn't function properly without this fix.
Working notes view
There shouldn't be any
Tested the original bug of user created notes disappearing. (The note did not disappear) 
Tested creating a note then creating a new graph.  (The notes did not transfer over )
#1316
#1325 (This issue was fixed here, however this separate PR has been made)

Notes view notes carrying over from graph to graph

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationViewTopComponent.java

:racehorse:  Greatly improved performance
:bug: Resolved a concurrent modification error
The primary fix to resolve was the concurrent modification  error which has been fixed. This PR also fixes a major performance issue in which there was logic error whereby there was a messages x messages going on; i.e the search would get slower the more messages you have.
If there was text entered in the search field and you click on a node with conversations, then this will now update thanks to a change listener I was able to tap into with the `messages` `ObservableList`.
Profiling before the change and you will see the 9,581 invocations...
Profiling after the fix shows the improvements
Lots of tests have been done trying to quickly change selection to reproduce the concurrent modification issue. …

Issue 1271 Conversation View Fixes

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/animation/Animation.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/animation/FlyingAnimation.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/animation/ThrobbingNodeAnimation.java

I have a added a fix for both the Flying animation and the throbbing animation causing crashes with no vertex's on the graph. The solution added:
-  A check in the ThrobNodeAnimation class that ensures there is at least 1 vertex before attempting to start the animation. 
- A check in the FlyingAnimation class to check there is at least 2 vertex's present when calling the Flying animation.
N/A
It avoids the code crashing when:
1: calling an animation with 0 nodes present
2: calling the Flying animation when there is 1 or less nodes.
Avoids users accidently crashing the application.
The Flying animation will not run unless there is 2 nodes present. It will mean the user can not watch a flying animation of 1 node.
Throb animation will not run unless 1 node is present.
I would test each …

fix for flying and throbbing animation crashes

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ConfigurationPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RunPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedIO.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/ImportJDBCIO.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCImportController.java

The File importer now obeys the "files include headers" option when importing and when running the plugin through API. Database Importer now imports all rows when the `Import` button is clicked.
Bug fix
Bug fix
1) Create a CSV file with no header row e.g.:
5,6,7,2009-12-05 23:59:59,2009-12-1
1,1,1,2009-12-15 23:59:59,2009-12-12
a,a,a,2009-12-25 23:59:59,2009-12-31
2) Click File/Import/From File
3) Disable the Files include headers check box and Select the file to import using green + sign
4) Verify the column header are inserted in the preview pane
5) Drag and drop Source Node-Identifier attribute on to the Col1 (And more attributes if you like)
6) import it by clicking `Import` button at the bottom
7) Verify all 4 nodes are drawn on a graph and verify the confirmation pop up message …

Fix the File importer and Database Importer `Import` action.

---

CHANGELOG.md
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCImportController.java

:bug: Fix a bug with the database importer #1326
:art: Minor code clean up and removed an unused return parameter
-   Added some javadoc and minor code clean up. 
-   Removed unused return argument
I tested the database importer using the Chinook Sqlite database and specifically the "Track" table which has more than 100 rows of data
I also tested a random CSV file to make sure there was no errors after changing the method signature
#1326

Fix to Database Importer only importing preview data

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java

Enclosed block of code causing JFX runtime exception in Platform.RunLater to execute on JFX thread.
N/A
Fixes bug for a core view.
Avoids JFX runtime exception.
N/A
N/A
#1313

Enclosed JFX elements in Platform.RunLater()

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

In the `Import from Database` pane the `Connection` drop down list is now properly refreshed as soon as a connection is modified or removed or  a new connection is added.
Better UX
Better UX
1. In Constellation go to Import from DB.
2. In `Manage Connections`-> `Connections` add a new connection .
3. Exit this screen and return to the main Import pane.
4. Check the `Connection` drop down and verify the new connection is there.
5. Repeat with `Modify` and `Remove` actions and verify the connections drop down list is updating properly.
https://github.com/constellation-app/constellation/issues/1327

Import from Database: Refresh Connection drop down list after add, modify and remove

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/camera/Graphics3DUtilitiesNGTest.java

Add unit tests for the Graphics3DUtilities class.
Ran the tests.
#413

:white_check_mark: Add tests for Graphics3DUtilities

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/camera/CameraUtilitiesNGTest.java

Add unit tests for the CameraUtilities class.
Ran the tests.
#413

:white_check_mark: Add tests for CameraUtilities

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/camera/CameraNGTest.java

Add unit tests for the Camera class.
Ran the tests.
#413

:white_check_mark: Add tests for Camera

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/camera/StereoCameraNGTest.java

Add unit tests for the StereoCamera class.
Ran the tests.
#413

:white_check_mark: Add tests for StereoCamera

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessState.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/io/ParameterIOUtilitiesNGTest.java

ParameterIOUtilities Unit test case
For unit testing
To improve code
Performance
Run the unit test

ParameterIOUtilities Unit test

---

CoreImportExportPlugins/nbproject/project.xml
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/ImportJDBCPlugin.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCImportController.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

When imported by any of above importers, the graph view is now reset to the full view to display everything that's been imported.
Better UX
Better UX
Import a big set of data using both of the above importers and verify it resets to the full view to display everything that's been imported.
https://github.com/constellation-app/constellation/issues/1312

Import from File and Import from Database - Reset graph view after importing

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ImportPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCImportPane.java

I would like feedback on this one regarding code from 118 - 135. It appeared to not provide any functionality after deleting as it was tied to the options menu drop down. However I'm not entirely sure if has a lingering effect somewhere else.
Changed the visibility of the options menu items to be more obvious by removing the options menu and placing options menu items straight on the view. (shown below)
All functionality should remain the same, the menu options have just been converted to buttons.
Its easier for the user to see the views functionality.
Easier for users.
- ensured SAVE and LOAD buttons were still triggering the correct pop up
- ensured checking the show attributes check box still triggered showing more attribute options
#1310

increased visibility of import views options

---

CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java
CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/resources/welcome_theme.css

broken branch reproducer for welcome page tooltip error.
1. open constellation 
2. hover over any of the recent file buttons within the welcome view
3. Exception should occur

added tooltip to welcome view recent files

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Matrix44fNGTest.java

Add unit tests for the Matrix44f class.
Ran the tests.
#413

:white_check_mark: Add tests for Matrix44f

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Matrix33fNGTest.java

Add unit tests for the Matrix33f class.
Ran the tests.
#413

:white_check_mark: Add tests for Matrix33f

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Vector3dNGTest.java

Add unit tests for the Vector3d class.
Ran the tests.
#413

:white_check_mark: Add tests for Vector3d

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Vector3fNGTest.java

Add unit tests for the Vector3f class.
Ran the tests.
#413

:white_check_mark: Add tests for Vector3f

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/ImportJDBCPlugin.java

I have removed pop up notification on file import and replaced it with a balloon notification. I have also added the notification to database imports as well.
File Importer:
This displays the exact same message as before but in balloon format.
Database:
It says : imported 18393 rows of data from connection: test (what I named my connection)
I have not added a click for more details. I wanted to wait for feedback first and what ask details I should add to that if I did add that feature. Also how to add a link to a balloon notification.
It achieves the same outcome as the current pop up but does it in a less intrusive way to the user.
It also adds the functionality to the DB connection importer.
UX improvements.
Maybe less obvious for some people??
I ensured the message still posted the …

added balloon notifications to DB and File imports

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

Added prompt text to the jbdc screen.
Automatically selected the first driver in the list if there was one.
Allows users to better understand what should be in each field.
helpful for users
none
#1323

Add prompt text to jdbc add connection

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Vector2d.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Vector2dNGTest.java

Add unit tests for the Vector2d class.
Ran the tests.
#413

:white_check_mark: Add tests for Vector2d

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Vector2fNGTest.java

Add unit tests for the Vector2f class.
Ran the tests.
#413

:white_check_mark: Add tests for Vector2f

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Vector4d.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Vector4dNGTest.java

Add unit tests for the Vector4d class.
Ran the tests.
#413

:white_check_mark: Add tests for Vector4d

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Vector4f.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Vector4fNGTest.java

Add unit tests for the Vector4f class.
Ran the tests.
#413

:white_check_mark: Add tests for Vector4f

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RowFilter.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RunPane.java

The table filter in the Configuration section now correctly filters when the filter text has column headers containing special characters like #,@,$, space etc other than _.
This filter was sometimes not filtering properly in a new Run tab. That has been fixed and now works consistently.
A new search filter without using javax.script CompiledScript with python ScriptEngine.
Better UX
Better UX
- Create a CSV file or edit an existing file to contain column headers with special characters  #,@,$, space except _. (source.Name, sourceTag#, Source Type etc.)
- Click on Import from Delimited file and load that file and confirm the file headers have the special characters in them.
- Click in the filter above the table and enter search query, such as source.Name=="Greg" and verify it searches …

File and Database Importers- Fix the Configuration filter

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIONGTest.java

:green_heart: Fix to JSON IO tests not working on Windows
* Some file streams where not properly closed which has been resolved.

:green_heart: Fix to JSON IO tests not working on Windows

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ConfigurationPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RunPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedSourcePane.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

In the File importer, the table filter in the configuration Run panes and the Attributes filter will now be cleared when all the files are removed.
1. Open Import from file
2. Select a file for importing and watch the data populate on screen
3. Enter search criteria in the Filter in a few Run tabs
4. Enter in a search term into the Attributes section
5. Now I have decided that my data is incorrect so I remove the file using the red button
6. Check all the Filters above and verify they are cleared. 
https://github.com/constellation-app/constellation/issues/1160

Import from File - Clearing the Search filters when all files are removed

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataSourceTitledPane.java

Whilst testing https://github.com/constellation-app/constellation/pull/1392 a NPE was found which was also occurring in `master`
When a plugin has no parameters and is loaded from a template then there
is a NPE error. This has been resolved. The NPE was:
```
Parameter creation for plugin Remove Unused Attributes failed:
java.lang.NullPointerException
at au.gov.asd.tac.constellation.views.dataaccess.panes.DataSourceTitledPane.lambda$createParameters$2(DataSourceTitledPane.java:164)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```
Used a `java.util.logger` instead of using `System.out.printf`
1. In the …

:bug: Fix to data access view load templates

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java

@GammaVel  hopefully this looks a bit better.
As per #1309 notification being to big due to the file path I have removed the path. Now it only displays the file names separated by a comma.
(it says the same file 3 times as its the only one I had. I added it 3 times)
Have all file names on separate lines, however this was not possible due to the notification styles restrictions.
Easier to read.
UX UI
Can't see the full path in the notification. However they are still present in the file importer view.
Ensured all relevant file names were posted
#1309

display file name not full path in balloon notification

---

CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/BinComparator.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

- Added a numeric sort option by label. Label (Number)
- Changed label option to Label (String)
Descending Number
Descending Number
Ascending Number
Ascending String
Allows users to sort their labels by their numeric value if the labels can be converted to a number.
Potential use cases where the labels are numbers and the user would like to sort them in ascending or descending order.
Screen shots provide various different mixes of numbers, strings, number/string combos. These show how it is working.
#861

Histogram view added numeric label sort option

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/DefaultQualityControlAutoButton.java
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/widget/QualityControlAutoButton.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

I have duplicated the buttons and added them to the bottom of the data access view. shown below.
improves users work flow as they work down the page.
UX UI
I ensured that the buttons mimic the ones at the top. They should do the exact same thing however just relocated down the bottom.
#1241

Added go and quality category to the bottom data access view

---

CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/BinComparator.java

Requested at the end of PR #1416 
- Changed Label (String) to Label (Text)
Text is more intuitive for normal users instead of String. 
UI
PR
#1416

changed Label (String) to Label (Text)

---

.github/workflows/greetings.yml

Make it evident that the bot is a bot by mentioning that it is an automated script.

Add text to mention robot nature of actions greeting

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java

Requested by @GammaVel from testing #1290 
Changed notes view delete note pop up header and message. 
Better confirmation message.
PR
#1290

Changed Notes View delete note text and header

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Frustum.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/FrustumNGTest.java

Add unit tests for the Frustum class.
Ran the tests.
#413

:white_check_mark: Add tests for Frustum

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

- Changed "cancel" - "Ok
- Moved "Remove" to left hand side
Drivers Tab
- Changed "cancel" - "Ok
- Moved "Remove" to left hand side (where modify was)
- Moved "Modify" to the right of "Remove"
Connections Tab
- Changed "Test" - "Test Connection" to be more self explanatory of what it does.
Add/Modify connections screen
The screen flows nicer and buttons are more intuitive to what they would be doing.
UX UI
I imagine none
All buttons still work as intended, only visual text was changed
#1322

Rearranged JDBC buttons

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

Changed the promt text of the connection string to better indicate what the user should do.
Easier to understand
UX UI
Issue
#1323
PR
#1387

Changed connection string promt text

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Mathd.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/MathdNGTest.java

Add unit tests for the Mathd class.
Ran the tests.
#413

:white_check_mark: Add tests for Mathd

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Mathf.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/MathfNGTest.java

Add unit tests for the Mathf class.
Ran the tests.
#413

:white_check_mark: Add tests for Mathf

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/FloatArray.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/FloatArrayNGTest.java

Add unit tests for the FloatArray class.
Ran the tests.
#413

:white_check_mark: Add tests for FloatArray

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/font/BidirectionalTextUtilitiesNGTest.java

Add unit tests for the BidirectionalTextUtilities class.
Ran the tests.
#413

:white_check_mark: Add tests for BidirectionalTextUtilities

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/IntArray.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/IntArrayNGTest.java

Add unit tests for the IntArray class.
Ran the tests.
#413

:white_check_mark: Add tests for IntArray

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RowFilter.java

Now the query allows trailing or leading white spaces in the column header. 
Before," Row == 1 " was marking it as incorrect format:
After: 
Better UX
Better UX
1. Open `Import from file` or 'Import from Database` window and add some valid columns in the preview.
2. Type " Row == 1 " with trailing and /or leading while spaces and verify it's not marking it as invalid in red.
3. Repeat with a column name and a valid value, with trailing and /or leading while spaces around the column name, and verify it's not marking it as invalid in red.
https://github.com/constellation-app/constellation/issues/1143

Importers - Fix the Row filter to trim white spaces in the header part of the query

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/PluginParameter.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/SwaggerServlet.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/swagger/constellation.json
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/AddRecordStore.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/RunPlugin.java
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/services/RunPlugins.java

An example value is added in the `Request body` sections of the REST API endpoints below:
`plugins` parameter in `run_plugins` endpoint
`args` parameter in `run_plugin` endpoint
`data` parameter in `add_recordstore` endpoint
Better UX
Better UX
1. Open Swagger (Run constellation and Tools->Start Rest Server then Display Rest Server Documentation)
2. Check above endpoints
Before:
After:
https://github.com/constellation-app/constellation/issues/665

Add the 'Example Value' in the Rest API 'Request body'

---

CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/resources/whatsnew.css
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

As per @GammaVel's suggestion, I've updated the Whats New Page layouy by centering the text and adding some padding to the sides
Better layout
Better layout
#1083

updated whatsnew layout

---

.githubutilities/run-tests.sh

Verbose logging to help with finding out when unit tests fail.
Unit tests can take longer to run and there is a lot more logs to go through.
https://github.com/constellation-app/constellation/issues/1468

:white_check_mark: Verbose logging during unit testing

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RowFilter.java

Fix the row filter to work on the last column
Bug fix
Bug fix
1. Click on Import from Delimited file
2. Load a file containing a special character in the last column header such as `source.Name`
3. Click in the search field above the preview table and enter a search query for the last column, such as source.Name=="Greg" and confirm it's working properly, without highlighting in red.
https://github.com/constellation-app/constellation/issues/1143

Fix the row filter to work on the last column

---

CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/resources/schema-view.css

Have moved away from the temp solution for the schema view css  my making the needed minor adjustments to more align it with other filter search bars in other parts of the application while also solving the issue that the temp solution originally aimed to resolve.
Better style alignment across the application
More familiar style
#841

Schema View Filter css

---

CHECKLIST.md
PULL_REQUEST_TEMPLATE.md

The most important changes are in 28111aaf0955546f1622163abd2c8f2a5134c746 and the rest are formatting changes.
Also have a look at the section in "Unit testing changes in your PR" making note of a minimum of 80% code coverage required for new code.
This is a chance to also make a call on what should be part of the PR process going forward.

Checklist Review

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java

Some updates based on testing #958 which should address the divide by 0 raised by @aldebaran30701 and I found a bug with seeing "1 of 0" results.
#958

:bug: Fixed a couple of bugs with the conversation search

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/PreviousViewAction.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/PreviousViewPlugin.java
CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/PreviousViewPluginNGTest.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/camera/BoundingBox.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/camera/Camera.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Frame.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/graphics/Vector3f.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/camera/BoundingBoxNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/camera/CameraNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/FrameNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/graphics/Vector3fNGTest.java

The previous view action within the experimental -> tools menu did not work, as it was setting the old camera to the new camera meaning nothing would occur. 
This change fixes that by using the other utility method and also changes the name to better reflect its action based on #1301 
Actually works now
N/A
moving the camera and then ensuring that it resets to that last action.
#1301

fix previous view plugin

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/JNumberedTextArea.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/JNumberedTextAreaNGTest.java

Unit tests for JNumberedTextArea
N/A
All tests pass

Unit tests for JNumberedTextArea

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/clipboard/ConstellationClipboardOwnerNGTest.java

Added a unit test for `ConstellationClipboardOwner`. There wasn't really much to unit test here...
More unit tests is better
#413

ConstellationClipboardOwner Unit tests

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/geospatial/Distance.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/geospatial/DistanceNGTest.java

Updated the unit tests for the Distance class.
More unit tests is better
#413

Distance unit tests

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/temporal/TemporalFormatting.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/temporal/TimeZoneUtilities.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/timer/Timer.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/temporal/TemporalFormattingNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/temporal/TimeZoneUtilitiesNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/timer/TimerNGTest.java

Added unit tests for the `TemporalFormatting`, `TimeZoneUtilities`, and `Timer` classes. I also discovered a small bug in `TemporalFormatting` so fixed that as part of this PR.
Unit tests are good
#413

TemporalFormatting, TimeZoneUtilities, Timer Unit Tests

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/temporal/TimeZoneUtilitiesNGTest.java

There was a unit test in `TemporalFormatting` that was throwing a Null Pointer on occasion. As it turns out, the issue seemed to be a mocked static in one of the unit tests in `TimeZoneUtilities` which may have been running in parallel (I don't say that with any confidence). 
Upon further inspection, I realised that the mocked static wasn't needed as the call being mocked wasn't affecting the result so I removed it which seemed to resolve the issue
Fix broken unit tests
Less broken tests

fixed issue with unit test

---

CoreHelp/src/au/gov/asd/tac/constellation/help/ConstellationHelpDisplayer.java
CoreHelp/src/au/gov/asd/tac/constellation/help/CoreHelpHelpProvider.java
CoreHelp/src/au/gov/asd/tac/constellation/help/HelpPageProvider.java
CoreHelp/src/au/gov/asd/tac/constellation/help/HelpServlet.java
CoreHelp/src/au/gov/asd/tac/constellation/help/HelpWebServer.java
CoreHelp/src/au/gov/asd/tac/constellation/help/preferences/HelpOptionsPanel.java
CoreHelp/src/au/gov/asd/tac/constellation/help/preferences/HelpOptionsPanelController.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/Generator.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/HelpMapper.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TOCGenerator.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TOCItem.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TOCParser.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TreeNode.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/HelpServletNGTest.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/preferences/HelpOptionsPanelControllerNGTest.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/utilities/GeneratorNGTest.java

Clean up of code smells in the CoreHelp module.
Removing bugs and code smells from CoreHelp.
Removing bugs and code smells from CoreHelp.
#1022

Sonar Clean up in CoreHelp

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/JSingleChoiceComboBoxMenu.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/JSingleChoiceComboBoxMenuNGTest.java

Unit tests for `JSingleChoiceComboBoxMenu` class
More tests
N/A
All tests pass
#413

Unit tests for JSingleChoiceComboBoxMenu class

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/JDropDownMenu.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/JDropDownMenuNGTest.java

Unit tests fo JDropDownMenu class
All tests pass
#413

Unit tests fo JDropDownMenu class

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/ip/IpAddressUtilities.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/memory/MemoryManager.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/ip/IpAddressUtilitiesNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/memory/MemoryManagerNGTest.java

Added units test for `MemoryManager` and an extra one for `IpAddressUtilities` to address a missing use case.
More unit tests is good
#413

MemoryManager and IpAddressUtilities Unit Tests

---

CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewHelpProvider.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTileRenderer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTopComponent.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/features/ConstellationAbstractFeature.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/layers/AbstractHeatmapLayer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/layers/AbstractPathsLayer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/layers/DayNightLayer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/layers/MapLayer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/layers/PointMarkerErrorLayer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/layers/ThiessenPolygonsLayer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationAbstractMarker.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationClusterMarker.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationMarkerFactory.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationPointMarker.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationPolygonMarker.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/InfoOverlay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/MapOverlay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/OverviewOverlay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/ToolsOverlay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/plugins/CopyCustomMarkersToGraphPlugin.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/providers/DefaultMapProvider.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/providers/MapProvider.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/DefaultMarkerCache.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/FeatureUtilities.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/MarkerCache.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/MarkerUtilities.java

Review all code smells within Map View.
The notable smells I've been leaving:
- Comments on classes at least 25% density.
The rest I've done my best to keep readability and code smells in mind.
I re-ran the 6 tests within the test suite and there appears to be no issues.

🧹 Code cleanup of MapView Module

---

CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/ConstellationHelpDisplayerNGTest.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/utilities/GeneratorNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/JDropDownMenuNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/JSingleChoiceComboBoxMenuNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/icon/DefaultCustomIconProviderNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/icon/IconManagerNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/tooltip/handlers/TooltipMouseEnteredHandlerNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/tooltip/handlers/TooltipMouseEnteredHyperlinkHandlerNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/tooltip/handlers/TooltipMouseEnteredTextAreaHandlerNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/tooltip/handlers/TooltipMouseMovedHandlerNGTest.java

* Given the recent random issues with unit tests failing, I went through all calls the MockedStatic and made sure they were all
in a try with resource or was being closed in tearDownMethods.
Thankfully none were found though I did find some instances where we
could reduce the nested try's

:memo: Reviewed MockedStatic Unit Tests

---

CHANGELOG.md
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationContribution.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationContributionProvider.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationBackgroundProvider.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationColorProvider.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/SelectableLabel.java

Clean up of code smells in the CoreConversationView module.
Also removed unused code in SelectableLabel.
Removing bugs and code smells in CoreConversationView.
Removing bugs and code smells in CoreConversationView.
#1022

Sonar Clean up in CoreConversationView

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

Added validation for the connection dialog, making sure that the connection name, driver, and connection string are all present.  A error is displayed if they try to add, save, or test the new connection without the required fields.
For example if you didn't add anything for the name or connection string you'd get the following error message.
The text fields also turn red if they lose focus and are empty.
None considered
This helps the user determine what are required fields and helps with additional information that may help with filling out those fields.  
Better messaging to the user as well as validation.   
- Add the import from database dialog from File > Import > From Database
- Click 'Manage connections' in the top right hand corner
- …

Add validation to the connection params

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/JMultiChoiceComboBoxMenu.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/JMultiChoiceComboBoxMenuNGTest.java

Unit tests for `JMultiChoiceComboBoxMenu` class
All tests pass
#413

Unit tests for JMultiChoiceComboBoxMenu class

---

CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/docs/attribute-editor.md
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/docs/expressions-framework.md
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/docs/import-from-database.md
CorePreferences/src/au/gov/asd/tac/constellation/preferences/docs/application-preferences.md

Some help pages had angle brackets with incorrect syntax 
Core function help pages 
To display correct text vales  
Compare the pages before and after the changes

Fixes to angle brackets in markdown

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/JDropDownMenu.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/JSingleChoiceComboBoxMenu.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/JDropDownMenuNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/JSingleChoiceComboBoxMenuNGTest.java

Fixed some tests and added more tests for JSingleChoiceComboBoxMenu and JDropDownMenu which involved a bit of code refactoring.
More coverage
All tests pass

More tests for JSingleChoiceComboBoxMenu and JDropDownMenu

---

CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewPane.java

The layers view help button wasn't displaying on the pane when you opened the graph. This was due to the help button object being added to multiple nodes which isn't possible since each node (including the help node) can only have one parent (and so the parent changed once the help button was added as a child the 2nd time).
To fix this I've extracted the help button creation into a separate function and just called that function when we wanted to add a help button. This results in a new help button being created for each place it is needed in the view
Fixes bug in Core
bug fix
#1581

fixed issue with layers view help button not displaying

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/ExportMenu.java
CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview/components/ExportMenuNGTest.java

After the refactor made to table view code, the export options were no longer working. The issue ended up being due to code being moved off the FX thread that needed to run in there. It also wasn't applying the file extension as intended and so I re-inserted some code for it that was omitted during the code refactor
Bug fix
Bug fix
#1574

Table view export fix

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java

An exception was being by the notes view when one of the graph builders was opened when the notes view was closed. This was due to the notes view trying to update the UI while it was closed. The cause was the lack of a check to make sure the notes view was actually open before trying to make the GUI changes.
Bug fix
bug fix
Followed reproducer from original ticket
#1583

Notes View Update Exception

---

CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/Generator.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/utilities/GeneratorNGTest.java

Remove the early exit condition from the help loader so the release versions can auto generate the toc file based on the picked up service providers

remove early exit case for loading help documents in release versions

---

.github/workflows/build-and-scan.yml
.githubutilities/run-tests.sh
PULL_REQUEST_TEMPLATE.md

Tested on CI and should pick up when a label is on a PR and parse the -verbose tag into the ant test runner.
Prerequisites of this to work is to be merged into master, and a label should be present on a branch that has a PR up. Simply adding the label and pushing a commit should re-trigger the running of tests in verbose.
#1468

Add verbose test logging by PR label

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/CircTreeArranger.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/MdsArranger.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPlugin.java
CoreHelp/src/au/gov/asd/tac/constellation/help/ConstellationHelpDisplayer.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/HelpSearchProvider.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TOCGenerator.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TreeNode.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCConnection.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCDriver.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/SQLiteDBManager.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformRenderable.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTopComponent.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GraphRenderable.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/Batch.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/NumberInputPane.java
CorePreferences/src/au/gov/asd/tac/constellation/preferences/GraphOptionsPanel.java
CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/graph/SGraph.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/NotifyDisplayer.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccess.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/utilities/BlazeUtilities.java

- Refactor the code to eliminate nested switch
- Exceptions should be either logged or rethrown but not both
- Open curly brace locate at the end of a line
- Local variables should not be declared and then immediately returned or thrown
- Remaining: static base class members should not be accessed via derived types (Except Map.Entry)
- String literals should not be duplicated
- New:"String#replace" should be preferred to "String#replaceAll"
More sonar code smell fixes
More sonar code smell fixes
https://github.com/constellation-app/constellation/issues/1022

Sonar clean up

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

This change adds text to the reset button based on if the preference has been changed from its default value.
The reset buttons only update once the preference has been changed via clicking the ok button and relaunching the dialog.
Before:
After:
https://github.com/constellation-app/constellation/issues/1140

Add text to respresent that a quality category is changed from the default

---

CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java

Add full path to the tooltip on recent files. See image for new tooltip
https://github.com/constellation-app/constellation/issues/1537

Add full path to tooltip on welcome view recent graphs

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/Table.java

There's a potential for an array out of bounds exception to occur in the table view. This is due to an attribute id being passed through to a function which uses that id as an index to retrieve from an array. If the attribute doesn't exist, that index is -1107 (which throws the exception).
This fix adds a check to ensure the attribute exists before running the subsequent code. Similar such checks are done throughout the codebase so this is just an instance where the check was forgotten.
Fixes possible bug
Less bugs

added missing attribute check to table view

---

CHANGELOG.md
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RunPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/ImportJDBCPlugin.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

1-4 and 6th issues in the related issue https://github.com/constellation-app/constellation/issues/1577 are fixed in here.
Better UX
Better UX
n/a
As elaborated in the related ticket https://github.com/constellation-app/constellation/issues/1577
https://github.com/constellation-app/constellation/issues/1577

Fix importer inconsistencies and bug fixes

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.form
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java

Bold and consistent with the Ktruss tool. Pointer changed to a hand also.
These changes mirror the ones performed in #1441 
Hierarchical:
KTruss:
#1461

Change fonts to align with KTruss in Hierarchical Cluster

---

.github/workflows/nightly-build.yml

This GitHub Actions script will run a CRON job once every day at 20:00 UTC or 8pm UTC. 
The job will also run when there is a prerelease, or release.
This job runs off code within the master branch from Constellation, Constellation-applications and Constellation-adaptors.
The build version is not altered during this process. 
The build completes successfully and uploads three artifacts. [Linux build, MacOSX build, Windows build]
See the following link for an example of the build on my fork: https://github.com/aldebaran30701/constellation/actions/runs/1571087044
N/A
Helps streamline processes in the build pipeline
As above
N/A
Tested on local fork
#515

Add nightly build script to CI

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/json/JsonUtilities.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/json/JsonUtilitiesNGTest.java

Adding unit tests for CoreUtilities - JsonUtilities.java
Nil
Unit tests + several Sonarqube fixes to unit under test.
Testing
Nil
Unit tests pass

Unit testing JsonUtilities

---

CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java

Updated the width of the property value text in the Histogram view to match the width of the text, rather than having some of the text cut off when longer labels are used. 
None realised 
Stops he property value heading text and the text for the bin labels from being cut off.
None realised 
#1600

Update width of Property Value text on Histogram 

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/rest/Response.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/rest/ResponseNGTest.java

Added unit tests for the `Response` class
More unit tests is good
More tests
#413

Response unit tests

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/html/MultiPartNGTest.java

Added unit tests for `MultiPart`
More unit tests is good
More tests
#413

MultiPart Unit Tests

---

CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/BinCollection.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
CoreHistogramView/test/unit/src/au/gov/asd/tac/constellation/views/histogram/BinCollectionNGTest.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

Added a selected count to the histogram. First figure is the amount selected, the second is the total amount of bins.

Add selected count to histogram display

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/UtilitiesHelpProviderNGTest.java

Added unit tests for `UtilitiesHelpProvider`
more unit tests is good
#413

UtilitiesHelpProvider unit tests

---

CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/BlazeAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/CameraAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/ColorAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/ConnectionModeAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/DecoratorsAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/DrawFlagsAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/LineStyleAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/TransactionGraphLabelsAttributeDescription.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/VertexGraphLabelsAttributeDescription.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/BlazeAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/CameraAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/ColorAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/ConnectionModeAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/DecoratorsAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/DrawFlagsAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/IconAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/LayerNameAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/LineStyleAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/TransactionGraphLabelsAttributeDescriptionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/VertexGraphLabelsAttributeDescriptionNGTest.java

Wrote unit tests for the `*AttributeDescription` classes in Core Visual Schema. The exception is `PlaneStateAttributeDescription` which I determined didn't have anything of value to unit test (just contains a constructor that calls super)
unit tests good
#413

Visual Schema Attribute Description unit tests

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/image/GaussianBlur.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/image/GaussianBlurNGTest.java

Added some unit tests for `GaussianBlur`. There were some bugs that were found during the process of writing them as well which have been fixed.
It is worth noting that I haven't included a unit test covering the fastest box blur (and functions that were used there), I identified an issue where an ArrayOutOfBounds exception is caused (see #1616) and while I can identify the source of the issue, I'm unable to figure out a best solution. Once that is resolved, unit tests for that can be added (they would be included here but I was more interested in getting these other ones through without issues)
more unit tests is good
#413

GaussianBlur unit tests

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/log/LogViewerSupport.java

Added the local time to logs as they are displayed in the Constellation output window. 
Allows for the user to check when plugins were run using the information in the logs.
#1058

Added DateTime Information to Logs

---

CorePreferences/src/au/gov/asd/tac/constellation/preferences/GraphPreferenceKeys.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/utilities/BlazeUtilities.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/utilities/BlazeUtilitiesNGTest.java

Added unit tests for `BlazeUtilities`. Note that there isn't one for the `colorDialog` function due to Constellation presently not making use of any libraries that can effectively unit test swing dialogs
Unit tests = good
#413

BlazeUtilities unit tests

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/DefaultCustomIconProvider.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/icon/IconManager.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/icon/IconManagerNGTest.java

There were a couple of issues with the tests for IconManager which I have cleaned up:
- one of the tests relied on a lookup returning a particular answer which can't be guaranteed if people create their own implementations of interfaces. I couldn't find a better way to write the test so omitted it
- one test actually had some incorrect expected values so I fixed those up
- some tests using a mock static didn't ensure that other functions called from the class called the actual method which was causing issues. Fixed this as well by making the real method call the default (unless explicitly mentioned otherwise)
- there was a also a lack of cleanup after …

IconManager test fixes

---

CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/concept/VisualConceptNGTest.java

Added some unit tests for `VisualConcept`. Since there were no regex's or similar to test for attributes in the concept, the only tests included are just to test whether attributes have been added correctly.
more unit tests = good
#413 #337

VisualConcept unit tests

---

CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/ColorAttributeInteraction.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/ConnectionModeAttributeInteraction.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/DrawFlagsModeAttributeInteraction.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/IconAttributeInteraction.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/LineStyleAttributeInteraction.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/TransactionGraphLabelsAttributeInteraction.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/VertexGraphLabelsAttributeInteraction.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/BlazeAttributeInteractionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/ColorAttributeInteractionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/ConnectionModeAttributeInteractionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/DecoratorsAttributeInteractionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/DrawFlagsModeAttributeInteractionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/IconAttributeInteractionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/LineStyleAttributeInteractionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/TransactionGraphLabelsAttributeInteractionNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/interaction/VertexGraphLabelsAttributeInteractionNGTest.java

Added unit tests to the `*AttributeInteraction` classes for Core Visual Schema
more unit tests = good
#413

Visual schema interaction unit tests

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/parser/ExcelImportFileParser.java

The way that the Excel import file parser was parsing numeric values was by getting them as double values before converting to String. The result of this is that it's impossible to parse a column as epoch datetimes as it freaks out as soon as it tries to pass the string as a long. This fix checks the double value coming in and determines whether it is a whole number before converting to String. If it is a whole number, then it gets the long value of cell first.
Enables people importing excel spreadsheets through the file parser to specify a column as an epoch datetime without Constellation freaking out
Can pass through epoch in a spreadsheet, don't need …

Excel Import bug fix

---

CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/CompleteGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/PreferentialAttachmentGraphBuilderPlugin.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/SmallWorldGraphBuilderPlugin.java

Currently, some of the experimental graph builders allow you to specify the types of nodes and transactions that will be used to build the graph and those lists are generated by getting all the registered types and putting them in the list. A potential issue arises with this though as this means that this would include any types that may have otherwise been overwritten (as specified in the schema concept's overwrittenVertexTypes and overwrittenTransactionTypes). This change resolves that issue by making use of existing functions designed to generate the list types without any overwritten types (as used by the Schema View) 
fixes potential bug
bug fix

Experimental Graph Builder possible parameters issue fix

---

.github/workflows/nightly-build.yml

Just a spelling fix in one commit.
No related ticket.

fix spelling in nightly build actions

---

CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java

The property value minimum text width has been updated to be the same width as the Property Value column title text and now expands as required when the Histogram is expanded. 
N/A
Fixes previous change that made the histogram bars not viewable when a vertex attribute is too long. 
Also stops the Count and Selected / Total Bin Count text for overlapping. 
N/A
#1600

Fixed Property Value Text Size in Histogram

---

CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

Added a missing whatsnew entry for the recently merged experimental find view
Good to tell users when a new feature is available
Informs users of a new feature

added missing whatsnew entry

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java

Added null checks to the new advanced find to stop null pointer exceptions from being thrown. 
None realised 
Less bugs in core.
None realised
Attempted reproducer from the original ticket (#1653) in multiple scenarios and could not reproduce the null pointer exception. 
#1653

New Find View Null Pointer Check 

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedSourcePane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedIO.java

As illustrated in https://github.com/constellation-app/constellation/issues/1652, when loading a template, `Destination` and `Files Include Headers` options now set as in the template.
File Parser is now checked before loading a template. A warning is displayed if they are not the same.
With the file parser check, perhaps we can check the column structures as well, or only perform a column structure check?
Bug fix
Better UX
n/a
As illustrated in the related issue https://github.com/constellation-app/constellation/issues/1652.
https://github.com/constellation-app/constellation/issues/1652

Fixing File Importer Source and Destination options when loading a template

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/components/ButtonToolbar.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/components/ButtonToolbarNGTest.java

Favourites option in Data access view is not working after the DAV refactor
This is a core functionality
Allow users to save their plugin favourites.
Open DAV select few plugins and click the star (Favourites). 
Select add or remove to choose the list of favourites
Close and open the application
Favourites category should appear

DAV Favourites option not working

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ConfigurationPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RunPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/docs/import-from-database.md
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/ImportJDBCIO.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCImportPane.java

Templates can now be saved and loaded in the Database Importer.  The `Run` tabs now clear previous query data  in the `Configuration` pane when a new query returns no data.
Bug fix enables the broken feature
1. Open Database importer and import some data. Drag and drop some attributes onto some columns.
2. Clicking on `Save template` button should prompt a window to enter a name for the new template. Then save it. 
3. Remove or change the attributes mapped.
4. Clicking on `Load Template` button should prompt a window with existing templates to select from. 
5. Load the previous template. It should remove the current mapping and load the previously mapped …

Fix Templates in Database Importer

---

CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/xml/XmlUtilitiesNGTest.java

* Added the license header
* Added some methods to refactor making the Xml Document and removing whitespacing
* Avoid using `new String()`
* Using `assertEquals` instead of `assertTrue`
* Code formatting
* Minor refactor to help with maintaining the code base
* The license header was missing
None realised
Re-ran the tests and made sure they all still passed.

Minor refactoring to XmlUtilities

---

CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/Blaze.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/ConnectionMode.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/LayerName.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/Plane.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/PlaneState.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/BlazeNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/ConnectionModeNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/LayerNameNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/PlaneNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/objects/PlaneStateNGTest.java

Unit tests and code comment additoon/cleanup for code in Visual Schema Models
Nil
Improve code quality
Improve code quality
None known
Test all pass
Nil

Visual Schema Models test and code comments/cleanup.

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportController.java

The warning message text when the headers are mismatching in the File Importer is changed to mention the mismatching files will be removed rather than deleted.
https://github.com/constellation-app/constellation/issues/1637

Improve the warning message text when the headers are mismatching in the File Importer

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/ExportMenu.java

Table view Export dialogs now display the folders along with the files of the relevant type.
1. Open a graph and go to the Table View
2. Click on the download option
3. Pick export to CSV
4. Verify the folders are displayed in the pop up window
5. Verify the folders are displayed in the folders at any level
6. Repeat with XLXS
https://github.com/constellation-app/constellation/issues/1623

Show the directories in Table view export dialogs

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/components/DataAccessResultsDirChooser.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/widgets/IconChooser.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/image/ExportToImageAction.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/json/ExportToJsonAction.java
CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/ScriptingViewPane.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/ExportMenu.java

1. Removed file path from the `File Name` field in the following pop up dialogs when 
- Table View->all Export dialogs 
- Scripting View->Options->`Open`, `Save as`
- Export To Image
- Export To JSON
- `Add Icons`, `Save Icon` in Icon Chooser (Not sure where this is used, hence not tested)
2. Fixed the `Export to Image` and `Export to Json` file chooser pop up dialogs to show the valid files previously added.
https://github.com/constellation-app/constellation/issues/1624

Fixing file open dialogs using `FileChooserBuilder`

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

The `EXCEL` is added as an option for parsing native excel datetime into Constellation which is available in the  `DateTime` `Formatter` in the `File Importer`.
1. Create an excel spreadsheet with a column with datetimes represented as a numeric value
2. Open File Importer in Constellation and load file in
3. Try to parse the intended column as a datetime
4. Right click and set the `DateTime` attribute format to `Datetime`->`EXCEL` and now parse the column as a datetime
https://github.com/constellation-app/constellation/issues/1663

Add Excel DateTime parsing option in File Importer

---

CoreUtilities/src/au/gov/asd/tac/constellation/utilities/json/JsonUtilities.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/json/JsonUtilitiesNGTest.java

When a `JsonNode` is null then return `null`. This helps when comparing null values. This was the behaviour before the recent refactor/unit testing hat was added.

JsonUtilities null node

---

CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
README.md

* Remove steps from the `README.md` that are no longer required
* Fix html syntax issues in `whatsnew.txt`
https://github.com/constellation-app/constellation/issues/1676

:memo: Update to README and fixes to whatsnew.txt

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/components/DataAccessTabPane.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/QueryPhasePane.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/components/DataAccessTabPaneNGTest.java

Fixed bug where the recent values used in string parameters are not saved to the recent values drop down list after running a plugin in the Data Access View. 
None realised
Fixed bug in core.
None realised 
Tested using the Split Nodes Based on Identifier plugin in the Data Access View, using a string value in the Split Character(s) parameter and seeing that the value is added to the recent values drop down list after the plugin is run.
#1662

Fixed Recent String Parameter Values Saving

---

CoreHelp/src/au/gov/asd/tac/constellation/help/HelpWebServer.java
CoreHelp/src/au/gov/asd/tac/constellation/help/preferences/Bundle.properties
CoreHelp/src/au/gov/asd/tac/constellation/help/preferences/HelpOptionsPanel.form
CoreHelp/src/au/gov/asd/tac/constellation/help/preferences/HelpOptionsPanel.java
CoreHelp/src/au/gov/asd/tac/constellation/help/preferences/HelpOptionsPanelController.java
CoreHelp/src/au/gov/asd/tac/constellation/help/preferences/HelpPreferenceKeys.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/preferences/HelpOptionsPanelControllerNGTest.java

Fixed bug where the Offline Help server and Rest server were not able to be run at the same time due to attempting to use the same port. 
Also added a preference in the Constellation options menu where the users are able to change the port for the Offline help server. 
None realised. 
Fixing a bug that is in core and providing the user with a new option to change the port of the offline help server. 
New preference option of users. 
None realised. 
Open the Help Documentation offline
Start the Rest server (Tools -> Start REST Server)
Observe that no errors are thrown when the server ports don't match.
#1672

Added Offline Help Server Port Preference

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/analytics/FactAnalyticPlugin.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/analytics/ScoreAnalyticPlugin.java

See title and https://github.com/constellation-app/constellation/issues/48#issuecomment-1114481005. tldr: it's not required (in all cases)
Fix an issue in Core
Not confusing people thinking a parameter is required when it is not
may be required in some instances (I assume I initially made it required for a reason) but I think more research needs to be done to determine the best solution. In the meantime, I'm sure there are other parameters not marked as required that are so this can possibly be re-evaluated when that is fixed

HOTFIX: reverted change that made a particular parameter required

---

bootstrap/assets/css/app.css

Updated the background colour of the online help menus so that the text is readable when hovered over. 
https://github.com/constellation-app/constellation-app.github.io/pull/8 - is the main PR that needs to be merged for this fix. This PR is just so that the changes don't get overwritten if the files are copied between repos. 
#1621

Online Help Menu Button Hover Colour 

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java

The dates formatted by the Excel datetime parser was introducing a time difference equal to that of the constellation user's time zone difference from GMT. This has been fixed now.
The correct time zone details are still not included as explained in https://github.com/constellation-app/constellation/issues/1673
1. Create an excel spreadsheet with a column with datetimes represented as a numeric value
2. Open File Importer in Constellation and load that file
3. Right click and set the DateTime attribute format to Datetime->EXCEL and now parse the column as a datetime
4. The same datetimes entered in the excel file should be displayed in the converted …

Remove the user's time zone difference added in the Excel datetime parser

---

.github/workflows/release-build.yml

A Github action to do the releases using Github actions. I have not tested this but it is a copy of the `nightly-build` with the addition of the `sed` command to update `Startup.java`. We may need 2 of these, one for Constellation and another for Cyber.
I have some further improvements to other GH actions and will push that into a separate PR if this one works.

Release Build Action

---

.github/workflows/build-and-scan.yml
.github/workflows/documentation_update_trigger.yml
.github/workflows/greetings.yml
.github/workflows/nightly-build.yml
.github/workflows/stale.yml

Following on from the recent update to the GitHub actions, I have made some improvements to the YAML scripts which is mainly formatting.

Update formatting of Github Actions YAML

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/AttributeNode.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ImportPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/TemplateUtilities.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedSourcePane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedIO.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/ImportJDBCIO.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

Templates in database and file importers now handle some edge cases and prevent exceptions, specifically when the templates are of an incorrect format. This was specially the case with legacy templates. More notes and discussions are in https://github.com/constellation-app/constellation/issues/1652 after the comment by [GammaVel](https://github.com/GammaVel)  
n/a
Templates are more usable
Better UX
n/a
As described in detain in https://github.com/constellation-app/constellation/issues/1652 Legacy/incorrect format could be manually created by editing a new template as in the screen captured there. Test both importers with all combinations of options, …

Template exceptions fix in database and file importers

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPlugin.java

Previously, `updateParameters()` wasn't overwritten in `WorkflowQueryPlugin`. The consequence of this was any plugins included in a workflow plugin wouldn't have their respective `updateParameters()` called if it was defined. This small change updates this to make sure updateParameters is called when necessary to ensure a plugin still runs as it would on its own.
Changes to an existing part of core
All plugins in a workflow behave as if they would standalone
Nil

WorkflowQueryPlugins update

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java

Changed text in formatter from "EPOCH" to "EPOCH (Unix)"
It is good to implicitly state that it is a unix epoch to avoid confusion.
People know that it is an unix EPOCH.
Text changes in the drop down. Unit tests pass. Formatter works on imported data.
#1699

Change EPOCH Formatter Text

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/components/ButtonToolbar.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/components/ButtonToolbarNGTest.java

Capitalized "favourites" in the manage favourites dialog box in the DAV.
Changed wording on "note" line in the dialog box.
N/A
Improves readability 
Improves user readability
N/A
Ran and noted that the text updated and the unit tests passed
#1677

Changed manage favourites dialog text

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find2/FindViewController.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find2/FindViewTopComponent.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find2/components/AdvancedFindTab.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find2/components/BasicFindTab.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find2/components/advanced/StringCriteriaPanel.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
CoreFindView/test/unit/src/au/gov/asd/tac/constellation/views/find2/components/BasicFindTabNGTest.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/GraphElementType.java

Changed title from "Find View" to "Find". In the "Basic Find" tab, "In Attributes" label has been updated to "Search Attributes". All attributes are selected by default. 
In the "Advanced Find" tab the number of matches found is displayed.
The "Match Criteria" and "Current Selection" labels have been spaced out.
Updated the "Ignore Case" label in advanced find tab.
Decided not to update strings in the "Look for" drop down to plural as it would impact code in other areas of the codebase.
Improves user experience.
Improves readability of UI text elements. Adds in features that were available in the old find view which improves experience.
Unit tests pass, …

Find View UI Improvements

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

When no query is entered by the user an error message shows up.
Improves usability
Reduces user confusion when they click "Query" button with no query text and nothing happens.
Clicked "Query" with no text or with just spaces and the error message showed up.
#1626

Added No Query Error Message

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCConnection.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java

Changed Title Test from "JDBC Import" to "Database Import"
Error dialog box that appeared when  incorrect queries or invalid connection parameters were entered has its title changed from "JDBC Import" to "Database Import".
Better representation of the connection/query error.
Error message is more correct now.
Checked to see if the message text updated when errors are made.
#1627

Database Connection and Query Error Title Change

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/daemon/QualityControlAutoVetter.java

Quality Control View is not updating it's state correctly when a plugin run completed to update the graph.  
Quality Control View is a core functionality.
QCV state is a key to graph analysis and this change fixes the bug on QCV state.   
Need to run the QC rules if there is a change to the graph

Quality Control View Not Updating Correctly

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find/advanced/QueryServices.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
CoreFindView/test/unit/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPluginNGTest.java

Changed variable at the top so that all nodes would keep being selected when the "Ignore" option is set.
Can properly advance search "Selected" nodes.
Stops confusion as to why selected nodes were being deselected.
Cannot re-create the bug anymore going through the same methods.
#1694

Bug with Searching Only Selected Nodes Is Fixed

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
toc.md

When a note is not associated with any vertexes or transactions the "Remove Selected" option is the context menu is disabled.
Reduces confusion on notes associated with the whole graph when the "remove selected" option does nothing.
Improves suability
When no graph elements are associated with note the "Remove Selected" option is disabled. When I add elements to the note the option becomes enabled again.
#1249

Notes View "Remove Selected" Menu Item Disabled

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewTopComponent.java

Fixed the issue where auto notes were not being refreshed in the notes view. The issue ended up being a combination of multiple threads interacting with the same objects at the same time and some operations being done in the wrong order.
While I was at it, I also cleaned up some of the `Platform.runLater` calls (as there was plenty of code that either didn't need to run on the fx thread or didn't need a separate call to queue on the fx thread) which should hopefully have improved performance a little. Also did some other minor code cleanup in the classes.
Considered reverting a change made to the state reader to set the pane notes to a copy of the state …

Fixed Auto Notes Issue

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/ValueInputPane.java

Updated the string dropdown lists from being able to show text longer than the Constellation window.
N/A
Stops text from being displayed in a way that is hard to read and extends off of the main window.
Easier readability.
N/A
Entered a long string into the Extract Types from Text plugin in DAV and observed that the width of the text in the dropdown list is set to a max size.
#1686

DAV String Dropdown List Width 

---

CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/bins/edgeaggregates/EdgeMaxTransactionDatetimeAttributeBin.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/bins/edgeaggregates/EdgeMinTransactionDatetimeAttributeBin.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/bins/linkaggregates/LinkMaxTransactionDatetimeAttributeBin.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/bins/linkaggregates/LinkMinTransactionDatetimeAttributeBin.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/bins/neighbouraggregates/VertexMaxNeighbourDatetimeAttributeBin.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/bins/neighbouraggregates/VertexMinNeighbourDatetimeAttributeBin.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/bins/vertexaggregates/VertexMaxTransactionDatetimeAttributeBin.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/bins/vertexaggregates/VertexMinTransactionDatetimeAttributeBin.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/temporal/TemporalFormatting.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/temporal/TemporalFormattingNGTest.java

Updated the file importer so that the DateTime Epoch formatter imports as Epoch in seconds rather than milliseconds. 
Updated attributes in Core Histogram View as they were passing in values too large to be converted to Epoch in seconds.
N/A
The standard for Epoch is seconds past 1970. Updated from Milliseconds to Seconds so that Constellation matches the standard.
N/A
1. Create a sample CSV file for testing that has EPOCH times 
2. Import into Constellation using the Import from File functionality 
3. Observe that the times are converted correctly from Epoch
#1724

Convert Epoch DateTime from Milliseconds to Seconds

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
CoreFindView/test/unit/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPluginNGTest.java

Fixed bug in #1694 and the bug that was introduced in #1741 (discussed [here](https://github.com/constellation-app/constellation/issues/1694#issuecomment-1225132464)).
N/A
Bug fix.
Tested that both of the bugs reported in #1694 no longer occur.
#1694 
#1741

Fix to Selection Bug in Find View

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/LayerByTimeAction.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersSwingDialog.java

Created a set size for the layer by time window to stop it creating a window too big that requires scroll bars. 
Added a set size method to the dialog box to stop it from changing the size of other windows that use the PluginParametersSwingDialog class.
N/A
UX improvement.
N/A
Layer by time window now opens without any scroll bars. 
#1722

Update Layer by Time Window Size

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/subgraph/ComponentSubgraph.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPlugin.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/GraphWriteMethods.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/GraphRecordStoreUtilities.java
CoreGraphFramework/test/unit/src/au/gov/asd/tac/constellation/graph/StoreGraphValidator.java

Workflow Query plugins are a great tool in Constellation to run multiple plugins sequentially without having to execute each plugin individually. Looking at the code though, it appears that a lot of the logic in and around `WorkflowQueryPlugin` only really works for running node-querying plugins rather than transaction-querying plugins, and so will present issues when you want to include a plugin of the latter style in your workflow. This PR adds some changes to allow transactions to be properly considered when running a workflow plugin.
An issue was also identified in which the batch subgraphs being created by the workflow plugin wasn't always applying …

fixed potential issues with workflow plugins

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/Table.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/TableDataComparator.java
CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview/components/TableDataComparatorNGTest.java

Columns in the Table View can now be sorted numerically.
Previous alphabetical sorting would give:
1
10
2
200
37
ABC1000
ABC123
ABC45
ABC6
ABC789
With numerical sorting, the order will now be:
1
2
10
37
200
ABC6
ABC45
ABC123
ABC789
ABC1000
Highly requested by prominent users.
Numbers need to be sorted numerically, as it is not useful to sort them alphabetically.
Potentially slower to perform the sort.
Check that numeric columns are sorted correctly.
Check that alphanumeric columns are sorted correctly.
Check that regular text columns are still sorted correctly.
#1197

Numerical sorting in Table View

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/docs/data-access-view.md

Fixed a link to a help page that was missed in a previous PR. 
Bugfix
Checked that the link opened the correct help page. 
#1681

Fixed Broken Help Page Link

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/geospatial/AbstractGeoExportPlugin.java

For a number of the geo export plugins, the Attributes parameter wasn't populated despite the element type already being set by default. This was because the element type default value was set before the controller (which populated the attribute parameter) was defined and it didn't know something needed to happen. Moving this set until after the controller is defined ensures the controller is also triggered by default which delivers the desired result
bugfix
nil
1. Go File > Export > GeoJSON (or one of the other geo export options, may need to open a graph first to have this option enabled)
2. Verify in the parameter window that the …

Geo export parameter fix

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java

Fixed issue with Linux dialog width being too small for the content displayed.
A larger width will be used if the system detects that it is running on Linux.
N/A
For improved visual appearance on Linux systems.
Improves visual appearance on Linux systems.
None
Confirm the Quality Control - Category Priority dialog is displayed at an appropriate size on Windows systems, and also on Linux systems.
#1792

Quality Control - Category Priority: Set dialog width based on system environment

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/temporal/TemporalFormatting.java

A change was made recently to swap EPOCH values to be converted using seconds instead of milliseconds. The Excel date time convertor was using the same EPOCH convertor, but requires it to be converted with milliseconds.
Added a second function so that the EPOCH values can still be translated with seconds and the Excel values can be translated using milliseconds. 
Bugfix in core.
Imported Excel date time data using the file importer.
#1797

Convert Excel Date Time Using File Importer

---

CoreAnalyticView/nbproject/project.xml
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/export/AnalyticExportResultsMenu.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPlugin.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironment.java
CoreGraphNode/test/unit/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginEnvironmentNGTest.java
CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReportPane.java
CoreTableView/nbproject/project.xml
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/ExportMenu.java

When viewing the plugin messages through the Plugin Reporter:
Child plugin messages will now be shown as part of a hierarchy of messages originating from a parent plugin.
N/A
For improved readability of plugin messages in the Plugin Reporter.
Seeing the hierarchy of messages in the Plugin Reporter provides an addition means of tracking the program flow.
N/A
Use the Analytic View to run some metrics on a graph.
Look at the plugin messages in the Plugin Reporter to confirm child messages are contained within parent messages.
Can also test in the Data Access View -> Test Parameters (Batched)
Confirm the child messages shown in the Plugin Reporter are …

Child plugin messages should be reported hierarchically through parent plugin.

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBubble.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/EnhancedTextArea.java

Added a negative offset to the bottom of the InlineCssTestArea which holds the messages. Also added an extra line at the end of each text message. The negative offset makes it look like there is no extra line at the end of messages.
Users don't have to give each message an extra click to fully view it.
Improves readability of messages.
Improves usability of conversation view.
If the InlineCssTextArea has a maximum number of messages it can hold, adding a new line at the end won't work. Although it is unlikely that texts would be that long.
Boxes also shrink slightly when clicked but this is not a drawback but thought I would mention it here.
Tested with …

Fixed Line cutoff bug in Conversation View

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java

Fixed an issue found in testing in the Analytic View where threads may block and cause the screen to hang.
Additional changes made to child plugin reporting through Analytic View.
N/A
Improved plugin reporting
Better visual representation of program flow.
Unknown
Test the Analytic View to confirm normal functionality, and child plugins report through their parent plugin.
#323

Child plugins will now report through parent plugins

---

CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/DataAccessViewWelcomePlugin.java

Reverted change made with unit tests that created a bug.
#1810

Fix bug with Welcome View Unit Tests

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java

Right click context menu hierarchy was not displaying correctly when multiple sub-menus specified including already existing items, in the `getMenuPath` of a Context menu. 
n/a
Fix the Right click context menu
Bug fix
n/a
1. Open a new Graph
2. Add a node to the graph
3. Right-click on the Node
4. Hover over the Layers option
5. Sub-menu should contain `Add Selection to Layer` and `Remove Selection from Layer` instead of `Remove Selection from Layer` after another `Layers` Sub-menu
https://github.com/constellation-app/constellation/issues/1750

Right click context menu hierarchy when already existing sub-menus are specified

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java

A simple check is added to fix the Arithmetic Exception occurring in the Conversation View when search item is not found.
1. Open up a graph with content viewable in the Conversation View
2. In the Conversation View, write a search term with no results
3. Press Enter
https://github.com/constellation-app/constellation/issues/1824

Fix Arithmetic Exception in Conversation View

---

CoreNotesView/release/modules/ext/docs/CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/notes-view.md
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimePicker.java

Changed the format of date in the time range filter to Year-Month-Day
Consistency with the data access view.
#1761

Updated help text of notes view and changed date format

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java

When the date time field is applied to the column, the header row contents are being shown as ERROR. 
Expected behaviour: The error field is ignored and the import completes with a message saying how many error rows were ignored
Cover the filter with try-catch and increment skipInvalidRows counter
#1731 #1795 #1796

1731 file import error numberformtexception

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/NumberInputPane.java

Numeric fields will now check the input text against a number pattern to confirm valid numeric data.
Could wait indefinitely for the component creator to provide a validation method.
Improved User experience.
Prevents bad data being used in number fields.
N/A
Test on Integer parameters and Float parameters.
Confirm the non-numeric keystrokes are being ignored.
#1687

Only allow numeric text in number parameters.

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java

This is a quick fix to make sure that when the user saves a note the graph needs to be saved as well. This way user changes to notes are not suddenly lost when they close consty.
Currently notes do not get saved to file when closing a graph because the user isn't given the option to save. But now thats fixed and the graph save dialog is set to trigger after a note is saved. 
Users can save notes to file using Ctrl+S instead of having to make changes to the graph itself to trigger the save event.
The fix seemed simple enough and nothing should be this easy, drawbacks will appear after testing.
Made changes to note and then saved it. The title of the graph …

Notes View graph save

---

CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV6UpdateProvider.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV6UpdateProviderNGTest.java

Changes were made in #1804 which improved sonar smells in some of the regexes in the `AnalyticConcept` types. No schema updater was created though for those changes so this change remediates that.
Backwards compatibility with older graphs already making use of the types that were modified
Backwards compatibility
Nil

added schema updater for regex changes in analytic types

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find2/FindViewController.java

Upon opening the new find view, if find next is the first button pressed on the basic find tab then it causes all of Constellation to hang. This single line change fixes this. 
This bug was found in testing the new release candidate for 2.10 and was not found in the 2.9 release.
Bug fix.
Open Constellation, a new graph and the new find view.
Type in a string to search in the basic find.
Hit Find Next.
Application won't become unresponsive.

Bug with New Find View Find Next 

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java

Fixed the undo caption of `Create Transaction` which was incorrect as  `Undo Process Gestures`, by executing it later rather than in the current thread, similar to Create Vertex, as per the discussions.
Removed the explicit call to flush in the `DefaultInteractionEventHandler.startHandlingEvents` only for Create Transaction, but kept the other half of the `||` operation JIC. Or can we remove all that code?
In SimpleEditPlugin-> public void run(final GraphWriteMethods graph,......) , somehow set a LockingManager.LockingEdit when the plugin is run. 
Bug fix
Better UX
Open a new graph, add a transaction and check Edit->undo which should be `Undo Create …

Fix the incorrect caption `Undo Process Gestures` to `Undo Create Transaction`

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java

Fixed bug where the users first click would count as two clicks in the Quality Control View when a new sphere graph is created. 
Fixes bug which causes confusion when using quality control view.
Improves usability of quality control view.
#784

Fixed double click bug in quality control view

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java

Fixed bug where the dialog boxes for select rule priority would appear only in the default monitor of workstations with multiple screens instead of the screen constellation is open in. 
Fixes a dialog positioning bug.
Reduces confusion for the user when opening the select rule priorities box.
#1793

Fixed quality control dialog box positioning

---

CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/utilities/BlazeUtilities.java

Updated Custom Blazes window title and description for Color selection.
Old version:
New version:
N/A
N/A
More user friendly.
N/A
N/A
#1886

Update Custom Blazes Window Title

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java

Added missing full stop and adjusted capitalization of "Skip Invalid Rows" so it is consistent with the text on the Import pane.
Old version:
New version:
N/A
N/A
N/A
N/A
N/A
#1883

Fix typos in error message for CSV import

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessViewCategoryPanel.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/tasks/LookupPluginsTask.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/utilities/DataAccessUtilities.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/tasks/LookupPluginsTaskNGTest.java

Add some fixes to potential issues that could arise in extending Constellation.
For instance, it appeared the code was assuming that any categories being looked at were one word with no spaces so a category such as 'My New Category' could disappear after ordering as it would be looking for 'My' rather than 'My New Category'. Also appeared the ordering was no longer looking at the category position for default ordering so this has been fixed.
Code in Core still needs to account for extending the application beyond Core.
Fixes potential issues with data access category ordering
Nil
#1682

fixed some potential issues around data access category ordering

---

CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/AbstractEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/BlazeEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/BooleanObjectEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/ByteObjectEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/ColorEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/DateEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/DateTimeEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/DoubleObjectEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/FloatObjectEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/HyperlinkEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/IntegerObjectEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/LocalDateTimeEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/LongObjectEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/ShortObjectEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/StringEditorFactory.java
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/TimeEditorFactory.java

The user can start editing an attribute straight way after clicked on one of the attribute panes.
Saves an extra click for the user as they don't have to un-tick the "No-value" checkbox anymore.
Reduces frustration when using the attribute editor.
When I go to edit an attribute the checkbox for no value is unticked.
#1888

Attribute Editor - Untick No Value Checkbox

---

CoreNotesView/release/modules/ext/docs/CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/notes-view.md
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/utilities/TextHelper.java

- [ x] Reviewed the [checklist](CHECKLIST.md)
Added in some help text that say what markdown features are available in the notes view.
Users might not know what markdown is or which features have been implemented so this is just some documentation on that.
Easier to use the markdown features
Maybe some of the help is not descriptive enough.
#1754

Added help text for Markdown

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/ConversationBox.java

I identified a possible null pointer issue with the `ConversationBox` which I've now resolved. In the sender attribute listener for the conversation, a list of possible sender attributes is filtered (to remove null values) before setting that as the sender attribute choices. The filtering though is currently being done incorrectly as the filter function only returns the stream and doesn't actually collect the results of the filter, meaning the subsequent setAll is still happening on the original list being passed (rather than the filtered one).
Bug fix
Bug fix

Conversation Box bugfix

---

CoreNotesView/release/modules/ext/docs/CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/notes-view.md

Removed the escape characters that were showing up in the markdown help text for the Notes View.
#1754

Removed escape characters from Notes View help.

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewTopComponent.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/translators/ScoreToHideTranslator.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/utilities/AnalyticTranslatorUtilities.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/visualisation/HideVisualisation.java
CoreAnalyticView/test/unit/src/au/gov/asd/tac/constellation/views/analyticview/utilities/AnalyticTranslatorUtilitiesNGTest.java

Fixed null pointer exception for old graphs.
Fixed bug when having the Conversation View open when closing the Analytic View which has some visualisations active causes Constellation to hang.
Fixed array index out of bounds exception for the hide visualisation when switching between graphs of different sizes.
Bugfix in core required for the new release. 
Old Graph Null Pointer:
1. Open a graph from v2.10 which has had an analytic run on it before
2. Create a new graph
3. Run an analytic on the graph from version 2.10
4. Swap to the new graph and observe the null pointer no longer occurs
Conversation View Bug:
1. Open the Conversation View and at least 2 …

Bug Fixes for the Analytic View State

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/DefaultPluginParameters.java
CorePluginFramework/test/unit/src/au/gov/asd/tac/constellation/plugins/parameters/DefaultPluginParametersNGTest.java
CorePluginFramework/test/unit/src/au/gov/asd/tac/constellation/plugins/parameters/types/MultiChoiceParameterTypeNGTest.java

A couple of extra unit tests written for `MultiChoiceParameterType` and `DefaultPluginParameters`
#413

Some more unit tests

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessViewCategoryPanel.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessViewCategoryPanelController.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessViewPreferenceKeys.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/tasks/LookupPluginsTask.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/tasks/LookupPluginsTaskNGTest.java

Reworked plugin lookup logic, and fixed associated classes including the test class.
N/A
It is a core functionality of the Data Access View.
Plugins will now be displayed correctly when migrating from v2.10 to v2.11.
N/A
Tested using the steps to reproduce in the associated issue ticket.
#1918

Fixed Data Access Categories not displaying when migrating from v2.10 to v2.11

---

CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV1UpdateProvider.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV2UpdateProvider.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV3UpdateProvider.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV4UpdateProvider.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV5UpdateProvider.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV6UpdateProvider.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV1UpdateProviderNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV2UpdateProviderNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV3UpdateProviderNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV4UpdateProviderNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV5UpdateProviderNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV6UpdateProviderNGTest.java

Unit testing of Update Providers within Visual Schema
nil
unit testing / code quality
unit testing / code quality
nil
Unit tests pass, code coverage uplift
nil

Testing Visual Schema - SchemaUpdateProviders

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/advanced/criteriavalues/StringCriteriaValues.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/advanced/utilities/AdvancedSearchParameters.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/plugins/advanced/AdvancedSearchPlugin.java

The List search option available under the Advanced Find was throwing `OutOfBoundException` and `NullPointerException`. 
1. Open up an existing Constellation graph that has some values for the nodes (Identifiers or labels)
2. Go to Edit > Find
3. Copy the value for one of the Identifiers and check it can be found on the graph
4. Go to Advanced Find tab
5. Change the Match Criteria to be Any
6. Click on the "Use List" checkbox
7. Paste in the previous Search term that was copied
8. Click on Find all -> Verify no Runtime error is thrown
https://github.com/constellation-app/constellation/issues/1962

Fix the Exceptions thrown in Advanced find when the Use list check box is checked.

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SaveResultsFileWriter.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SaveResultsFileWriterNGTest.java

Put reader of a particular file in try block so it is closed automatically after use, allowing the existing code to actually delete file where it was previously unable. Deletion was blocked because scanner was still open.
N/A
Bugfix, csv files for unit tests weren't being deleted.
Unneeded csv files are now properly removed.
Aside from usual possibility of introducing new bugs, nothing.
Unit tests themselves pass, and visually observed files being deleted.
https://github.com/constellation-app/constellation/issues/1948

Add code to close reader of file which blocks deletion, format tests

---

.github/workflows/nightly-build.yml
.github/workflows/release-build.yml

The nightly and release build scripts were using older versions of actions and so updating to use newer versions. I've gone with v3 instead of v4 for upload-artifact as based on what I can see online, it seems to have possible breaking changes so don't want to switch that far without further testing (so for now upgrade to v3 and then explore what an upgrade to v4 would look like)
Upgrading libraries used
Upgrading libraries used

updated build scripts to use newer versions of actions

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/attribute/TimeZoneAttributeDescription.java

Added an additional check in ```convertFromString()``` that covers bad default values of time zones.
The default values of the different time zones could be changed, but I couldn't find out where they're set.
Bug fix, certain graphs can't be opened.
Certain graphs can now be opened.
Aside from usual risks, none.
Verified by creating graphs similar to one described in the original issue and with unit tests.
https://github.com/constellation-app/constellation/issues/1907

Bug/exception on load time_zone

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/DataAccessViewTopComponent.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/io/DraggableCell.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataSourceTitledPane.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/PluginFinder.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/experimental/TestParametersPlugin.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GMLImportProcessor.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/file/GraphMLImportProcessor.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectTopNPlugin.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreDropper.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/RecordStoreQueryPlugin.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/utilities/GraphMLUtilities.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/io/DataAccessStateIoProviderNGTest.java
CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportDialog.java
CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportTopComponent.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/AdvancedFindTab.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/BasicFindTab.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/FindViewTabs.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/ReplaceTab.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/advanced/DateTimeCriteriaPanel.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/advanced/utilities/AdvancedSearchParameters.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/components/advanced/utilities/UseListInputWindow.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/plugins/advanced/AdvancedSearchPlugin.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/quicksearch/GraphRetriever.java
CoreFindView/src/au/gov/asd/tac/constellation/views/find/utilities/FindViewUtilities.java

Updated code to use some of the new features introduced between Java versions 11 and 21.
Modules updated:
Data Access View
Error Report View
Find View
Keep code updated to latest Java specifications.
Improved code readability.
Incorporating the latest improvements in the Java platform to the Constellation code.
#1987

Data Access, Error Report, and Find View, code updates.

---

.github/workflows/build-and-scan.yml
.github/workflows/nightly-build.yml
.github/workflows/release-build.yml
docker/netbeans-runner/Dockerfile

Updated the netbeans runner to remove files being downloaded to support old help system. These files were no longer needed but it seems they were also affecting builds
Fixes issues with builds
Fixes issues with builds

updated netbeans runner to remove files downloaded for old help system

---

CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/DateTimeRangeInputPane.java

Added wrapping to the datetime range spinners in data access view.
N/A
Better usability.
None.
Automated testing and manual use of spinners.
https://github.com/constellation-app/constellation/issues/2014

Add wrapping to spinner widget

---

ProjectUpdater/nbproject/project.properties
ProjectUpdater/src/au/gov/asd/tac/constellation/projectupdater/ProjectUpdater.java

Updated the ProjectUpdater to Java 21
Update Core code
Core code updated

Updated ProjectUpdater

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/results/FactResult.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/UndoGraphEditState.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/query/BitMaskQueryCollection.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationPolygonMarker.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/utilities/FeatureKey.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/AxesRenderable.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelinePanel.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/geospatial/Shape.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/attribute/compatibility/ElementGraphLabelsV0.java

The following Sonar rules have been cleaned up in the code:
(Java) Literal suffixes should be upper case
(Java) Lambdas should be replaced with method references
Updating code in Core.
#2022

Sonar Code Smells Cleanup (Literal Suffixes, Lambdas)

---

CHANGELOG.md
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/GraphRecordStore.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/HookRecordStore.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/RecordStore.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/TabularRecordStore.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/placeholder/PlaceholderUtilities.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/placeholder/StoreGraphRecordStore.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ActionPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RowFilter.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/draw/CreateTransactionPlugin.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/draw/CreateVertexPlugin.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationClusterMarker.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/markers/ConstellationMultiMarker.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GraphRenderable.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/FileInputPane.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/MultiChoiceInputPane.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/NumberInputPane.java
CoreSecurity/src/au/gov/asd/tac/constellation/security/proxy/ConstellationHttpProxy.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelinePanel.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/merge/PermanentMergePanel.java
CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/merge/PermanentMergeTableModel.java
CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudTopComponent.java

The following Sonar rules have been cleaned up in the code:
(Java) Private fields only used as local variables in methods should become local variables
(Java) Restricted identifiers should not be used as identifiers
(Java) Lambdas containing only one statement should not nest this statement in a block
Updating code in Core.
#2022

Sonar Cleanup (Private fields, restricted identifiers, lambdas containing only one statement)

---

CoreFindView/src/au/gov/asd/tac/constellation/views/find/plugins/BasicFindPlugin.java
CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/io/GraphJsonWriter.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/schema/type/SchemaTransactionTypeUtilities.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/schema/type/SchemaVertexTypeUtilities.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/value/expression/ExpressionParser.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/hashmod/HashmodAction.java
CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/widgets/IconChooser.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/InfoOverlay.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/PluginParameter.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/factory/TableViewPageFactory.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/file/ConstellationInstalledFileLocator.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/geospatial/StyleGenerator.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/StringUtilities.java

Changes address the following Sonar Rules
**(Java) "==" and "!=" should not be used when "equals" is overridden** - The following case could not be addressed
- ExpressionParser (au.gov.asd.tac.constellation.graph.value.expression)
**(Java) Method parameters should be declared with base types** - All cases addressed
**(Java) Generic wildcard types should not be used in return types** - All cases could not be addressed.
Refactoring wild cards in all cases will result in a knock-on effect for a large number of classes across many modules. If warranted, this work can be undertaken but does not seem a priority given the effort vs value.
**(Java) Mergeable …

Code Smells (use equals, remove arrays from parameters, wild card returns, mergeable if statements)

---

CHANGELOG.md
CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/traits/FlowUndirected.java
CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/utilities/Point3D.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/locking/LockingManager.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/undo/UndoGraphEditState.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/utilities/MultiValueStore.java
CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ImportDefinition.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/parser/ExcelImportFileParser.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomUtilities.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
CoreNamedSelectionView/src/au/gov/asd/tac/constellation/views/namedselection/NamedSelectionTopComponent.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/JoclVersionAction.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/JoglVersionAction.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/GLInfo.java
CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/GlyphsFrame.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/BooleanParameterType.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/FloatParameterType.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/IntegerParameterType.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/ParameterListParameterType.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/PasswordParameterValue.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/StringParameterValue.java
CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/ScatterChartPane.java
CoreSecurity/src/au/gov/asd/tac/constellation/security/password/PasswordObfuscator.java
CoreSecurity/src/au/gov/asd/tac/constellation/security/proxy/ProxyOptionsPanel.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelineTopComponent.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/clustering/TreeLeaf.java
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/components/TimelineChart.java

Changes address the following Sonar Rules
**Fix (Java) Method names should comply with a naming convention** - The following case could not be addressed
- SEdge (au.gov.asd.tac.constellation.views.scripting.graph)
- SLink (au.gov.asd.tac.constellation.views.scripting.graph)
- SReadableGraph (au.gov.asd.tac.constellation.views.scripting.graph)
- STransaction (au.gov.asd.tac.constellation.views.scripting.graph)
- SVertex (au.gov.asd.tac.constellation.views.scripting.graph)
- SWritableGraph (au.gov.asd.tac.constellation.views.scripting.graph)
**(Java) Methods should not have identical implementations** - All cases addressed
**(Java) Format strings should be …

Code Smells - (method naming convention, method duplicate implementation, string formatter)

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticAggregatorParameterValue.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/Generator.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TOCGenerator.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TOCParser.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TreeNode.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/ActionPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/RunPane.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCConnectionManager.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCDriver.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCDriverManager.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewState.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersSwingDialog.java

Addressed some of the code smells identified by Sonarcloud.
However, there are many "instanceof" issues flagged by Sonar which cannot be fixed.
They fall into a category similar to the following:
> To check if an instance is a List of any type in Java, you can use the instanceof operator. 
> However, due to **type erasure** at compile time for **generics**, 
> directly checking for a specific parameterized type like List\<MyType\> is not feasible.
> 
Improved code quality, and coding standards.
Consistency in coding standards.
#2022

Sonar code smells:  Raw types should not be used

---

CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/image/ExportToImageAction.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/json/ExportToJsonAction.java
CoreImportExportPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/importexport/image/ExportToImageActionNGTest.java
CoreImportExportPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/importexport/json/ExportToJsonActionNGTest.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/SaveAsAction.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/FileInputPane.java
CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/ExportMenu.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/ExportGlyphTexturesAction.java
CoreTesting/test/unit/src/au/gov/asd/tac/constellation/testing/ExportGlyphTexturesActionNGTest.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/filechooser/FileChooser.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/filechooser/FileChooserNGTest.java

Added dialog box when saving a graph that appears when file already exists.
N/A
N/A
User's will now be less likely to mistakenly overwrite files.
None.
Automated testing and manual testing.
https://github.com/constellation-app/constellation/issues/1957

Add confirmation dialog box when saving and file already exists

---

CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/features/ConstellationAbstractFeature.java

A change that was made during the sonar code smell surge caused an error to be thrown as the map view was opened and stopped the map from being shown.
Bugfix in Core
Open the map view 
Observe no errors thrown

Hotfix: Map View cannot be opened

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/GraphRecordStoreUtilities.java

Added null check to `normalizeType()` to prevent exception. This fixes a bug that stops the user from copying and pasting nodes.
Also auto formatted coded. Actual changes are at line 1127 in `normalizeType()`.
N/A
N/A
Restores ability to copy and paste nodes.
N/A
Automated testing and manual testing.
https://github.com/constellation-app/constellation/issues/1967

Fix exception when copy pasting nodes in graph

---

CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudIOProvider.java

words set variable seems to be unused, keeping just in case
Fixed a typo causing no such element exception when trying to open recent word cloud view graph (see original issue for steps). I think the code is unneeded to begin with, as the "words" variable isn't read from, but I'm keeping it just in case.
N/A
N/A
Fixed excpetion
N/A
Manual and automated testing.
https://github.com/constellation-app/constellation/issues/1965

Fix possible typo causing no such element exception

---

CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/HelpSearchProvider.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/HelpSearchProviderTask.java

Fixed bug that would cause multiple copies of the same help page to be opened if that help page was referred to by multiple different sources. The search bar no longer displays the duplicates of the help pages too.
For example, the help page ``export-from-constellaion.md`` is referenced by 8 different plugins which all appear on that page. When the help page is opened, 64 copies of the help page are opened.
N/A
N/A
Extra copies of a help page are no longer opened.
N/A
Tested manually.
https://github.com/constellation-app/constellation/issues/2084

Fix bug causing many copies of export help pages to be displayed

---

CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/ArrangementPluginsHelpProviderNGTest.java

Accidentally merged a PR with a broken unit test. This PR fixes that unit test
Fixes unit tests
Fixes unit tests

fixed broken unit test

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/resources/analytic-view-dark.css
CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/resources/attribute-editor-dialog-dark.css

Updated the color of the checkboxes in the Analytic View so they stand out from the background
Changed the color of the text boxes in the Parameters pane of the Analytic View to match dark mode
Changed the color of the no value checkboxes in the Attribute Editor to match the checkboxes in the Data Access View
Consistency and readability of views in Core.
#1964 
#2077

Updated Dark Mode Bugs

---

CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/HelpSearchProvider.java

Fixed a bug that wouldn't show help pages in search bar if spaces were used instead of hyphens.
For example, searching ```import from database``` wouldn't display the page for import from database, but ```import-from-database``` WOULD work.
N/A
N/A
Easier to search for help pages with spaces in their names.
None.
1. Open Consty
2. In the search bar type: ```import from database```
3. Observe the help page for "import from database" appearing
4. In a different version of Consty, in the search bar type: ```import from database``` and observe the page NOT appearing
https://github.com/constellation-app/constellation/issues/2104

Fix spaces in help page search not working

---

CONTRIBUTING.md

Fix the broken links to Developer guide in the [Contributing to Constellation ](https://github.com/constellation-app/constellation/blob/master/CONTRIBUTING.md) page
Open the above link and check links to Developer guide

Fix the Developer guide links in contributing guide

---

CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/plugins/select/SelectionContextMenu.java

Added "Select Nodes" and "Select Transactions" to right-click selection menu
N/A
N/A
More ways to select all nodes or all transactions
None.
1. Open graph in consty
2. Create some nodes and transactions
3. Right click on empty part of graph
4. Hover over selection menu
5. Observe "Select Nodes" and "Select Transactions" options are present, and are functional
https://github.com/constellation-app/constellation/issues/2108

Add "Select Nodes" and "Select Transactions" to right-click selection menu

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

(cherry picked from commit a3eddff8b77f0ac1cd248610f4a0a6673bfde17d)
Fixed the contact details, removing the references to csiro in the [Contributing to Constellation ](https://github.com/constellation-app/constellation/blob/master/CONTRIBUTING.md)page
Verify there's no reference to the csiro email anymore in the above link and the code of conduct link.

Contributing guide: update contact details

---

onlinePandocTemplate.txt

Update the documentation link on the navbar for online help
Update to online help

Update online help template

---

onlinePandocTemplate.txt

Update link for TOC in the online help template.
Update to online help

Update toc in template

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/about.txt

Updated the blurb found in Help -> About to match what is mentioned at the bottom of the Constellation website.
Up to date information
Up to date information

updated about text to match what is mentioned on website

---

.github/workflows/build-and-scan.yml
.github/workflows/stale.yml
CoreDependencies/src/ivy.xml

Updated github actions to use the latest versions of actions (except upload-artifact which will be looked at separately)
actions up to date
actions up to date

updated github actions to use latest actions versions

---

CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/SchemaViewPane.java
CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/providers/HelpIconProvider.java

Fixes a bug that happens if you open the Schema view more than once in a single session of running Constellation.
Bugfix in Core.
Open Constellation and the Schema View
Close the Schema View and reopen it
Observe no errors
Note: If you continuously open and close the Schema view with a graph open, a null pointer exception can occasionally be thrown. This existed in v2.11 and is captured in #2144 
#2143

Schema View Duplicate Children Bugfix

---

CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/editors/DateTimeEditorFactory.java

Fix bug causing date time picker in attribute editor to get stuck on current date.
N/A
N/A
Bug fixes.
None.
1. Open consty
2. Open graph that has transaction (sphere graph builder, for example)
3. Open attribute editor and select a transaction on graph
4. In attribute editor, click date time.
5. Select a date using the date picker.
6. Observe field has updated to selected date.
https://github.com/constellation-app/constellation/issues/2127

Fix date time picker's date not changing

---

CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/resources/layers-view-dark.css
CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/resources/rule-pane-dark.css
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/javafx/dark.css

Updated some of the buttons in Dark Mode to be more visible.
- Changed the DatePicker arrows to be white so they are visible
- Updated the Quality Control View radio buttons to be easier to see
- Updated the Layers View checkboxes to match the color of the Data Access View ones
Easier usability due to increased visibility for the buttons
Increased visibility on buttons 
Open the DatePicker in either the Data Access View -> Test Parameters or Attribute Editor -> Transaction -> DateTime
See that the buttons are white and a lot more visible
Open the Quality Control View -> Category Priority 
The radio buttons are now easier to see
Open the Layers View and …

Updated buttons in Dark Mode

---

CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/create/NewSchemaGraphAction.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/templates/ManageTemplatesPlugin.java
CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/templates/SaveTemplatePlugin.java
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/SingleChoiceInputPane.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SeparatorConstants.java

Templates can now be deleted (although the null pointer exception is thrown, which will be handled in a separate PR)
The cause was using `File.pathSeparator ( ; )` in file path, which doesn't work with java.io.FILE 
E.g. `C:\Users\user1\.CONSTELLATION\Graph Templates\au.gov.asd.tac.constellation.graph.schema.AnalyticSchemaFactory;New Template 1` doesn't exist to delete. Reverted back to use `/` instead.
No way to delete templates otherwise.
1. File Menu -> Select Manage Template
2. Select a saved template from the dropdown list
3. Click Delete button. 
4. Click Ok Button 
5. Open File -> Select Manage Template again and verify the above template is no …

Fix the issue when deleting templates

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/components/DataAccessTabPane.java
CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/QueryPhasePane.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPaneNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/QueryPhasePaneNGTest.java
CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/utilities/DataAccessUtilitiesNGTest.java
CoreDataAccessView/toc.md
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/ValueInputPane.java

Fixed test files that would fail randomly and inconsistently. The two main causes were a concurrency problem in QueryPhasePane and its tests, and similar issues in ValueInputPane when binding a property in a run later.
N/A
N/A
Unit tests are far less likely to fail
To validate the ValueInputPane still functions as intended:
1. Open data access view
2. Check "Test Parameters"
3. Click the down drop (recent values list) next to"Test1" parameter and observe no recent values
4. Type a value into "Test1" parameter
5. Click "GO"
6. Click the down drop (recent values list) next to"Test1" parameter
7. Observe the previous string entered is in the down drop 
Can …

Fix github testing issues

---

CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/Conversation.java
CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/DefaultConversationMessageProvider.java

Conversation view no longer shows conversations from the last viewed graph when the current graph does not contain conversation data of its own.
Bug fix
Bug fix
1. Open a graph with conversation data
2. Create a new graph and add 2 nodes and a transaction, which would not have conversation data to display
3. Open Conversation View and verify conversations are shown when the first graph is selected
4. Verify conversations clear when the nodes are selected on the second graph
https://github.com/constellation-app/constellation/issues/2149

Fix the conversation view to not show conversations from other graphs.

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomInAction.java
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomOutAction.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

Changed the default keyboard shortcuts for zooming in and zooming out to better suit Linux. `CTRL -` now zooms out and `CTRL =` now zooms in. The thought process being the physical keys have the plus and minus symbol on them.
None.
N/A
Default key binds now work on Linux
None.
1. Open consty
2. Open or create a graph with nodes in it.
3. Use `CTRL -` to zoom out
4. Use `CTRL =` to zoom in
https://github.com/constellation-app/constellation/issues/2165

Change default shortcuts for zooming in and out of graph

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java

Fixed warning message for notes view, as it didn't have any styling.
N/A
N/A
Styling is consistent.
None.
1. Open consty
2. Create new graph
3. Open notes view
4. Click "Create note", don't fill in any details, then click "Add Note"
5. Observe warning message is styled
https://github.com/constellation-app/constellation/issues/2188

Fix styling on note view error message

---

CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/ImageGraphBuilderAction.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/ImageGraphBuilderPlugin.java

Update "image" to "images(s)" for parameter and menu option.
Indicates to user that multiple images may be loaded
1. Select from menu Experimental > Build Graph > From Image(s)...
2. Observe menu option and dialog's first parameter now refers to image(s)
#2190

Update image to images(s) for Experimental > Build Graph

---

CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/sna/centrality/KatzCentralityPlugin.java

Arrays have been replaced with ArrayLists in the processing of the Katz Centrality Analytic data.
This code change prevents a JVM crash that occurs when using the Katz Centrality Analytic on a mid-large graph.
The underlying issue is within Java itself with its management of Arrays.
A newer version of Java (22) seems to have addressed the issue, but we cannot move to that version yet due to other compatibility issues.
Considered updating Java to a newer version, but no other versions at the same release level were suitable.
To avoid an abrupt crash of the application.
Katz Centrality Analytic will perform as expected, without any surprise abrupt crashes. …

Katz Centrality Analytics: Fix to prevent JVM from crashing.

---

CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/compare/CompareGraphAction.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedImportController.java
CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/DelimitedSourcePane.java
CoreTesting/src/au/gov/asd/tac/constellation/testing/TestNotificationsAction.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/NotifyDisplayer.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/ScreenWindowsHelper.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/NotifyDisplayerNGTest.java
CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/ScreenWindowsHelperNGTest.java

- Added overloaded methods for NotifyDisplayer.displayAlert and NotifyDisplayer.displayLargeAlert to be able to set the dialog to pop up at specified point. 
- Added new utility to obtain the main window's centre (ScreenWindowsHelper.getMainWindowCentrePoint())
- Updated some actions to utilise the new utility to set the displayAlerts to be displayed on the same screen/monitor: Compare graph, template warning messages, test notifications
- Added 2 unit tests to test passing in the point parameter
- Added logic to enable importFileParserComboBox if no files were added to file selection list
To display Alerts on the same screen as the app.
1. Create a new …

Update NotifyDisplayer to popup on same screen

---

CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/AnalyticSchemaFactory.java

The change made here (#2053) aimed to resolve the logic issue with how the foreground icon is resolved. As it turns out, the fix wasn't quite right as it made the assumption that any non-schema type would have a null foreground icon, whereas it actually had the default unknown icon. Since the icon was never null, the subsequent else if statement was never reached.
This PR fixes that logic so that rather first checking is the icon is null, it checks if the icons matches the default unknown icon
Fix a logic issue in Core
Non-schema types can once again now have icons applied if there is an existing icon matching the type name + still adheres to checking …

fixed foreground icon schema resolve

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPlugin.java

Updated the Extract Words from Text plugin to extract words from other languages when they are included in the Whitelist.
Extract Words from Text using the Whitelist
Step 1: Create a graph with some nodes and transactions
Step 2: Add some words in a different language in the Activity attribute of the transactions 
Step 3: Extract those words using the Extract Words from Text plugin in the Data Access View
Step 4: Observe that nodes have been created with those words
Extract Words from Text without using the Whitelist
Repeat Steps 1-2
Use Extract Words from Text with no parameters
Observe the nodes have still been created 
#2202

Update Extract Words From Text

---

CoreSecurity/src/au/gov/asd/tac/constellation/security/password/PasswordDeobfuscator.java
CoreSecurity/src/au/gov/asd/tac/constellation/security/password/PasswordObfuscator.java
CoreSecurity/src/au/gov/asd/tac/constellation/security/password/PasswordUtilities.java
CoreSecurity/test/unit/src/au/gov/asd/tac/constellation/security/password/PasswordDeobfuscatorNGTest.java
CoreSecurity/test/unit/src/au/gov/asd/tac/constellation/security/password/PasswordObfuscatorNGTest.java
CoreSecurity/test/unit/src/au/gov/asd/tac/constellation/security/password/PasswordUtilitiesNGTest.java

Fix exception being thrown because of the wrong type of obfuscator and deobfuscator being used.
The constant `T_LEN` has also been added in `PasswordUtilities` as it's required for the new `GCMParameterSpec` obfuscator/deobfuscator. `T_LEN` can only have the values {128, 120, 112, 104, 96}, or {64, 32} for certain applications, so I have chosen 128 (info from: https://docs.oracle.com/javase/8/docs/api/javax/crypto/spec/GCMParameterSpec.html).
Feel free to request any changes.
N/A
N/A
Exception no longer thrown
May mess with password related systems. There didn't seem to be any unit testing for the security module until now …

Replace password obfuscator and deobfuscator

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArranger.java

Found issue where sorting code was being called repeatedly inside a loop.
Code should be run after the loop completes.
N/A
Useability of hierarchical arrangement on large graphs.
Useability of hierarchical arrangement on large graphs.
N/A
Confirm the hierarchy arrangement completes within a reasonable time on larger graphs.

Fix issue with Hierarchical arrangement on large graphs.

---

.github/workflows/nightly-build.yml
.github/workflows/release-build.yml

Updated the nightly and release build scripts to use upload-artifact v4 since v1-3 are being deprecated.
The main change from v3 to v4 was that artifacts were now immutable having previously been mutable. Having reviewed the migration file for v4 https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md, it doesn't appear that our use cases require any special adjustments in order to account for the immutability of artifacts since our jobs create a new artifact for each build version and nothing is altered about the artifact after upload. This may need to be monitored though after merging in case issues arise.
upload-artifact v1-3 is being …

updated build script to run upload-artifact v4

---

CorePreferences/src/au/gov/asd/tac/constellation/preferences/LookAndFeelModuleInstall.java

Fixed minor bug that caused an extra entry of FlatLAF Dark to appear in look and feel section. Unsure if this occurs in a built version of consty or not.
N/A
N/A
Bug fixed
None.
1. Rebuild Core preferences module
2. Open Consty
3. Setup->Options->Appearance->Look and Feel
4. Click down drop and observe one occurrence of FlatLaf Dark
https://github.com/constellation-app/constellation/issues/2134

Fix duplicate FlatLAF Dark options

---

CoreGraphNode/src/au/gov/asd/tac/constellation/graph/node/plugins/DefaultPluginInteraction.java

Update the time display in plugin reporter to be local time.
This is needed as the time displayed would be better understood in the plugin reporter.
This is needed as the time displayed would be better understood in the plugin reporter.
Steps:
1. Open an existing graph in Consty
2. Open Data Access View and select Select All and click Go.
3. Open Plugin Reporter and expand Select All. Observe the time to be local time (with UTC offset).
#49

Update plugin reporter

---

CHANGELOG.md
CoreVisualGraph/test/unit/src/au/gov/asd/tac/constellation/graph/visual/plugins/hop/HopFullNGTest.java
CoreVisualGraph/test/unit/src/au/gov/asd/tac/constellation/graph/visual/plugins/hop/HopHalfNGTest.java
CoreVisualGraph/test/unit/src/au/gov/asd/tac/constellation/graph/visual/plugins/hop/HopOneNGTest.java
CoreVisualGraph/test/unit/src/au/gov/asd/tac/constellation/graph/visual/plugins/merge/MergeNodeNGTest.java
CoreVisualGraph/test/unit/src/au/gov/asd/tac/constellation/graph/visual/utilities/BoundingBoxUtilitiesNGTest.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/VisualSchemaFactory.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV1UpdateProvider.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV6UpdateProvider.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV7UpdateProvider.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/plugins/CompleteSchemaPlugin.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/utilities/ColorblindUtilities.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/VisualSchemaFactoryNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/compatibility/VisualSchemaV7UpdateProviderNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/plugins/CompleteSchemaPluginNGTest.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/utilities/ColorblindUtilitiesNGTest.java

- updated some of the unit tests in Visual Graph
- added some unit tests to classes in Visual Schema missing unit tests
- did some general code cleanup in Visual Schema, removing some unused functions
- moved the unit tests for CompleteWithSchema into the Visual Schema, where the class is actually based. To make it fit, some changes did need to be made to the unit tests in order for them to work (as some elements being used are not available for use in Visual Schema)
Increased unit test coverage, removal of unused code increases maintainability
More unit tests, increased maintainability
#413

Visual Schema + Graph Unit Tests

---

CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
CoreWordCloudView/release/modules/ext/docs/CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/word-cloud-view.md
CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudTopComponent.java

Word cloud view has been moved out of the experimental tab, and into the regular views tab. Documentation has also been updated to reflect this.
N/A
N/A
Word cloud is now accessible from views tab.
None.
1. Open consty
2. Click Views
3. Observe Word Cloud View is present
4. Click Experimental->Views
5. Observe Word Cloud View is not present
https://github.com/constellation-app/constellation/issues/2232

Move word cloud to views tab

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpener.java
CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpenerNGTest.java

Changed what type of variable stored the track graphs currently being opened. Fixes issue where the same path with different file separators would be treated as different paths.
Perhaps file separators could be dynamically replaced to be uniform, but I feel storing file paths with the `Path` variable type would be less error prone.
N/A
Bug preventing re opening of graphs is fixed
None.
If already have a saved graph file:
1. Open consty
2. Open graph
3. Close graph, but DONT close consty
4. Open graph again
5. Observe graph not opening
If you don't already have a graph saved:
1. Open consty
2. Create graph and save
3. Close graph and open again, should …

Fix unable to open graph more than once

---

CoreAnalyticView/nbproject/project.properties
CoreConversationView/test/unit/src/au/gov/asd/tac/constellation/views/conversationview/ConversationNGTest.java
CoreConversationView/test/unit/src/au/gov/asd/tac/constellation/views/conversationview/ConversationViewTopComponentNGTest.java
CoreDataAccessView/nbproject/project.properties
CoreErrorReportView/nbproject/project.properties
CoreFindView/nbproject/project.properties
CoreGraphNode/nbproject/project.properties
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/Generator.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/utilities/GeneratorNGTest.java
CoreImportExportPlugins/nbproject/project.properties
CoreInteractiveGraph/nbproject/project.properties
CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/io/AutosaveStartup.java
CoreLayersView/nbproject/project.properties
CoreNotesView/nbproject/project.properties
CorePluginFramework/nbproject/project.properties
CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/logging/ConstellationLoggerStart.java
CorePluginReporterView/nbproject/project.properties
CoreQualityControlView/nbproject/project.properties
CoreTableView/nbproject/project.properties
CoreUtilities/nbproject/project.properties
CoreViewFramework/src/au/gov/asd/tac/constellation/views/JavaFxTopComponent.java
CoreVisualSchema/nbproject/project.properties
CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeStartup.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewStartup.java
CoreWordCloudView/nbproject/project.properties

Fixed some module security issues found while running unit tests independently.
Unit tests should run without issues whichever way they are launched.

Module security updates and unit test fix.

---

CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/LineBatcher.java

Fixed a bug where undirected transactions would appear directed until interacted with again.
N/A
N/A
Transactions no correctly display as directed or undirected.
None.
1. Create a graph in edge mode with two Nodes, A and B.
2. Add a transaction from Node A to Node B
3. Change the value of the attribute "directed" to False (Notice the arrow disappear from the end of the transaction).
4. Add a transaction from Node B to node A
5. Observe undirected transaction still appears as undirected
https://github.com/constellation-app/constellation/issues/1889

Fix bug causing undirected transactions to appear directed

---

CHANGELOG.md
CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/interaction/CompositeNodeStateAttributeInteraction.java
CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/io/RawIOProvider.java
CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/io/VertexTypeIOProvider.java
CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/CompositeNodeState.java
CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/CompositeStatus.java
CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/ContractedCompositeNodeState.java
CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV5UpdateProvider.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/AnalyticSchemaFactoryNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/CompositeNodeStateAttributeDescriptionNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/RawAttributeDescriptionNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/TransactionTypeAttributeDescriptionNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/VertexTypeAttributeDescriptionNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/interaction/CompositeNodeStateAttributeInteractionNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/interaction/RawAttributeInteractionNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/interaction/TransactionTypeAttributeInteractionNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/interaction/VertexTypeAttributeInteractionNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/io/CompositeNodeStateIOProviderNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/io/RawIOProviderNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/io/TransactionTypeIOProviderNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/CompositeNodeStateNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/ContractedCompositeNodeStateNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/ExpandedCompositeNodeStateNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/RawDataNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV5UpdateProviderNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/concept/AnalyticConceptNGTest.java
CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/utilities/CompositeUtilitiesNGTest.java
CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/processing/GraphRecordStoreUtilities.java

Added unit tests for the remaining classes in Core Analytic Schema requiring testing. Also updated some tests from the previous PR.
Also like the last one, included a small amount of code cleanup.
More unit tests is better.
#413

More Analytic Schema Tests

---

CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/BinComparator.java

Sorting by Label (Number) had issues when trying to sort bins that weren't numeric. I have fixed the logic so that instead of simply returning -1 if both bins aren't numeric (which was prone to breaking transitivity), it instead just compares as it would for the Label (Text)
Bug fix
Bug fix
Ran steps to reproduce as outlined in original issue
#2255

fixed numeric sort for non-numeric bins

---

CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java

When dragging elements on the graph with mouse, they are not animating but jump directly to the end point.
Added back some code in DefaultInteractionEventHandler which forces the interaction graph's operations to be performed.
> if (!operations.isEmpty()) {
if (interactionGraph != null) {
interactionGraph = interactionGraph.flush(false);
}
operations.forEach(op -> manager.addOperation(op));
}
This means that the previous operations (movement of the elements' positions) are updated on the graph.
This is a core user interaction experience that had been removed.
1. Open Constellation. Open a valid graph with vertices and transactions.
2. Right-click on a …

Graph elements not animating when dragged with mouse

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ImportGraphFilePlugin.java

Selecting a different filetype may accidently attempt to open the previous selected file in File name.
Fix to clear filename when filetype changes.
To prevent accidental mismatch of file types and filenames, fix by clearing filename when filetype changes.
Steps to Reproduce
1.Open Constellation
2. Open a new graph
3. Open Data Access View
4. Select Import File Graph
5. Select File Type ML / GraphML / Pajek from drop down list (make sure you have the file saved locally)
6. Select File Open -> browse to your drive for the file type> Click Open Button
Click GO
6.Keep your file name in file box but change the File type now. The File name should be cleared. …

Fix to clear filename when filetype changes

---

CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/CompleteGraphBuilderPlugin.java
CoreTesting/test/unit/src/au/gov/asd/tac/constellation/testing/construction/CompleteGraphBuilderPluginNGTest.java
CoreUtilities/src/au/gov/asd/tac/constellation/utilities/SystemUtilities.java

Added a popup to the complete graph builder that warns the user if a graph will have too many transactions. The current threshold is 100,000 transactions. Users can choose to proceed or cancel.
N/A
N/A
Users will be warned that the graph they choose to build will be large and may affect cosnty.
None.
1. Open Consty and make a new empty graph
2. Click Experimental -> Build Graph - Complete Graph Builder
3. Enter 1000 for number of nodes
4. Click Build
5. Observe warning for 24975000 transactions
6. Click cancel
7. Again, Click Experimental -> Build Graph - Complete Graph Builder
8. Uncheck random edge weights, and enter 1000 for number of nodes
9. Observe …

Add warning popup to complete graph builder

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewTopComponent.java

Fix for the issue where the Notes View does not update the state of the view correctly when changing between graphs if the view is minimized. The Create Note button should now always be enabled when a graph is active.
Also did some minor code cleanup in NotesViewPane
Allows users to use the full functionality of the Notes View when it is minimized.
1. Open Constellation and the Notes View. Minimize the Notes View
2. Open or create a graph
3. Click on the Notes View and observe that the Create Note button is still active
#2273

Fix Issue with Notes View State

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticConfigurationPane.java

Added scroll pane to allow users to scroll down in the information pane. Also fixes an apparent bug where the user could change the parameters of "Betweeness centrality Analytic" in the "Questions" section.
N/A
N/A
Allows user to access all parameters without resizing the application.
None.
1. Open consty and make a new sphere graph
2. Views->Analytic view
3. In the analytic view select: Categories -> Centrality then tick "Betweeness centrality Analytic" in the Analytics section. 
4. Click Run, and a table of results will be displayed.
5. Observe a scroll bar has appeared in the Information section, allowing you to access the remaining parameters …

Add scroll pane to Analytic View's information section

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewTopComponent.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewTopComponent.java

Fix for the issue where the Analytic View does not update the state of the view correctly when changing between graphs if the view is minimized. The run button stays disabled even when a graph becomes active.
Also fixed a null pointer that was occurring in the Notes View when a graph was closed and the Welcome Tab became active.
Allows users to use the full functionality of the Analytic View when it is minimized. 
Analytic View Issue 
1. Open Constellation and the Analytic View. Minimize the Analytic View 
2. Open or create a graph
3. Click on the Run button and see that an analytic has been run 
Notes View Issue
1. Open Constellation …

Fix issue with Analytic View state when minimized

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
CoreQualityControlView/test/unit/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPaneNGTest.java

Adjusted the alpha of the quality control view's rows. Allowing the selected row to be more noticable.
N/A
N/A
User can now more easily see the selected row in the quality control view.
None.
1.  Open consty and open a graph.
2. Views -> Quality Control View
3. Click on a row in the quality control view
4. Observe selected row's highlight is visible
https://github.com/constellation-app/constellation/issues/2282

Make selection more visible in quality control view

---

CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/importing/ExtractWordsFromTextPlugin.java

Currently the Extract Words from Text plugin in the Data Access View only able to match against words using the English alphabet. 
This change allows for the plugin to match against and extract words using any language or alphabet.  
This change also allows for words with apostrophes, dashes or underscores to be extracted as whole words, instead of just parts of the word.
Fixes a bug in Core and adds additional functionality to an existing plugin.
Allows users to extract words in any language from the data on their graphs.
1. Create or open a graph with at least 2 nodes and 1 transaction
2. Add the Content attribute to the transaction and add a value …

Extract Words from Text on Non-English Characters

---

CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/factory/TableCellFactory.java

Due to a recent change in the Table View a bug is occurring where columns where some of the data is null is being overwritten by the data in the other rows when scrolling in the table. This change fixes this bug while still keeping the functionality added by the word wrapping PR. 
1. Create a graph with about 30 nodes
2. Add the node attribute Geo.Country 
3. Assign a few of the nodes with some different country values
4. Open the Table View, swap the Element Type to Node and add the column for the source attribute Geo.Country
5. Scroll up and down the data in the Table View and see that the null values are not replaced with other …

Fix Table View Data Duplication Bug

---

CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccess.java
CoreVisualSchema/release/modules/ext/docs/CoreVisualSchema/complete-with-schema.md
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/VisualSchemaPluginRegistry.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/plugins/CompleteSchemaPlugin.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/plugins/CompleteSchemaSelectionAction.java
CoreVisualSchema/src/au/gov/asd/tac/constellation/graph/schema/visual/plugins/CompleteSchemaSelectionPlugin.java
CoreVisualSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/visual/plugins/CompleteSchemaSelectionPluginNGTest.java
CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt

Added a plugin to use Complete with Schema only on the selected elements of the graph.
The changes in GraphVisualAccess.java have been added to allow for the colorblind options to still be applied to only the selected part of the graph instead of the whole graph when Complete with Schema on Selection is run. It allows for nodes and transactions to keep their set colors instead of turning grey.
Added new functionality in Core
1. Create a graph
2. Select part of the graph
3. Run Complete with Schema on Selection (found in the Tools menu)
4. Check that Complete with Schema was only run on the selected elements on the graph
#2311

Add Complete with Schema on Selection Plugin

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/utilities/AnalyticUtilities.java
onlinePandocTemplate.txt

Hotfix for the template that the help pages are modified by when they are pulled into the online help repo, updated to match what the new paths are for the help files.

Hotfix for online help template

---

CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticResultsPane.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewTopComponent.java
CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/visualisation/HideVisualisation.java

The Hide slider in the Analytic View was enabled when it was meant to be disabled and vice versa. The slider also wasn't able to be moved correctly due to the Analytic View refreshing on every graph change event. 
The change allows for the Analytic View to still be updated when the view is minimised but stops the view from refreshing constantly when the hide slider is moved. 
Bugfix in Core
1. Open or create a graph with at least a few nodes and transactions
2. Open the Analytic View and run an analytic
3. Try to move the Hide slider, it should not move
4. Click the Hide button and then move the Hide slider, the slider should move and be responsive
#2349

Analytic View Hide Slider Fix

---

CoreHelp/src/au/gov/asd/tac/constellation/help/HelpServlet.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/HelpServletNGTest.java

The issue was cause if the app was run from directories/folders with spaces in their names.
Added code to replace spaces after obtaining base directory.
This needs to be in core for the help pages to work.
This needs to be in core for the help pages to work.
1. Install constellation in a folder with spaces in its name eg. "C:/test folder"
2. Run Consty and open a help page from within Consty (click on a ? in one of the views)
3. On the help page that has opened, navigate down the documentation hierarchy and click on Selection -> Blaze selection
Page for Blaze selection should be displayed (not a page with an exception).
#2345

Spaces in directory name causes too many redirects for help page to load

---

CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/AbstractInclusionGraph.java

Fixed a typo in that would make it possible for pinned vertices to be moved in an arrangement plugin, only if all vertices were pinned.
N/A
N/A
Pinned vertices now still in their pinned positions.
None.
1. Open consty and make a sphere graph
2. Select all vertices, then go Arrange->Pin Vertex Positions
3. Now go Arrange->Grid and observe graph does not get arranged
https://github.com/constellation-app/constellation/issues/2364

Fix pinned vertices still being affected by arrangement plugins

---

CoreTimelineView/nbproject/project.xml
CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/clustering/ClusteringManager.java
CoreTimelineView/test/unit/src/au/gov/asd/tac/constellation/views/timeline/clustering/ClusteringManagerNGTest.java

Added a simple null check to prevent null pointer exception. Also refactored the code to be more readable.
N/A
N/A
Null pointer is no longer thrown, and timeline view is more usable.
None.
1. Create a new graph and add Sphere Graph of nodes=5 and transactions=5 (Experimental->Build Graph->Sphere Graph Builder).
2. Open the Timeline View.
3. Select a handful of nodes in the graph.
4. Select Dim Excluded Nodes from the 3rd dropdown list in the Timeline view. Then ensure that "Show node Labels" buttons are selected.
5. In the dropdown list of attributes (to the right of Show Node Labels), select the "Label" attribute. Observe no null pointers are thrown …

Fix NPE for timeline view

---

CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java
CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/draw/CreateTransactionPluginNGTest.java

Reverting the changes made for PR #2368 which was the fix for PR #2316.
Returning the code to what it was before the fix for the issue where destroying all composites created new vertexes and transactions (#2291), will fix the subsequent effects discovered (issues #2379 and #2343). 
But the issue #2291 will return as an issue. This will need an alternative solution.
Steps for merge nodes issue:
1. Open Consty
2. Select Experimental -> Build Graph-> Structured Graph Builder
3. Create a Structured Graph with default values
4. Select any section of the graph
5. Select Tools->Merge Nodes from menu
6. Uncheck few check boxes from Left Column
7. Click OK
8. …

Revert undirected transactions that was Destroy all Composites fix

---

CoreHelp/src/au/gov/asd/tac/constellation/help/ConstellationHelpDisplayer.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/Generator.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TOCGenerator.java
CoreHelp/src/au/gov/asd/tac/constellation/help/utilities/toc/TreeNode.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/utilities/GeneratorNGTest.java
CoreHelp/test/unit/src/au/gov/asd/tac/constellation/help/utilities/toc/TOCGeneratorNGTest.java
toc.md

Fix for the online help TOC file links. 
Fixes online help

Hotfix: Fixing online help toc links

---

CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/utilities/NewNotePane.java

Scrollbar was intermittently appearing, making it hard to view the whole note (particularly when there are no newlines).
Setting the preview pane's pref height and width and viewport height and width helps resolve this.
ReizeTextFlows function is therefore not needed.
Scrollbar allows viewing of the whole note.
1. Open any new/Existing Graph
2. Views-> Note View
3. Create Note -> Enter Title -> Write Note (long note without newline or line breaks).
4. Click Preview -> Font is different; background color is different (as expected) and whole note can be viewed (using scrollbar when necessary).
#2357

Made scrollbar for Notes preview tab appear when needed

---

CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTileRenderer.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/overlays/InfoOverlay.java
CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/providers/DefaultMapProvider.java

When switching from another map with a higher zoom level than the Maximum zoom of default map threw an exception. It has been fixed, and additionally when switching the maps, the zoom range is now reset to the max zoom level of the current map.
- Open the Map View and zoom in all the way on one of the maps that isn't the default map
- Swap to the default map
- Observe no exception is thrown and verify the zoom bar displays the correct range of the new map.
https://github.com/constellation-app/constellation/issues/2341

Fix the exception when switching from another map to default map

---

CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramTopComponent.java

Cannot Invoke exceptions were thrown in the histogram when the Property for Attribute Category is not set and Select button is pressed for below combinations:
Graph Element: Any, and select the correct element in the graph
Property : Empty as when loaded. (Selecting to empty from the drop down doesn't throw the exception)
Selection Mode: "Within Existing Selection" or "Add To Existing Selection"
Then pressing the  Select button throws the exception.
binCreator is no longer null when the Attribute value is empty string after the changes here, preventing the exceptions.
1) Add null checks in functions the exceptions are thrown: E.g.: `filterSelection `, …

Fix the exceptions in histogram when Property for Attribute Category is not set

---

CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java

While in minimized view, the Quality Control View was throwing an exception when the nodes were deleted from the Quality Control View table when using Delete From Graph . This occurs after the nodes previously been deleted from the table while the QCV is in minimized mode (but activated) - the reason being that the table had not been updated after the first Delete From Graph.
This is an issue with isVisible field (in AbstractTopComponent) being set to false while in "minimized" mode.
The solution was to override "componentActivated" and set isVisible to true; This method is activated when the Quality Control View is minimized but made visible. This will …

Quality Control View Delete From Graph Exception - table not updating

---

.github/workflows/release-build.yml
CoreWebServer/src/au/gov/asd/tac/constellation/webserver/api/swagger/constellation.json

Swagger UI now displays the release version next to the CONSTELLATION REST Services header.
Tools-> Display REST Server Documentation
Verify the correct version is displayed next to the `CONSTELLATION REST Services` header in the Sawgger UI Page. It'll be (under development) when running from netbeans.
https://github.com/constellation-app/constellation/issues/2344

Display the release version in Swagger UI

---

.github/workflows/build-and-scan.yml

Bug fix in build-and-scan.yml
N/A
N/A
Verbose logging is now functional again
None
1. Run tests online, with verbose-logging tag added.
2. Observe log files are verbose
1. Run tests online, WITHOUT verbose-logging tag added.
2. Observe log files are NOT verbose

Fix verbose logging not working online

---

ProjectUpdater/src/au/gov/asd/tac/constellation/projectupdater/ProjectUpdater.java

As recommended by Sonar, adding setting the `FEATURE_SECURE_PROCESSING` feature to true for instances of `TransformerFactory`
Resolves an issue identified by sonar
Resolves an issue identified by sonar

added feature secure processing to TransformerFactory instances

---

.github/workflows/build-and-scan.yml
.githubutilities/sonar.sh

The sonar scan was failing when running in master even though there were no issues running in PR branches. It seems the issue lies in the arguments passed to the `sonar.sh` script. In a PR branch, all 5 arguments are non-blank and there are no issues matching up arguments. On the other hand in master, 3 of the arguments in the middle are empty and so there is an argument mismatch. This change adds quotes around the arguments in the hopes this enables master to recognise the empty argument values properly).
Sonar scanning is useful for the codebase
Sonar scanning working in master again

Fixed Sonar Scan
